### ISSUE TITLE
"Can't parse line from whitelist: " v6 address not working in whitelist FNM Community

### ISSUE THREAD

**Issue by Lostepic** [pavel-odintsov/fastnetmon#1001]
Hello,

Very strange one, seems using community version when I add a IPv4 address to the `/etc/networks_whitelist` it picks it up and works fine, when I add in an IPv6 that has been banned so just copied the address from the ban list it instead shows 

`2024-01-26 05:30:59,878 [INFO] Read configuration file
2024-01-26 05:30:59,878 [ERROR] Can't parse line from whitelist: 2a0a:xxxx:xxxx::10/128
2024-01-26 05:30:59,878 [INFO] We loaded 1 networks from whitelist file
2024-01-26 05:30:59,878 [INFO] We are working on Linux and could use ip tool for detecting local IP's
2024-01-26 05:30:59,902 [INFO] We found 2 local IP addresses and will monitor they
2024-01-26 05:30:59,902 [INFO] We loaded 6 networks from networks file
2024-01-26 05:30:59,902 [INFO] Totally we have 3 IPv4 subnets
2024-01-26 05:30:59,902 [INFO] Totally we have 5 IPv6 subnets`

I have tried with the subnet expanded, I have also tried just copying all the networks from the `/etc/networks_list` to the whitelist and still it picks up ipv4 fine but not ipv6

**Comment by pavel-odintsov** [comment]
Hello!

I'm sorry but whitelist does not support IPv6 addresses.

Sincerely yours, Pavel Odintsov

**Comment by Lostepic** [comment]
Is it possible to add this to the community version, and is it a feature in advanced? so far am having great time with the community except this not being able to whitelist an ipv6 address

**Comment by pavel-odintsov** [comment]
Hello!

I'll convert this issue to feature request and it will be added to tasks
queue but I cannot provide any estimations about time when we will deliver
it.

Advanced edition has IPv6 hostgroups support and it can be used for
replication whitelist behaviour by disabling ban actions

Sincerely yours, Pavel Odintsov

**Comment by potvinp** [comment]
+1 on this feature request. Currently it's a bit difficult to run a dual-stack Ookla speedtest server when IPv6 gets banned since it triggers their systems to remove it due to their requirements lol

**Comment by pavel-odintsov** [comment]
Thank you for feedback!

Is there is any way to get list of all Ookla speed test IPs as feed?

**Comment by potvinp** [comment]
I don't believe so unfortunately, as they're all provided to Ookla by network operators so they're spread across various domains and subnets. I don't think it's too much of an issue personally, however it would be nice for network operators who run these servers alongside FastNetMon to be able to whitelist the v6 addresses their servers are on to prevent them from being removed.

**Comment by pavel-odintsov** [comment]
Done! :)
