### ISSUE TITLE
Disable networks_files

### ISSUE THREAD

**Issue by Talhazzers** [pavel-odintsov/fastnetmon#1006]
* Your operating system name and version? Ubuntu 20.04
* Please attach your /etc/fastnetmon.conf configuration file https://justpaste.it/egytu
* What capture engine are you using: Netflow, sFlow, miror? sFlow
* If you are using Netflow or sFlow, please specify version, vendor name, model name and firmware of agent device.  Junos 15 - Juniper 4550

I don't want to use /etc/networks_files. I want Fastnetmon to monitor all IP addresses. For this, I set the dump_all_traffic and other_traffic options to on, but it did not work.

**Comment by pavel-odintsov** [comment]
Hello!

That's fundamental part of FastNetMon Community design and it cannot be
changed.

You need to provide list of networks as FastNetMon needs to know which
networks is owned by you and which one is remote.

FastNetMon advanced has multiple options address it by reading networks
list from BGP session:
https://fastnetmon.com/docs-fnm-advanced/subnet-collection-from-bgp-peering-session/
<https://fastnetmon.com/docs-fnm-advanced/subnet-collection-from-bgp-peering-session/?amp>
and
if you want to try it here:
https://fastnetmon.com/trial/ <https://fastnetmon.com/trial/?amp>

Sincerely yours, Pavel Odintsov
