### ISSUE TITLE
FASTNETMON NOT WORKING

### ISSUE THREAD

**Issue by cmlangeni** [pavel-odintsov/fastnetmon#1028]
I have recently installed FastNetMon Community Edition on an Ubuntu 24.04 LTS server and configured it to use NetFlow data from a Cisco NCS 5500 router. I have also set up the IP list as per the configuration guidelines. However, when I run the fastnetmon_client command, I do not receive any output or information as expected.

Here are the details of my setup for reference:
•	OS: Ubuntu 24.04 LTS
•	FastNetMon Version: Version: 1.2.8 a813f7da
•	Flow Type: NetFlow v9
•	Source Device: Cisco NCS 5500 IOSXR  7.5.2
o	NetFlow exporter set up on the Cisco NCS 5500 attached.
o	Relevant IP ranges configured in the fastnetmon.conf file attached.
o	
Despite this, there is no data displayed when I execute fastnetmon_api_client ban 102.70.1.254 i get 
"Query failed This IP does not belong to our subnets". Could you please assist me in diagnosing the issue? Are there any specific logs, tests, or configurations you would recommend checking?

Looking forward to your guidance.
[TNM fastnetmon.zip](https://github.com/user-attachments/files/17966291/TNM.fastnetmon.zip)

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for reaching us here. I can see that you've contacted our support and I'm closing this issue.
