### ISSUE TITLE
Incorrect calculation flowset_length in process_netflow_packet_v9

### ISSUE THREAD

**Issue by Klavishnik** [pavel-odintsov/fastnetmon#1029]
* Your operating system name and version?
Ubuntu 24.04
```bash
uname -a
Linux user-test-fuzz 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
* Please attach your /etc/fastnetmon.conf configuration file
I changed the file extension to `.txt`, so I could add it as an attachment
[fastnetmon.conf.txt](https://github.com/user-attachments/files/18102538/fastnetmon.conf.txt)

* What capture engine are you using: Netflow, sFlow, miror?
 Netflow
* If you are using Netflow or sFlow, please specify version, vendor name, model name and firmware of agent device.  
I am submitting manually generated traffic
------------------------------------------------------------------------------------------------------------------------------

Hello!
I am researching your project and while fuzz-testing netflow processing functions. I found incorrect behavior when processing a data packet.

The error occurs in the function `process_netflow_packet_v9`, in file
```bash
netflow_plugin/netflow_v9_collector.cpp:1515
```

The data package I am submitting is below:

![image](https://github.com/user-attachments/assets/c2ad1cdb-9af5-4826-80a4-1238028419e9)

The data is sent by the command:
```bash
nc 127.0.0.1 2055 < <file>
```

This data packet is 49 bytes long and is processed in two loop iterations at line 1546:
![image](https://github.com/user-attachments/assets/493aa0f7-4f44-4ac4-bae9-2168881540c1)

The instance of class `const netflow9_flowset_header_common_t* flowset` is written 4 bytes after the offset from the beginning of the packet array by offset (offset is static and on my architecture takes 20 bytes).

4 bytes is the size of two variables in a class instance:
![image](https://github.com/user-attachments/assets/cc3ab023-10c4-4f4f-bbfb-b74e083eef87)

At the end of the loop, the offset variable is changed (line 1611) and now its size is 46.

When executing line 1555 
```C
 const netflow9_flowset_header_common_t* flowset = (const netflow9_flowset_header_common_t*)(packet + offset);
 ```
 on the second iteration of the loop, 4 bytes of data will be required again. The problem is that in the packet that I send, there are three free bytes of data (49-46 = 3), so instead of two bytes, only one byte remains for the variable `uint16_t length`. Therefore, to get the length, the program climbs onto a "foreign" byte of code: 
 
 
![image](https://github.com/user-attachments/assets/fcaba1e0-f158-4da3-9a11-8e7ced9f5cd6)

In this particular situation, this code byte is equal to 00, so the logic is not violated.
When instrumenting the code, for example, with ASAN sanitizers, this section of the code will be marked by the sanitizer and will be equal not to 0x00, but to 0xBE. Executing the section of code on line 1558 will trigger the sanitizer. I attach a picture
![image](https://github.com/user-attachments/assets/fc016f50-d84c-4186-9aa9-5ebc49177708)

Lines 1557 and 1558 contain the following code:
```C
 uint32_t flowset_id     = ntohs(flowset->flowset_id);
 uint32_t flowset_length = ntohs(flowset->length);
  ```
  When executing the code on line 1558, there is also a violation of conversions due to access to "foreign" memory, so the value is calculated incorrectly.
  
![image](https://github.com/user-attachments/assets/0c271a66-a970-490e-95d3-c771a895cacc)

I have attached the data set that causes this behavior in the archive.
[netflow_length_test_cast.tar.gz](https://github.com/user-attachments/files/18102811/netflow_length_test_cast.tar.gz)

**Comment by pavel-odintsov** [comment]
Hello!

That's incredible level of research! Thank you very much for your effort.

It's pretty chaotic pre-Christmas period but I'll do my best to investigate it further ASAP

**Comment by pavel-odintsov** [comment]
I created dump with example of data for Wireshark [netflow_v9_issue.zip](https://github.com/user-attachments/files/18129738/netflow_v9_issue.zip)
