### ISSUE TITLE
Incorrect calculation flowset_length in process_ipfix_packet

### ISSUE THREAD

**Issue by Klavishnik** [pavel-odintsov/fastnetmon#1030]
The same  [this issue](https://github.com/pavel-odintsov/fastnetmon/issues/1029) but for function `process_ipfix_packet` in `netflow_plugin/ipfix_collector.cpp`

[ipfix_length_test_cast.tar.gz](https://github.com/user-attachments/files/18103567/ipfix_length_test_cast.tar.gz)

![image](https://github.com/user-attachments/assets/d29e91d4-bd00-4a8b-aefd-a5e97425d1b9)

**Comment by pavel-odintsov** [comment]
I've prepared pcap dump for reproduce [ipfix_issue.zip](https://github.com/user-attachments/files/18130680/ipfix_issue.zip)
