### ISSUE TITLE
Enhance protocol detection logic

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#189]
Current code for protocol detection is very simple:

``` bash
unsigned int get_max_used_protocol(uint64_t tcp, uint64_t udp, uint64_t icmp) {
    unsigned int max = my_max_on_defines(my_max_on_defines(udp, tcp), icmp);

    if (max == tcp) {
        return IPPROTO_TCP;
    } else if (max == udp) {
        return IPPROTO_UDP;
    } else if (max == icmp) {
        return IPPROTO_ICMP;
    }

    return 0;
}
```

And could introduce mistakes in case of 50% udp and 50% tcp.  We should implement ability types "mix" (when attack used multiple protocols) and should check when one protocol consumes 70% of bandwidth/pps and set variable to this protocol.

**Comment by pavel-odintsov** [comment]
Thank you so much! I will review code and apply path shortly!

**Comment by Phinitris** [comment]
Anytime ;)
Have created a pull request: #190

**Comment by Phinitris** [comment]
This feature request can be safely closed, because it's already implemented.
