### ISSUE TITLE
Dynamic thresholds

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#197]
As mentioned by Frank franklouwers in ticket https://github.com/pavel-odintsov/fastnetmon/issues/56 we could learn average pps/bps for specified hosts and set threshold according to this learned value.

**Comment by pavel-odintsov** [comment]
Hello, franklouwers!

Please look at this: https://github.com/FastVPSEestiOu/fastnetmon/issues/227

We collect average speed for subnet and you could tune your detector to average traffic :) And notify/block hosts when average traffic exceed.

**Comment by pavel-odintsov** [comment]
I have idea about implementing this approach with Graphite.

**Comment by chasgames** [comment]
Hi Pavel

Did this ever get integrated?

I am also interested in a dynamic threshold feature.

**Comment by pavel-odintsov** [comment]
It's not implemented yet.

**Comment by chasgames** [comment]
Ok, Happy to help test this when it is implemented. For example, our google cache servers consume high PPS constantly, rather than exclude it from the protection, it would be ideal for fastnetmon to learn this is normal traffic.

**Comment by pavel-odintsov** [comment]
Yes, it's very interesting feature. But you could implement it with some additional code for Graphite and custom groups.

**Comment by pavel-odintsov** [comment]
It's possible to implement such behaviour now. Just fill all data about traffic to InfluxDB/Graphite and then request average traffic and create host groups with custom thresholds for all your hosts.

**Comment by chasgames** [comment]
This sounds great Pavel, 

How do we push the average traffic to the host groups, do you have an example?

**Comment by pavel-odintsov** [comment]
Hello!

I do not have complete solution but it could look like:
1. Extract average traffic for whole day for each host
2. Create host_group for each host with specified threshold (whole day traffic + 50%)
3. Repeat each night / week

**Comment by Octolus** [comment]
We really need something like that, so it calculates average - and if a big jump, it dumps

**Comment by pavel-odintsov** [comment]
Thank you for feedback! Back in time we had LUA engine in FastNetMon but it was so unreliable and LUA itself causes many issues.

Do you have any ideas about dynamic engine which can solve your problem? Can you just alter FastNetMon's source code?

**Comment by Octolus** [comment]
I wouldn't have the experience to sadly, I was hoping there would be some way already built-in.

So it would create a dynamic threshold based on the traffic, then detect spikes, etc.

**Comment by pavel-odintsov** [comment]
Even task to store traffic is extremely challenging for big networks. There are no simple solution in this area. You can retrieve baselines from InfluxDB and then use them as thresholds. You can use this one as reference https://fastnetmon.com/docs-fnm-advanced/fastnetmon-naseline-calculation/ Community version uses different logic but you can check idea.

**Comment by pavel-odintsov** [comment]
Dynamic thresholds can be easily implemented by using metrics in TSDB metrics databases like this one and then loading these values as thresholds into configuration: https://fastnetmon.com/docs-fnm-advanced/fastnetmon-naseline-calculation/
