### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [pavel-odintsov/fastnetmon#218]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/FastVPSEestiOu/fastnetmon/blob/77454070e995bd2ef51f069ba363502434daba76/src/fastnetmon.cpp#L1664)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by pavel-odintsov** [comment]
Hello!

I do not like exceptions in C++ especially in multi thread code. With they code debugging become a nightmare. I prefer do not use exceptions at all. And I like I can do it :)

**Comment by pavel-odintsov** [comment]
Additionally, I have bunch of C code (netmap, pf_ring, patricia) where I can't use any C++ features.

**Comment by elfring** [comment]
Would you like to reuse [catch-all handlers](http://en.cppreference.com/w/cpp/language/try_catch "Catching of C++ exceptions") at more source code places?

**Comment by pavel-odintsov** [comment]
I do not like exceptions. I hate exceptions! :) If it not possible to avoid code with exceptions I isolate it with blocks of try/catch.
