### ISSUE TITLE
Add TCP injection attack detection "plugin"

### ISSUE THREAD

**Issue by david415** [pavel-odintsov/fastnetmon#282]
I suggest we add a plugin which is capable comprehensive TCP injection attack detection. In particular there are 5 attacks that are possible; described here:

https://github.com/david415/HoneyBadger_docs/blob/hackpad1/source/how-to-badger-the-puppet-masters.rst#tcp-injection-attack-categories

Reference code here:
https://github.com/david415/HoneyBadger

Note that honeyBadger has composite struct table driven unit tests... but we also have integration tests which are pcap file driven tests... and the data injection attack pcap files can be found in this git repo:
https://github.com/david415/honeybadger-pcap-files

(however i am starting a new collection of pcap files that contain RST injection attacks which honeybadger also detects)

You might also be interested to look at the work by Fox-IT as done in detecting injection attacks:
http://blog.fox-it.com/2015/04/20/deep-dive-into-quantum-insert/

In the public domain there is only Fox-IT's patch to Snort and Honeybadger that detect these attacks. I believe HoneyBadger to be far more comprehensive than the patch to Snort... Would you like FastNetMon to be the world's third to detect these attacks?

**Comment by pavel-odintsov** [comment]
Hello, nice work!

First of all, FastNetMon haven't any options for deep packet analyzer and should be modified enough deeply for adding this option. Secondly, we need patch flow tracker code which used for per-packet processing and now it's very slow.

TCP injection is very important but it's of of scope for DDoS/DoS detection toolkit. But I will be very appreciate for TCP level attack analyzer which could work on wire speed (14.6+ mpps).

**Comment by pavel-odintsov** [comment]
Hello, everybody!

I have answered for this request in issue here:
https://github.com/FastVPSEestiOu/fastnetmon/issues/282

Will be fine to hear feedback about it from Community.

On Sun, Jun 14, 2015 at 9:49 PM, David Stainton <notifications@github.com>
wrote:

> I suggest we add a plugin which is capable comprehensive TCP injection
> attack detection. In particular there are 5 attacks that are possible;
> described here:
>
>
> https://github.com/david415/HoneyBadger_docs/blob/hackpad1/source/how-to-badger-the-puppet-masters.rst#tcp-injection-attack-categories
>
> Reference code here:
> https://github.com/david415/HoneyBadger
>
> Note that honeyBadger has composite struct table driven unit tests... but
> we also have integration tests which are pcap file driven tests... and the
> data injection attack pcap files can be found in this git repo:
> https://github.com/david415/honeybadger-pcap-files
>
> (however i am starting a new collection of pcap files that contain RST
> injection attacks which honeybadger also detects)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/282>.
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by david415** [comment]
OK that makes sense. Handshake hijack attacks could be detected at wire speed but the other attacks require full TCP reassembly written to a ring buffer for later retrospective analysis... in fact... a full byte comparison of overlapping stream contents is needed to eliminate false positives... that is normal TCP retransmissions.

**Comment by pavel-odintsov** [comment]
Yep, but if you help me with wire speed TCP analyzer we could offer huge benefits for everyone! :)

**Comment by pavel-odintsov** [comment]
Hello!

david415, I'm working on nDPI integration now and you could try to implement this feature as nDPI module and we could integrate they together to FastNetMon :)

**Comment by david415** [comment]
Yes that sounds good! What code should I look at to gain familiarity with nDPI? I'll browse your source tree and do some searches to try and learn more for now....

**Comment by pavel-odintsov** [comment]
I'm digging in code right now, function ndpi_detection_process_packet will be nice start! :)

**Comment by pavel-odintsov** [comment]
It's not the main FNM purpose. We work on wide-range capture engines and only a few of them offer TCP-level information. I'm going to close this ticket because it's out of scope for FNM. If you need detailed information about such issues please use Bro/Suricata instead.

The main goal of FastNetMon is DDoS/DoS detection.
