### ISSUE TITLE
Grafana integration

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#294]
It's really important! We need good visualization!

**Comment by guilhermefigueiredo** [comment]
I have today integrated fastnetmon + graphite + grafana
![grafana01](https://cloud.githubusercontent.com/assets/13203464/8525691/ca77df46-23d8-11e5-8cad-a3740a8e1970.png)

**Comment by pavel-odintsov** [comment]
Is it real attack?

**Comment by guilhermefigueiredo** [comment]
hell pavel!

some do, some do not. we still have some false positives that we are analyzing. So still we do an analysis of these false positives with nfsen.

**Comment by pavel-odintsov** [comment]
If you use netflow I have bunch of recommendations against false positives, please ask in maillist :)

**Comment by thomas-mangin** [comment]
For netflow we find that long lasting flows ( weeks ) can cause big spikes, so we cross-check with link utilisation to prevent false-positive.

**Comment by pavel-odintsov** [comment]
Thomas, thanks for feedback. Could you offer example of cross check?

**Comment by thomas-mangin** [comment]
We use code base similar to exaddos to use SNMP and pull our transit interface. This is displayed on the NOC's screens, we have threshold which alerts when we see unusually high PPS/Bandwidth. So we can decide to act/ignore alerts coming from NetFlow.

**Comment by pavel-odintsov** [comment]
Thanks! We could try!

But I have another idea behind this:
```bash
# In some cases with NetFlow we could get huge bursts related to aggregated data nature
# We could try to get smoother data with this option, i.e. we will divide counters on collection interval time
netflow_divide_counters_on_interval_length = off
```

Or you could try to use LUA handler and drop "long" data completely.

**Comment by pavel-odintsov** [comment]
We have few community-contributed Grafana Dashboards (please check FastNetMon's mail list for details) and complete integration using our own Dashboards in FastNetMon Advanced: https://fastnetmon.com/fastnetmon-advanced/
