### ISSUE TITLE
Add handler code when attack arrives with another protocol

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#307]
Subject

**Comment by Anito23** [comment]
We are waiting for the decision of this issue. )

**Comment by pavel-odintsov** [comment]
Well, we could add attack protocol to fastnetmon_client. And add checks about attack protocol and call notify script second time when attack protocol changed.

But we should offer configuration option for this case.

**Comment by pavel-odintsov** [comment]
It can be done using shortened ban time
