### ISSUE TITLE
Offer capability to store /etc/fastnetmon.conf in Redis.

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#315]
Subject. It will useful for limits per host group.

**Comment by zenvdeluca** [comment]
Trying to compile with redis support, but its failing even havinng hiredis lib dev installed. any clue ?

root@netmon1.iad1:/usr/src/fastnetmon/src/build# apt-get install -y libhiredis-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libhiredis-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@netmon1.iad1:/usr/src/fastnetmon/src/build# cmake ..
-- Setting build type to Release as none was specified.
-- You are running Linux and we can build PF_RING support
-- We found PF_RING ZC headers and will build PF_RING ZC support
-- checking for one of the modules 'hiredis'
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:350 (message):
  None of the required 'hiredis' found
Call Stack (most recent call first):
  cmake/FindHiredis.cmake:14 (PKG_SEARCH_MODULE)
  CMakeLists.txt:175 (find_package)


-- We could compile Redis support
-- Configuring incomplete, errors occurred!

**Comment by pavel-odintsov** [comment]
Helli, Vicente!

What linux distro version have you used?

On Tuesday, July 21, 2015, Vicente De Luca <notifications@github.com> wrote:

> Trying to compile with redis support, but its failing even havinng hiredis
> lib dev installed. any clue ?
>
> root@netmon1.iad1:/usr/src/fastnetmon/src/build# apt-get install -y
> libhiredis-dev
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libhiredis-dev is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> root@netmon1.iad1:/usr/src/fastnetmon/src/build# cmake ..
> -- Setting build type to Release as none was specified.
> -- You are running Linux and we can build PF_RING support
> -- We found PF_RING ZC headers and will build PF_RING ZC support
> -- checking for one of the modules 'hiredis'
> CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:350
> (message):
> None of the required 'hiredis' found
> Call Stack (most recent call first):
> cmake/FindHiredis.cmake:14 (PKG_SEARCH_MODULE)
> CMakeLists.txt:175 (find_package)
>
> -- We could compile Redis support
> -- Configuring incomplete, errors occurred!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/315#issuecomment-123405495>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by zenvdeluca** [comment]
Ubuntu 12.04.5 LTS \n \l

Thanks for quick replying! best regards

**Comment by pavel-odintsov** [comment]
So old distro :) Could you share output of `dpkg -L libhiredis-dev` ?

Could you try to uncomment this code in CmakeLists:
```bash
# For CentOS 6 please use this code:
add_definitions(-DREDIS)
target_link_libraries (fastnetmon hiredis)
```

Thanks :)

**Comment by zenvdeluca** [comment]
@pavel-odintsov current version are having issues when trying to compile on Ubuntu 12.04 with redis support

You are running Linux and we can build PF_RING support
We found PF_RING ZC headers and will build PF_RING ZC support
CMake Error at CMakeLists.txt:142 (find_package):
  Could not find module FindHiredis.cmake or a configuration file for package
  Hiredis.

  Adjust CMAKE_MODULE_PATH to find FindHiredis.cmake or set Hiredis_DIR to
  the directory containing a CMake configuration file for Hiredis.  The file
  will have one of the following names:

    HiredisConfig.cmake
    hiredis-config.cmake



-- Configuring incomplete, errors occurred!
make: *** [cmake_check_build_system] Error 1

Anything I am missing ?

**Comment by pavel-odintsov** [comment]
Hello :)

Please uncomment only this lines in CmakeLists:
```bash
add_definitions(-DREDIS)
target_link_libraries (fastnetmon hiredis)
```

And run compilation code again ;)

**Comment by pavel-odintsov** [comment]
So I have integrated Redis to FastNetMon completely and you could get it with perl fastnetmon_installer.pl --use-git-master in a few minutes! :)

**Comment by zenvdeluca** [comment]
:+1: :grinning:

**Comment by pavel-odintsov** [comment]
Same ideas as I mentioned in https://github.com/pavel-odintsov/fastnetmon/issues/378 I prefer to keep current text file configuration at this moment. 

Advanced version has MongoDB for such purposes but MongoDB it pretty huge thing for community version.
