### ISSUE TITLE
How to refresh the whitelist ip. 

### ISSUE THREAD

**Issue by gthgame** [pavel-odintsov/fastnetmon#323]
Hello , 

You need add a way where the script auto refresh the whitelisted ips. ( like every 5 mins or so ) .

At this moment for whitelist an ip you need restart all fastnetmon. 

Cordialy,

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately, we could not do it. There are no code for dynamic lists reload. But I could try to build it.... But there are no ETA for this.

There are only one way to do it - full daemon restart.

**Comment by gthgame** [comment]
i'm using : 

ddosok=$(mysql --user=xxxxxxxxxx --host xx.xx.xx.xx --password=xxxxxxxx --database=xxxxxxx -s --execute="select ddos from tblhosting where assignedips = '${1}';")
if [ "$2" == "incoming" ] && [ "$ddosok" == 1 ]; then
    exit 0
fi

For doing the whitelist , but it seems it fails many times ... what's wrong in my code ? I think when ddos come it can't connect anymore the db wich is on diferent host ... and so fail to execute the code properly . 

Something is wrong in my code ? 

Do you know other way ?

**Comment by pavel-odintsov** [comment]
It's not a good idea. Because after one call FastNetMon marks this IP as banned and will not execute ban until it will be unbanned. You could specify very short ban time if you want it.

**Comment by gthgame** [comment]
i see ... thank you

**Comment by pavel-odintsov** [comment]
Could you store whitelist IP's in redis? I have integration for Redis and could offer option for store subnet lists inside it.

Database or php script is very slow and could broke toolkit logic.

**Comment by pavel-odintsov** [comment]
Online reconfiguration needs an extremely large amount of effort. I do not have any plans to implement it in near future.
