### ISSUE TITLE
Switch to serialization code for attack details instead silly std::cout

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#330]
Subject! I like this idea :)

**Comment by denji** [comment]
- [gRPC](http://www.grpc.io/) ( https://github.com/grpc/grpc )
- [protobuffer - Protocol Buffers](https://github.com/google/protobuf/) ( https://developers.google.com/protocol-buffers/ )
- [FlatBuffers](http://google.github.io/flatbuffers/) ( https://github.com/google/flatbuffers )
- [Cap'n Proto](https://capnproto.org/) ( https://github.com/sandstorm-io/capnproto )
 - [Cap'n Proto, FlatBuffers, and SBE](https://capnproto.org/news/2014-06-17-capnproto-flatbuffers-sbe.html)

![Feature Matrix](https://cloud.githubusercontent.com/assets/3759759/7901831/3e0b71ac-07a5-11e5-946b-38187aefff41.png)

**Comment by pavel-odintsov** [comment]
denji, how this article is related with serialization? We haven't anybody who use protobufs or smth else in DC environment and should use more standard tools/protocols for it.

**Comment by pavel-odintsov** [comment]
std::cout do this job great.
