### ISSUE TITLE
Integrate Tesseara as dashboard

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#334]
Because Grafana is very very very big :)  http://urbanairship.github.io/tessera/

**Comment by Phinitris** [comment]
What do you mean as dashboard?
You want to directly install Tessera + Graphite as a dependency when installing FastNetMon and configure it to directly use FastNetMon as data source?

Or just recommend it as a nice application for presenting FastNetMon data from Graphite?

**Comment by pavel-odintsov** [comment]
Just recommend it now :)

**Comment by Phinitris** [comment]
Alright! I still prefer Grafana ;)

**Comment by Phinitris** [comment]
I mean, look at this. Can't imagine anything better ;) Also Displays DDoS Attacks with Redlines(Arrows)
![zyyfgbp](https://cloud.githubusercontent.com/assets/10375269/8763716/8e6e424c-2dab-11e5-94f8-34df20f20e7e.png)

**Comment by pavel-odintsov** [comment]
But we still have troubles with top 10 talkers in Grafana :(

**Comment by zenvdeluca** [comment]
@Phinitris would you mind helping me setup a similar dashboard ?

**Comment by Phinitris** [comment]
@zenvdeluca sure. Just add me on Skype(henne.s)

**Comment by Phinitris** [comment]
@pavel-odintsov
Does that make any difference? Tessera is also using the Graphite API(wsgi Port 8080). That's the reason why we can't calculate top 10 talkers. Because the Graphite Process itself is running at 100% CPU, not Grafana.

**Comment by zenvdeluca** [comment]
anyone tried to replace graphite by influxdb,
so fastnetmon => influxdb => grafana ?

**Comment by zenvdeluca** [comment]
@pavel-odintsov saw the last commit about influxdb.. you're a monster Pavel :) !!!

**Comment by pavel-odintsov** [comment]
Thanks :) InxluxDB is compatible with Graphite protocol and we have got
this integration with really small fee :)

On Sunday, August 9, 2015, Vicente De Luca <notifications@github.com> wrote:

> @pavel-odintsov <https://github.com/pavel-odintsov> saw the last commit
> about influxdb.. you're a monster Pavel :) !!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/334#issuecomment-129170553>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Would recommend Grafana! :) It works GREAT!
