### ISSUE TITLE
Call notify script in case if internal attack too

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#341]
Subject!

> hi pavel,
> yes, data center for cloud service like IAAS,  this case may happened.
> what is the trade off ?

**Comment by Phinitris** [comment]
+1

**Comment by 8ara8a** [comment]
+1

**Comment by pavel-odintsov** [comment]
It's enough complex task because we haven't any option do count traffic from external networks and from internal networks for same host. Current counter architecture is a little silly and we could not implement this.

**Comment by pavel-odintsov** [comment]
It's impossible with current design and needs so much work. If you are interested in such things please reopen this ticket.
