### ISSUE TITLE
src/sflow_plugin/sflow_collector.cpp readFlowSample_header() may read beyond buffer

### ISSUE THREAD

**Issue by green525** [pavel-odintsov/fastnetmon#352]
The function readFlowSample_header() executes skipBytes(sample, sample->headerLen); without checking the result. In case of an invalid headerLen or a too short datagram, the further decode_\* functions may read beyond the end of the buffer.

[In the original sflowtool code base skipBytes ends the program flow, so this is not an upstream issue ;)]

**Comment by pavel-odintsov** [comment]
We've migrated away from this code and completely reworked sflow plugin: https://github.com/pavel-odintsov/fastnetmon/pull/844
