### ISSUE TITLE
Introduce top10 flooders for one attack

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#37]
Subject)

**Comment by s4m4n** [comment]
What about "Top flooders" and "Top Flooded" in specific period? 
ie Top Flooded IPs in past week. with summary of each attack

**Comment by pavel-odintsov** [comment]
This ticket related to sorting of attack sources in connection tracking mode by used bandwidth and pps. This approach could simplify attack mitigation in case of non spoofed attacks.

**Comment by pavel-odintsov** [comment]
Well, I do not have any reasons/benefits from this idea.
