### ISSUE TITLE
Could you insert notify_script_path option for each host_group?

### ISSUE THREAD

**Issue by kartoffelbaer** [pavel-odintsov/fastnetmon#377]
hello,

it would be very cool to have the option to set different notify_script_path for each hostgroup :) :+1: 
could you may insert this feature?

greetings,
kartoffelbaer

**Comment by henry-spanka** [comment]
Well, we are getting more and more variables.
Maybe it would make sense to use YAML format for the config file.

Will read some docs and see if it will be an improvement for fastnetmon. This way, we can implement any config options we want without having a really weird config file.

**Comment by pavel-odintsov** [comment]
Nice option. I could implement it because I have already same idea for custom actions for each host group. 

But I do not like YAML. I prefer something like json but it's not human-friendly :) So we could discuss it in another issue https://github.com/FastVPSEestiOu/fastnetmon/issues/378

**Comment by zenvdeluca** [comment]
or we can modify the parameters we pass to notify script, and treat each hostgroup case at the script level. I like the idea to offload fastnetmon as much as possible, keep the focus on detection, and leave the other tasks to "scripts".

This should make Pavel's like easier, having him focused on supporting and improving the detection algorithms / etc, and allow the community to contribute in many different languages. 
We already have notify scripts in bash and python, we can write up things in the way we want, without need to keep Pavel busy adding more stuff to fastnetmon core unrelated to traffic processing + anomaly detection.

**Comment by pavel-odintsov** [comment]
We added this option in JSON based notify script for advanced edition: https://fastnetmon.com/fastnetmon-json-formats/

**Comment by pavel-odintsov** [comment]
I think proper solution is this: https://github.com/pavel-odintsov/fastnetmon/issues/731
