### ISSUE TITLE
Add ability to process same IP from different vlans completely separately

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#379]
Hello!

This issues mentioned by linyutsung6502p@gmail.com in FastNetMon maillist.

**Comment by henry-spanka** [comment]
+1
But would be only possible with a dedicated fastnetmon server between core router and border router.

sFlow/Netflow protocols do not include VLAN information from what I know.

**Comment by pavel-odintsov** [comment]
I do not like this idea. Sorry about it. If you are interested in such things please feel free to reopen ticket and mention your interest.
