### ISSUE TITLE
Strange text in console mode about IPv6

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#380]
dennis@ri1a: fastnetmon$ sudo ./fastnetmon
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6
IPv6

**Comment by wagnst** [comment]
is ipv6 fully supported? when i enter ipv6 CIDR's i see in log
[ERROR] Can't parse line from subnet list: '2a01:....'

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately we haven't support for IPv6. It's correct message.

**Comment by craig** [comment]
Hi Pavel, when do you plan to implement ipv6?

**Comment by pavel-odintsov** [comment]
Unfortunately no plans about it. So much changes in counters / announces.

**Comment by craig** [comment]
:'-(

**Comment by pavel-odintsov** [comment]
Really sorry about it :(

**Comment by craig** [comment]
Hm. ipv6 adaption is kind of slow, but sitll. Do you think you mind find time until the end of 2016 for this?  Maybe someone wants to do it as a project, GSOC?

**Comment by pavel-odintsov** [comment]
IPv6 requires a lot of design / redesign work. I prefer to keep this task until I build new architecture.

**Comment by craig** [comment]
Ah, I see. Thank you for explaining! :)

**Comment by pavel-odintsov** [comment]
welcome :)

**Comment by pavel-odintsov** [comment]
Original issue was fixed.
