### ISSUE TITLE
We haven't netsta on CentOS 7 servers

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#384]
sh: netstat: команда не найдена

**Comment by henry-spanka** [comment]
We can use the command that replaces netstat
```bash
ss
```

**Comment by pavel-odintsov** [comment]
Hi!

I'm using it for interfaces list. Could we do same with ss? So i'm thinking
we should use ip tool istead.

On Sunday, August 23, 2015, Henry Spanka <notifications@github.com> wrote:

> We can use the command that replaces netstat
>
> ss
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/384#issuecomment-133760571>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by henry-spanka** [comment]
What about using the following:

```bash
ip -o addr show | awk '/inet/ {print $2}' | uniq
```

**Comment by pavel-odintsov** [comment]
Nice idea! Will use it! :)

On Sun, Aug 23, 2015 at 2:23 AM, Henry Spanka <notifications@github.com>
wrote:

> What about using the following:
>
> ip -o addr show | awk '/inet/ {print $2}' | uniq
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/384#issuecomment-133764049>
> .
>



-- 
Sincerely yours, Pavel Odintsov
