### ISSUE TITLE
GoBGP support

### ISSUE THREAD

**Issue by waszi** [pavel-odintsov/fastnetmon#389]
Please consider adding gobgp support. It has flowspec support and it in my opinion it is easier to integrate with other tools (it supports gRPC). GoBGP consists two golang binaries (gobgp - cli and gobgpd - daemon).

in example adding flowspec route:
gobgp global rib -a ipv4-flowspec add match destination 10.0.0.0/32 source 1.2.3.4/32 then discard

With this it would be also very interesting feature to add blocking top sources (above filter threshold). I am currently using sflow-rt + gobgp to do this but sflow is rather inacurrate with low bandwidth attacks.

https://github.com/osrg/gobgp

**Comment by pavel-odintsov** [comment]
Hello!

Awesome! I never heard about this project but it will solve my issues :) And Go very portable for bundling with my toolkit. 

Gobgp format is very similar to ExaBGP and I could integrate it enough fast because my Flow Spec code is clean and  well tested https://github.com/FastVPSEestiOu/fastnetmon/blob/master/src/bgp_flow_spec.h :) 

I have created ticket to GoBGP and will try it.

**Comment by pavel-odintsov** [comment]
waszi, I could implement sources blocking with BGP.

But we need some way to check "how much bytes we have rejected with this announce". Do you know any way how we could do it?

**Comment by waszi** [comment]
It depends how accurate and fast counters we require. I would use 
py-junos-eznc script permanentnly connected to netconf/ssh. Script will be polling every few seconds "show firewall" in xml format and store results in redis/influxdb. SNMP with large number of ACL rules can be slow and if I remember correctly flowspec counters are not exported through snmp.

I am currently using py-junos-eznc to poll interface stats (snmp is so slow if you like 10-15 seconds polling intervals :)

**Comment by pavel-odintsov** [comment]
Hello!

Could you share your evaluation of speed for SNMP? How much ACL do you have? I'm working now on SNMP integration with Juniper but if you have negative experience I will move to pyez.

We need download all counters for each filtering rule each 30-60 seconds. Because if attack changes really fast we need some way to remove useless filter rules.

So will be fine if you share experience about "how much filtering rules could process Juniper" . I could not find it in official documents.

You could answer directly with email pavel.odintsov@gmail.com :)

Thanks for feedback!

**Comment by waszi** [comment]
I have checked snmp on my MX and it do not contain flowspec ACLs only static ones.
OID: .1.3.6.1.4.1.2636.3.5.2.1

http://juniper.clico.pl/pomoc/juniper-days/2009/emilMX_Juniper_Day.pdf   - 256k ACLs on MX240 and higher.

Typical target: OpenVZ VPS
Most of attacks we are experiencing has no more than 30 high bandwidth sources. If we filter this high bandwidth sources rest is easily handled by vps hardware node.

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for feedback! Do you have any references how I could use bgp
announces for juniper firewall?



On Saturday, August 29, 2015, waszi <notifications@github.com> wrote:

> I have checked snmp on my MX and it do not contain flowspec ACLs only
> static ones.
> OID: .1.3.6.1.4.1.2636.3.5.2.1
>
> http://juniper.clico.pl/pomoc/juniper-days/2009/emilMX_Juniper_Day.pdf -
> 256k ACLs on MX240 and higher.
>
> Typical target: OpenVZ VPS
> Most of attacks we are experiencing has no more than 30 high bandwidth
> sources. If we filter this high bandwidth sources rest is easily handled by
> vps hardware node.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FastVPSEestiOu/fastnetmon/issues/389#issuecomment-135967982>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
I have started work https://github.com/osrg/gobgp/issues/285 https://github.com/pavel-odintsov/gobgp_api_cpp_client.

**Comment by pavel-odintsov** [comment]
I have implemented GoBGP support. Please check this: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/GOBGP.md

**Comment by pavel-odintsov** [comment]
But it will work only with IPv4 unicast. Flow Spec integration need enough big amount of actions and scheduled on next months.

**Comment by pavel-odintsov** [comment]
I think that basic integration was implemented but it requires few pertty complicated things:

1. C++ 11 or more recent compiler
2. Bunch of gRPC staff

So at this moment I do not have plans to improve integration. ExaBGP is recommended way to implement BGP integration now.

**Comment by pavel-odintsov** [comment]
In FastNetMon Advanced we use GoBGP for all kinds of BGP integration. It works fine but compilation process is a kind of nightmare.

**Comment by pavel-odintsov** [comment]
If you're curios we're working on GoBGP migration for FastNetMon.

**Comment by pavel-odintsov** [comment]
Hello!

I think since https://github.com/pavel-odintsov/fastnetmon/commit/d398b57c4ff675e8a7806636dfe57e192091346b we can declare GoBGP support :)
