### ISSUE TITLE
Whitelist external IPs

### ISSUE THREAD

**Issue by SynSeer** [pavel-odintsov/fastnetmon#394]
Need to be able to whitelist heavily used sites that are external, such as Apple.  If networks_list includes 10.10.10.0/24, I can add 10.10.10.5/32 to networks_whitelist to ignore traffic to/from that IP.  However, I have added 17.253.0.0/16 to network_whitelist has still receive reports that high volume traffic is coming from that IP range.

**Comment by pavel-odintsov** [comment]
Hello!

It's good idea but we need some architecture changes for it. So LPM code need optimization too.

**Comment by pavel-odintsov** [comment]
Nice idea. We should implement it ASAP.

**Comment by pavel-odintsov** [comment]
So we also could implement whitelist for internal IPs. It will be very useful for internal backup servers / storages.

**Comment by pavel-odintsov** [comment]
Duplicate of https://github.com/pavel-odintsov/fastnetmon/issues/564
