### ISSUE TITLE
Add option to account internal flows

### ISSUE THREAD

**Issue by henry-spanka** [pavel-odintsov/fastnetmon#399]
It would be nice, if we could enable accounting of internal flows via a configurable option.

E.g. traffic between two networks both defined in the /etc/networks_list

**Comment by pavel-odintsov** [comment]
Hello!

It's possible but need separate counters... But now we can't use any counters because they are not so flexible and allocated statically. With ipv6, vlan support we could add this. But now it's really hard to implement.

**Comment by pavel-odintsov** [comment]
Sorry, I do not think that we need this. It does not match to FastNetMon's idea to detect incoming/outgoing DDoS. As traffic visibility I can suggest checking advanced edition.
