### ISSUE TITLE
fastnetmon_client zero stats each 5 seconds

### ISSUE THREAD

**Issue by robertoberto** [pavel-odintsov/fastnetmon#428]
I updated fastnetmon today and we're hitting a bug
With docker image it doesn't happen

1) using juniper mx and ipfix
2) junos config

flow-monitoring {
    version-ipfix {
        template ipv4 {
            flow-active-timeout 10;
            flow-inactive-timeout 10;
            template-refresh-rate {
                packets 1000;
                seconds 10;
            }
            option-refresh-rate {
                packets 1000;
                seconds 10;
            }
            ipv4-template;
        }
    }
}

3) fastnetmon config
netflow_sampling_ratio = 10
average_calculation_time = 30
average_calculation_time_for_subnets = 30
netflow_divide_counters_on_interval_length = on

**Comment by pavel-odintsov** [comment]
Hello!

Please try to change check_period from 3 seconds to 13 seconds. This could solve your issue.

**Comment by robertoberto** [comment]
not solve it

**Comment by mail3dexter** [comment]
I am also facing some issues with stats. It is not getting average out properly.
Below is the configuration i am using on my MX80 test routers:
mayur_p@r101-jpr-rtr1-ntw.adc-tx.as40034.net> show configuration | display set | match flow
set forwarding-options sampling family inet output flow-inactive-timeout 15
set forwarding-options sampling family inet output flow-active-timeout 60
set forwarding-options sampling family inet output flow-server 172.16.211.35 port 2055
set forwarding-options sampling family inet output flow-server 172.16.211.35 source-address 172.16.211.6
set forwarding-options sampling family inet output flow-server 172.16.211.35 version 5

This is the config file :
http://pastebin.com/raw.php?i=WErhzmwL

Please let me know if something is wrong.

I see proper values every 5 seconds and rest of the time it goes down decreasing almost nearto 0 at 4th second and again at 5th values are proper.

**Comment by pavel-odintsov** [comment]
Hello!

Please enlarge "average_calculation_time = 5" to 61 (maximum from active and inactive timeout + 1 second)

**Comment by mail3dexter** [comment]
average_calculation_time_for_subnets should also be 61?

**Comment by mail3dexter** [comment]
I changed "average_calculation_time = 5" to 61 as you said, but it is now not detecting attacks.

**Comment by pavel-odintsov** [comment]
Unfortunately this issue could be related with project design and could not be avoided without huge code changes...

**Comment by mcflyspb** [comment]
service iptables stop ?

**Comment by pavel-odintsov** [comment]
This ticket does not provide enough details. Probably, it was related to active/inactive time violation which happens sometimes with JunOS. 

I would recommend this guide for detailed investigation of active/inactive timeout in flows: https://fastnetmon.com/2017/01/20/netflow-flows-duration/
