### ISSUE TITLE
Cannot compile with SnabbSwitch enabled

### ISSUE THREAD

**Issue by Murk1108** [pavel-odintsov/fastnetmon#440]
Hello,

I am having trouble compiling FastNetMon with the snabbswitch plugin. I made the following change to CMakeLists.txt

```
+#set(ENABLE_LUA_SUPPORT yes)
```

as the same file states that this is required. I then run

```
# cmake .. -DENABLE_SNABBSWITCH_SUPPORT=ON
 -- C++ compilation flags: -O3 -DNDEBUG
-- Setting build type to Release as none was specified.
-- You are running Linux and we can build PF_RING support
-- We found PF_RING ZC headers and will build PF_RING ZC support
-- We have enabled PF_RING's hardware filtering option
-- You are running Linux with enough recent kernel and we can build AF_PACKET support
-- We will enable nDPI support
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   thread
--   regex
--   program_options
--   system
-- We found hiredis library and will build Redis support /opt/libhiredis_0_13/include/opt/libhiredis_0_13/lib/libhiredis.so
CMake Warning at CMakeLists.txt:430 (message):
  We can't find Mongo C library


-- We have found log4cpp and will build project
-- We have found json-c library correctly: /opt/json-c-0.12/lib/libjson-c.so
-- Configuring done
-- Generating done
-- Build files have been written to: /root/fastnetmon/src/build
```

Finally, a make procudes the following error:

```
[...]
/usr/bin/ld: cannot find -lsnabb
collect2: error: ld returned 1 exit status
CMakeFiles/fastnetmon.dir/build.make:116: recipe for target 'fastnetmon' failed
make[2]: *** [fastnetmon] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/fastnetmon.dir/all' failed
make[1]: *** [CMakeFiles/fastnetmon.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
    make: *** [all] Error 2
```

SnabbSwitch has been downloaded (via git clone) to /usr/local/src/snabbswitch and compiled and also seems to work fine:

```
# /usr/src/snabbswitch/src/snabb
Usage: /usr/src/snabbswitch/src/snabb <program> ...

This snabb executable has the following programs built in:
  example_replay
  example_spray
  firehose
  gc
  packetblaster
  snabbmark
  snabbnfv
  snsh
  top

For detailed usage of any program run:
  snabb <program> --help

If you rename (or copy or symlink) this executable with one of
the names above then that program will be chosen automatically.
```

This is on a Fedora 22 host in case it matters. I feel like I am missing a step here, but I cannot figure out which one it is and there does not seem to be no specific documentation on how to enable this feature - I am willing to provide a PR which adds this documentation once I get it running.

Note that the FastNetMon binary I compiled without SnabbSwitch support is working without any trouble. I am currently using netmap mode, which works but I would like to compare performance with SnabbSwitch for our workload. Any help would be appreciated.

**Comment by pavel-odintsov** [comment]
Hello!

You could run install script with this options:
```bash
perl fastnetmon_install.pl --use-git-master
```

And it will build mongoc for you. Than you need to change configuration options and run cmake .. / make again.

Performance of netmap and snabbswitch are really similar but netmap support is really mature and stable.
