### ISSUE TITLE
Feature request:  swap incoming/outgoing labels

### ISSUE THREAD

**Issue by akhepcat** [pavel-odintsov/fastnetmon#443]
Depending on the interfaces monitored via netflow,  incoming and outgoing may reversed.

ideas:

  global option to "flip"  incoming/outgoing   ( would require separate FNM instances for different groups)

  add an optional "reverse" flag to each CIDR block in the /etc/networks_list 
     this could be done via comma-delimited format, any fields past the CIDR would be optional.

**Comment by pavel-odintsov** [comment]
Hello!

We do not need this option because we do not read direction from netflow :) We detect it manually with networks_list with long prefix matching.

**Comment by akhepcat** [comment]
interesting.  
I look at the attack report, and then look at my network interface, and the data is reversed in the attack info.

**Comment by pavel-odintsov** [comment]
Very interesting. Could you share whole report?

**Comment by akhepcat** [comment]
I left it alone too long, and we've started a backup cycle through that specific interface.  I should have screen-capped when I took the report.

Let me wait until things are past this, and i'll see if i can get another that shows up.

**Comment by pavel-odintsov** [comment]
Nice! Waiting for new bug reports :)
