### ISSUE TITLE
Feature request:  separate incoming/outgoing pps and mbps rates

### ISSUE THREAD

**Issue by akhepcat** [pavel-odintsov/fastnetmon#445]
add an optional "(pps|mbps)_(in|out)=####" flag to each CIDR block in the /etc/networks_list 
     this could be done via comma-delimited format, any fields past the CIDR would be optional.
     this would be compatible with the "reverse"  flag as well that I also requested.

**Comment by pavel-odintsov** [comment]
Hello!

You could check this ticket https://github.com/pavel-odintsov/fastnetmon/issues/285 about same idea :)

**Comment by akhepcat** [comment]
Cool!  any limit on the number of groups?  

(as a side note, a lot of the old links to issues are referencing the old project name, which might get confusing down the line...  i.e., https://github.com/FastVPSEestiOu/fastnetmon/issues/407  )

**Comment by pavel-odintsov** [comment]
No limits on group number :) But you need full toolkit restart if you remove/add new group. I will fix links in near future. Thanks for report!

**Comment by akhepcat** [comment]
Thank you!

**Comment by pavel-odintsov** [comment]
Welcome :)

**Comment by pavel-odintsov** [comment]
Duplicate for: https://github.com/pavel-odintsov/fastnetmon/issues/285
