### ISSUE TITLE
Add direct support for SMTP protocol

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#446]
Hello!

It could be useful when server itself have't MTA. There are some awesome services with guarantee mail delivery: https://www.mandrill.com

**Comment by anacondaqq** [comment]
yes, but they sending with header the real server IP.
You can check it by itself. Your IP will be showed to everyone with email headgears.
This is common trick with game servers, why admins think they can hide their IP, but their services show their real ip by mail-server.

How to avoid this: two servers & relays with postfix, where in headgears we will have internal IP, and not public.

**Comment by craig** [comment]
Pavel, I'm not sure it's too useful to implement this. People are able to set up something as easy as postfix already or call mandrill from the triggered-scripts when DDoS occurs. Using them is enough IMHO? Or maybe I'm getting wrong what you're trying to do here?

**Comment by pavel-odintsov** [comment]
Yep IP server sharing is not a good idea...  Yes we could implement this with notify scripts. So somebody could contribute custom notify script for this case! :)

**Comment by pavel-odintsov** [comment]
I think this option is out of scope for FNM.
