### ISSUE TITLE
Introduce per subnet thresholds

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#448]
Hello!

Some users asked about this feature and we could offer it without so much code changes.

We need following features:
1) Ability to implement pps/mbps threshold's for subnets mentioned in networks_list
2) Ability to call ExaBGP / script of smth else in case of exceeded thresholds

But we need separate place for this configuration type...

**Comment by pubyun** [comment]
need this feature, thanks

**Comment by pavel-odintsov** [comment]
Duplicate of https://github.com/pavel-odintsov/fastnetmon/issues/508
