### ISSUE TITLE
Does not install on CentOS 7.1 using default kernel

### ISSUE THREAD

**Issue by ghost** [pavel-odintsov/fastnetmon#449]
The CentOS 7 based RPM requires a library the ntop RPM does not provide or has changed. The result is fastnetmon is unable to install.

After trying to build from source, the install instructions are also out of date hard coding PF_RING 6.0.3 in place when 6.1.1 is required via RPMs. This makes no sense? There is also no mention of nDPI installing in the manual install instructions yet it continues to give error after error after error such as:

CMake Error at CMakeLists.txt:198 (message):
  Could not find nDPI library

If we fix one, another pops up, if we fix that, another pops up, it seems that this hasn't been updated/tested at all.

**Comment by LinHub** [comment]
luajit just after it. None of this is listed in the instructions, RPM installs aren't seen, and different versions are hard coded. It is definitely out of date/broken.

**Comment by pavel-odintsov** [comment]
Hello

Unfortunately rpm package is broken. Pleaseuse automatic installer.
 6.0.3is a current version of pfring library.

On Thursday, 12 November 2015, LinHub <notifications@github.com> wrote:

> luajit just after it. None of this is listed in the instructions, RPM
> installs aren't seen, and different versions are hard coded. It is
> definitely out of date/broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/449#issuecomment-155939354>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by robdn** [comment]
Misleading subject. The installer works well on CentOS 7.1 with default kernel and netmap.

**Comment by pavel-odintsov** [comment]
Yep it works perfect with automatic installer but works bad with rpm packaged version (because it's outdated).
