### ISSUE TITLE
Не собирается под Centos 6

### ISSUE THREAD

**Issue by mdpuma** [pavel-odintsov/fastnetmon#454]
Здравствуйте,

Пытаюсь установить последнюю версию, никак не получается.

Останавливается на
Can't build fastnetmon! at fastnetmon_install.pl line 1483, <STDIN> line 1.

До этого все модули собираются без ошибок.

[fastnetmon_install.log.txt](https://github.com/pavel-odintsov/fastnetmon/files/39008/fastnetmon_install.log.txt)

**Comment by mdpuma** [comment]
[CMakeOutput.log.txt](https://github.com/pavel-odintsov/fastnetmon/files/39013/CMakeOutput.log.txt)

**Comment by pavel-odintsov** [comment]
cd /tmp/fastnetmon.build****/src/build и запустите make и пожалуйста, расшарьте ошибку.

**Comment by mdpuma** [comment]
/tmp/fastnetmon.build.dir.ibbnqHRQpj/fastnetmon/src/build # make
make: *** No targets specified and no makefile found.  Stop.

**Comment by pavel-odintsov** [comment]
Тогда: cmake ..

**Comment by mdpuma** [comment]
host13 /tmp/fastnetmon.build.dir.ibbnqHRQpj/fastnetmon/src/build # cmake ..
-- C++ compilation flags: -O3 -DNDEBUG
-- Setting build type to Release as none was specified.
-- You are running old Linux kernel and we can't build AF_PACKET support
-- We will enable nDPI support
CMake Error at CMakeLists.txt:198 (message):
  Could not find nDPI library


-- Configuring incomplete, errors occurred!
See also "/tmp/fastnetmon.build.dir.ibbnqHRQpj/fastnetmon/src/build/CMakeFiles/CMakeOutput.log".
host13 /tmp/fastnetmon.build.dir.ibbnqHRQpj/fastnetmon/src/build # echo $?
1

**Comment by pavel-odintsov** [comment]
Ну вот, по какой-то причине не собрался ndpi:

```bash

We are calling command: git clone https://github.com/pavel-odintsov/nDPI.git

Initialized empty Git repository in /tmp/fastnetmon.build.dir.lKPsUTLIlW/nDPI/.git/
Command finished with code 0

We are calling command: ./autogen.sh
Command finished with code 32256
```

Можете попробовать руками его собрать? Либо autogen, либо aclocal не хватает.

**Comment by mdpuma** [comment]
Проблема думаю в том что папка /tmp смонтирована с флагом noexec. Попробую переписать скрипт чтобы он собирался в другую папку.

**Comment by pavel-odintsov** [comment]
Да, это многое объясняет :) Если что - создайте другой тикет,

**Comment by mdpuma** [comment]
Да, это решило проблему, помню до этого стояла версия которая не собиралась в папке /tmp, поэтому и так получилось.

Благодарю за выделенное время моей проблеме :)

**Comment by pavel-odintsov** [comment]
Рад помочь :)
