### ISSUE TITLE
GeoIP Handling

### ISSUE THREAD

**Issue by chron0** [pavel-odintsov/fastnetmon#457]
I've been trying to get fastnetmon to work with MaxMind's GeoIPCity.dat database, but it seems, it only works with GeoIPCity-lite. Is there a trick to get it to use GeoIPCity.dat?

**Comment by pavel-odintsov** [comment]
Hello!

I'm not sure is this code working :) I have dropped support for GeoIP some time ago..

**Comment by chron0** [comment]
OMG, sorry pavel, this ticket was actually meant for https://github.com/elastic/packetbeat - I must have confused my open github tabs and current projects, I guess I starred fastnetmon last (working beautifully here) - so thanks for releasing the code and never mind this "issue" :)

**Comment by pavel-odintsov** [comment]
Haha :) Not a problem :)
