### ISSUE TITLE
Multiple feature requests (Russian, many)

### ISSUE THREAD

**Issue by cmhungry** [pavel-odintsov/fastnetmon#459]
1. несколько пороговых значений на срабатывание  типа, 100кппс, 200кппс, 500кппс, 1мппс, 300 мбит, 1 гбит, 5 гбит
2. жестче смотреть за баном по скорости. А то ни разу не видел по нему срабатывания, хотя в клиенте вот частенько висит клиент по несколько минут с явным превышением лимита мбпс.
3. в бан-скрипт передавать информацию, за что баним - ппс или бпс. Сейчас только ип/ппс/направление
4. в бан-скрипт передавать информацию о текущем bps/pps, если бан
5. в лог писать ип-адрес "кого баним", сейчас "2015-11-13 15:20:57,600 [INFO] We run execute_ip_ban code with following params  in_pps: 8897 out_pps: 102021 in_bps: 650308 out_bps: 6974983 and we decide it's outgoing attack", а ип-адрес передается в другой строчке лога. Не грепается в итоге это. Ну и тип атаки неплохо бы писать сразу в лог в эту же строчку.
6. непонятная строчка в логе "2015-11-13 16:58:31,949 [INFO] We detected this attack by pps limit". Какая атака, зачем она, куда и как... 
7. название лог-файла не задается в конфиге, и когда несколько инстансов, их не разделить по конфигам. И они вдобавок не пишут "а кто это написал в лог"
8. запись в логе Attack with direction: outgoing IP: 95.213.143.180 Power: 46811,  а если превышение по mbps?
11. если неизвестный протокол в деталях атаки, то писать не unknown, а номер протокола
```
2015-11-13 18:19:45.247525 95.213.149.107:0 > 186.2.164.194:0 protocol: unknown frag: 0  packets: 1 size: 94 bytes ttl: 0 sample ratio: 4096  
 2015-11-13 18:19:45.283004 186.2.164.194:0 > 95.213.149.107:0 protocol: unknown frag: 0  packets: 1 size: 102 bytes ttl: 0 sample ratio: 4096  
```
14. разбор QinQ sFlow
17. а что с ipv6?
18. peak attack power выводить в заголовок при посылке details
19. тип атаки (udp, syn flood, icmp, tcp/unknown) выводить в заголовке. Можно при посылке details
20. задавать разные пороги на incoming / outgoing трафик
21. как вариант - передавать все, включая сообщения, не в stdout, а в некий HTTP REST API снаружи. А уже там пусть логика обработки. Но - нужно тогда передавать по ступенькам срабатывания порогов, 100кппс - 200 - 300 - 500 - 1мппс - 2мппс - 5мппс - дохера и по трафику - 100 мбит, 200 мбит, 500 мбит, 1 гбит, 5 гбит, 10 гбит, дохера

**Comment by pavel-odintsov** [comment]
Hello!

1. Good idea
2. Already works, fixed few versions ago
3..19 Need some time to think about these features. Part of them was implemented in Advanced version/waiting for implementation in community.

**Comment by pavel-odintsov** [comment]
Most of the things here are implemented in Community edition like IPv6, some features were implemented in Advanced edition like this: https://fastnetmon.com/docs-fnm-advanced/example-web-hook-receiver-for-fastnetmon-advanced/ 

QnQ was removed but may be resurrected with new versions of parsers.
