### ISSUE TITLE
Детали атаки

### ISSUE THREAD

**Issue by mdpuma** [pavel-odintsov/fastnetmon#460]
Предлагаю проверять тип атаки на основе пакетов которые пришли в течений 1 секунды. Сейчас предпологаю, проверяются указанные n пакетов (по умолчанию 500), на оснований которого делается вердикт, атака icmp_flood/udp_flood.

Думаем о таком из за вероятности, что при udp/tcp флуде, может просочиться больше icmp пакетов, в эти самые 500 пакетов.

**Comment by pavel-odintsov** [comment]
Привет!

А это так и работает. Просто счетчики по tcp/udp/icmp были сломаны, вчера в коммитах https://github.com/pavel-odintsov/fastnetmon/commit/24cc84e5ab33443bfa2bbfb62e2ddef81b2d55e0
https://github.com/pavel-odintsov/fastnetmon/commit/0f2be7279cc47473dab05f4f02daca60576d19e7 починил.

И теперь решение о типе / протоколе атаки принимается на основании ВСЕГО трафика. Так было и ранее (выцепленные 500 пакетов для этого не использовались - только для более точной митигации силами флоу спека), но просто входные данные были кривые...
