### ISSUE TITLE
Custom logic to detect DDoS attack implemented with lua script

### ISSUE THREAD

**Issue by mdpuma** [pavel-odintsov/fastnetmon#461]
Возникла такая идея, в связи с осложнением самой программы.

Почему не сделать обработку логики, условий, при превышений pps/bps/flow на lua скрипте.

Так можно будет упростить лимиты на ип, подсеть, и всё что выходит за рамки просто pps/bps/flow на сетевой порт.

**Comment by pavel-odintsov** [comment]
Дергать рантайм луа на каждый айпи при поиске того, что выел лимиты по скорости - будет очень тяжелая операция. Потому что ее нельзя делать пакетно, я сразу и обсчитываю скорость и проверяю - не превышает ли она предел.

**Comment by mdpuma** [comment]
Можно выполнять с определённой частотой снятие метрик текущих и переваривание их скриптом lua.

**Comment by pavel-odintsov** [comment]
Идея хорошая, но во многом надо быть оооочень аккуратными с производительностью. Этот код првоерки требуется ли блокировка узла или нет выполняется для каждого узла в сети и если сеть класса /8, это будет серьезный оверхед. Lua, конечно, быстра, но у всего есть свои пределы :)

**Comment by pavel-odintsov** [comment]
I'm sorry but we've decided to deprecate scripting support: https://github.com/pavel-odintsov/fastnetmon/issues/852

**Comment by pavel-odintsov** [comment]
We've decided to discontinue support for lua due to complexity of maintenance and extremely low demand.
