### ISSUE TITLE
Странное поведение

### ISSUE THREAD

**Issue by cmhungry** [pavel-odintsov/fastnetmon#462]
В субботу имели очень большое количество срабатываний, возможно, ложное. Потом все успокоилось - как я понимаю, из-за двух вставших/зависших экземпляров.

![image](https://cloud.githubusercontent.com/assets/16045329/11465421/91d04bb2-9749-11e5-9e80-91cecef4b95e.png)

Машина при этом перестала отвечать на SSH снаружи, да и в существующей консоли отвечала неадекватно
Can't make pipe, can't allocate memory и т.п.

**Comment by pavel-odintsov** [comment]
У тебя гигабайт памяти суммарно? :) Это даже не минимально необъодимое, для твоего размера сетей - это чисто буфер под счетчики. Добивай до 4х гб хотя бы. Траблы с аллокацией памяти к такому и приводят.

**Comment by cmhungry** [comment]
ok, спасибо
пошёл добавлять памяти виртуалке

**Comment by pavel-odintsov** [comment]
I think original issue was related to memory exhaustion.
