### ISSUE TITLE
A way to drop fastnetmon_client results to file every 5s

### ISSUE THREAD

**Issue by robdn** [pavel-odintsov/fastnetmon#466]
Hey,
I was wondering if there is a way to dump fastnetmon_client results to file every, for example, 5 s?

Kind Regards,
Dom

**Comment by robdn** [comment]
Ok, asked question without reading the source code.

The data is available at /tmp/fastnetmon.dat

**Comment by pavel-odintsov** [comment]
Hi!

You also could change timeout for printing data to /tmp/fastnetmon.dat with check_period = 1 option in /etc/fastnetmon.conf
