### ISSUE TITLE
White list not working

### ISSUE THREAD

**Issue by s4m4n** [pavel-odintsov/fastnetmon#467]
I just noticed that the whitelist is not working and it triggers the bash script and send out notification.

Any idea?

**Comment by pavel-odintsov** [comment]
Hi

What format have you used for whitelist? Could you share logs?

**Comment by s4m4n** [comment]
cat whitelist :
127.0.0.1
192.168.1.1
192.168.10.0/29

 [INFO] We loaded 3 networks from whitelist file
 [ERROR] Can't parse line from whitelist: 127.0.0.1

also I see lots of below every minute 
 [INFO] We haven't template for flowset_id: 512 but it's not an error if this message go away in 5-10 seconds. We need some time to learn it!

**Comment by pavel-odintsov** [comment]
Please use cidr mask for all records here:
```bash
127.0.0.1/32
192.168.1.1/32
```

**Comment by s4m4n** [comment]
seems to be solved, what is the other error for ?

**Comment by pavel-odintsov** [comment]
It's about broken support for NetFLOW option templates.
