### ISSUE TITLE
FYI - Type of attack detection

### ISSUE THREAD

**Issue by mail3dexter** [pavel-odintsov/fastnetmon#469]
All types of attacks are listed here:

https://www.stateoftheinternet.com/types-of-ddos-attacks.html

**Comment by pavel-odintsov** [comment]
Thanks! Very useful and detailed description!

On Monday, 21 December 2015, Mayur Patel <notifications@github.com> wrote:

> All types of attacks are listed here:
>
> https://wwwstateoftheinternetcom/types-of-ddos-attackshtml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/469>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by craig** [comment]
I think the summaries there are not too good, they don't categorize and are somewhat redundant IMHO.
