### ISSUE TITLE
Telnet Exabgp / expect integration

### ISSUE THREAD

**Issue by sever-sever** [pavel-odintsov/fastnetmon#471]
Многие сталкивались с данной проблемой.
Суть в том, что используя ExaBgp и указывая next-hop-ом FastNetMon (10.0.3.114)  комьюнити прекрасно ловятся на стороне ядра, и пересылаются с комьюнити блекхола на нужные аплинки. Но отправляя next-hop-ом адрес нужного шлюза (1.1.1.1), ядро не ловит этот префикс, т.к. ExaBgp ничего не знает о данном роуте.
А есть ли функция, которая заворачивает траффик на ядре статикой?

В простом варианте, при срабатывании бана на атакуемый хост 10.0.0.1

Предпологается зайти телнетом на ядро (маршрутизатор) и отправить  команду:
 "ip route 10.0.0.1 255.255.255.255 Null0 tag 666"

Но не всегда надо заварачивать трафик в Null0, а при атаке на хост, например заворчивать трафик на другой шлюз.
 "ip route 10.0.0.1 255.255.255.255  1.1.1.1"

Пробовал через PBR, получается довольно криво. Есть ли варианты?

**Comment by pavel-odintsov** [comment]
Привет!

Посылку команды через телнет можно реализовать силами notify_script и ban / unban действий. Ну или можно также выбрасывать вручную маршрут на ExaBGP до нужного nexthop.

**Comment by sever-sever** [comment]
Спасибо. 
Если кому интересно будет.
Решено добавлением 2 функций для ban и unban.
Необходимо доустановить expect, для надёжности срабатывания.

#!/usr/bin/env bash

# This script will get following params:
#  $1 client_ip_as_string
#  $2 data_direction
#  $3 pps_as_string
#  $4 action (ban or unban)

#  sh notify_about_attack.sh 10.1.1.1 inbound_direction 24 ban
#  ban "ip route 10.1.1.1 255.255.255.255 1.1.1.1"
#  unban "no ip route 10.1.1.1 255.255.255.255 1.1.1.1"

banip=$1
# Gateway nexthop for static routes banned ip
gateway_nexhop=1.1.1.1

core_ip=192.168.0.10
core_login=admin_login
core_pass=admin_password
core_en_pass=enable_password


function func_ban {
(expect -c "

spawn telnet $core_ip
    expect \"Please Enter Password:\"
    send \"$core_pass\r\"
    expect \">\"
    send \"enable\r\"
    expect \"Password:\"
    send \"$core_en_pass\r\"

    expect \"#\"
    send \"configure terminal\r\"
    expect \"(config)#\"
    send \"ip route $banip 255.255.255.255 $gateway_nexhop\r\"
    send \" \r\"

    expect \"(config)#\"
    send \"end\r\"
    expect \"#\"
    send \"logout\r\"
interact
")
}

function func_unban {
(expect -c "

spawn telnet $core_ip
    expect \"Please Enter Password:\"
    send \"$core_pass\r\"
    expect \">\"
    send \"enable\r\"
    expect \"Password:\"
    send \"$core_en_pass\r\"

    expect \"#\"
    send \"configure terminal\r\"
    expect \"(config)#\"
    send \"no ip route $banip 255.255.255.255 $gateway_nexhop\r\"

    expect \"(config)#\"
    send \"end\r\"
    expect \"#\"
    send \"logout\r\"
interact
")
}


if [ "$4" = "unban" ]; then
    echo
    echo "END atack on client $1 direction $2, pps $3 and action $4"
    func_unban
    exit 0
fi

if [ "$4" = "ban" ]; then
    echo
    echo "Detect atack on client $1 direction $2, pps $3 and action $4"
    func_ban
    exit 0
fi

**Comment by sever-sever** [comment]
Помогло действия для ban / unban.
Если кому интересно, необходимо доставить expect для надёжности выполнения команд.
Добавлено 2 функции, при бане, маршрут заносится в маршрутизатор указывая новый шлюз.
При разблокировке маршрут снимается.
Спасибо. Буду дальше прикручивать.


#!/usr/bin/env bash

\# This script will get following params:
\#  $1 client_ip_as_string
\#  $2 data_direction
\#  $3 pps_as_string
\#  $4 action (ban or unban)

\# sh notify_about_attack.sh 10.1.1.1 inbound_direction 24 ban
\#  ban "ip route 10.1.1.1 255.255.255.255 1.1.1.1"
\#  unban "no ip route 10.1.1.1 255.255.255.255 1.1.1.1"

banip=$1
\# Gateway nexthop for static routes banned ip
gateway_nexhop=1.1.1.1

core_ip=192.168.0.10
core_login=admin_login
core_pass=admin_password
core_en_pass=enable_password


function func_ban {
(expect -c "

spawn telnet $core_ip
    expect \"Please Enter Password:\"
    send \"$core_pass\r\"
    expect \">\"
    send \"enable\r\"
    expect \"Password:\"
    send \"\$core_en_pass\r\"
    expect \"#\"
    send \"configure terminal\r\"
    expect \"(config)#\"
    send \"ip route $banip 255.255.255.255 $gateway_nexhop\r\"
    expect \"(config)#\"
    send \"end\r\"
    expect \"#\"
    send \"logout\r\"
interact
")

}

function func_unban {
(expect -c "

spawn telnet $core_ip
    expect \"Please Enter Password:\"
    send \"$core_pass\r\"
    expect \">\"
    send \"enable\r\"
    expect \"Password:\"
    send \"$core_en_pass\r\"
    expect \"#\"
    send \"configure terminal\r\"
    expect \"(config)#\"
    send \"no ip route $banip 255.255.255.255 $gateway_nexhop\r\"
    expect \"(config)#\"
    send \"end\r\"
    expect \"#\"
    send \"logout\r\"
interact
")
}


if [ "$4" = "unban" ]; then
    echo
    echo "END atack on client $1 direction $2, pps $3 and action $4"
    func_unban
    exit 0
fi

if [ "$4" = "ban" ]; then
    echo
    echo "Detect atack on client $1 direction $2, pps $3 and action $4"
    func_ban
    exit 0
fi

**Comment by pavel-odintsov** [comment]
Да, отличный кейс :) А если выделите отдельными скриптами - cisco_ban / cisco_unban можете прислать Pull Request их в папочку scripts, явно будут многим полезны :)

**Comment by plojr** [comment]
Guys, when you use telnet in func_ban, you don't need to use ExaBGP? Can I use the shell script in order to communicate with the router directly?

**Comment by pavel-odintsov** [comment]
Yes you can. Just add telnet call in example script https://github.com/pavel-odintsov/fastnetmon/blob/master/src/notify_about_attack.sh

**Comment by pavel-odintsov** [comment]
And yes exabgp is not required thing.

**Comment by pavel-odintsov** [comment]
I think that original issue was solved :)
