### ISSUE TITLE
Why didn't checked other traffic or internal traffic for DDOS detection?

### ISSUE THREAD

**Issue by mahdi1001** [pavel-odintsov/fastnetmon#472]
Fastnetmon is good, and it is very fast.
We want match "other traffic" and "internal traffic" with ddos detection.
but only incoming and outgoing traffic match with ddos detection.
is it impossible?!!!

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately we haven't support for tracking internal traffic.

But "other" traffic means "not your network traffic" so it's speaking about mistake in configuration (you lost some network in /etc/networks_list) or spoofied traffic in your network.

In normal case should have zero counters for other traffic.

**Comment by mahdi1001** [comment]
Hello :)
I bridge 2 interface in my system, and fastNetmon show this data:
Incoming traffic             0 pps      0 mbps      0 flows
Outgoing traffic             0 pps      0 mbps      0 flows
Internal traffic             0 pps      0 mbps
Other traffic            71260 pps    761 mbps.

and /etc/networks_list is empty.
in client run  iperf3 -c 10.10.10.10 -p 8080 -P 80 -u -b 200M  -t 60.
and in server run iperf3 -s -p 8080.
All of them match to other traffic!!!

**Comment by pavel-odintsov** [comment]
Hello,

You should add all your networks in /etc/networks_list in CIDR form. After this FastNetMon will detect traffic direction and you could get zero "other" counter.

**Comment by mahdi1001** [comment]
TNX.
OK, but support for tracking internal traffic is very necessary.
Has it the solution?!
If my change all direction to outgoing in source code for support tracking , is it correct? has it problem?
fro example:
in function "get_packet_direction" return just "OUTGOING" for support tracking in all traffic.

**Comment by pavel-odintsov** [comment]
Hello!

Yep, it's possible. But it's very dirty hack. You could replace this line (packet_direction = INTERNAL;): https://github.com/pavel-odintsov/fastnetmon/blob/1740d754dc1017c298b4a3227705ce7c4b6f0f88/src/fast_library.cpp#L844

By this code:
```C++
        subnet = destination_subnet;
        subnet_cidr_mask = destination_subnet_cidr_mask;

        packet_direction = INCOMING;
```

**Comment by KingJiJi** [comment]
Hello :
repleace  (packet_direction = INTERNAL;): can help support "internal traffic"  ?

replease it need reinstall ?

thank you  .
