### ISSUE TITLE
[INFO] We detected this attack by pps limit

### ISSUE THREAD

**Issue by mdpuma** [pavel-odintsov/fastnetmon#474]
В моменты атаки, лог заполняется сообщениями 

[INFO] We detected this attack by pps limit

Возможно убрать это ? или сделать уровни логирования настраиваемыми из конфиг файла.

**Comment by cuddylier** [comment]
Would be great if you could add some logging options to stop receiving spam emails, my VPS IP was blocked by gmail in the process of testing due to so many emails attempting to be sent about the same attack. I am not using fastnetmon for nullroute purposes, just monitoring so only really need an email about an attack once and not constantly every second.

**Comment by pavel-odintsov** [comment]
Hello

You could try net healer project from Vicente De Luca. It coukd prevent so
much notify emails.

On Friday, 22 January 2016, cuddylier <notifications@github.com> wrote:

> Would be great if you could add some logging options to stop receiving
> spam emails, my VPS IP was blocked by gmail in the process of testing due
> to so many emails attempting to be sent about the same attack. I am not
> using fastnetmon for nullroute purposes, just monitoring so only really
> need an email about an attack once and not constantly every second.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/474#issuecomment-173718141>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by cuddylier** [comment]
I'll look into it but it looks like a lot of work to get it up and running, I'm not that tech savvy when it comes to things that in depth so might not be possible to setup.

**Comment by pavel-odintsov** [comment]
You could set ban_time to some large value ~ 3600 and specify blank ban action. And you could get emails about attacks only every hour.

**Comment by mdpuma** [comment]
Было бы не плохо упомянуть в readme об этом проэкте, ввиду того что наверняка, многие ставят fastnetmon на множество серверов.

**Comment by cuddylier** [comment]
If I specified no ban action then I wouldn't get an email at all? Or are you talking about using net healer?

**Comment by pavel-odintsov** [comment]
We are speaking about Net Healer. Sorry about non english language here.

**Comment by mdpuma** [comment]
Возвращаюсь к вопросу о сообщениях в логе

We detected this attack by pps limit

Возможно ли не писать их логи если ип адрес находится в whitelist ?

**Comment by mdpuma** [comment]
Решил проблему через hostgroups указав подсети белого списка с опцией enable_ban = no

**Comment by pavel-odintsov** [comment]
Хороший вариант;)

On Friday, 6 May 2016, mdpuma <notifications@github.com> wrote:

> Решил проблему через hostgroups указав подсети белого списка с опцией
> enable_ban = no
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/474#issuecomment-217401263>
>


-- 
Sincerely yours, Pavel Odintsov
