### ISSUE TITLE
need feature to reload config on signal HUP

### ISSUE THREAD

**Issue by pubyun** [pavel-odintsov/fastnetmon#477]
as title

**Comment by pavel-odintsov** [comment]
Hello!

It's very complex task because we are working on very-very-very high packet rates. What certainly you need to change in runtime?

**Comment by pubyun** [comment]
i check the code, it's hard to reload config in runtime.
we should keep ban list of hosts of fastnetmon on restart or clear the ban list before exit.

i prefer to keep state of ban list on restart.

**Comment by pavel-odintsov** [comment]
You could use API and handle this process manually. You could trigger unban in shutdown with external script: https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/API.md
