### ISSUE TITLE
man page for program

### ISSUE THREAD

**Issue by pubyun** [pavel-odintsov/fastnetmon#478]

**Comment by pavel-odintsov** [comment]
You could check this https://github.com/pavel-odintsov/fastnetmon/tree/master/src/man

**Comment by pubyun** [comment]
sorry, i got the man page now.
there are some import missing information in them. such as:

--configuration_file arg set path to custom configuration file
list the signal handle information

**Comment by pavel-odintsov** [comment]
Yep, it's problem. Not all features well documented.
