### ISSUE TITLE
fastnetmon_api_client не собирается

### ISSUE THREAD

**Issue by mdpuma** [pavel-odintsov/fastnetmon#480]
Здравствуйте,

fastnetmon_api_client не собирается. Последнюю версию пробую собрать.

Также, интересует где хранится информация о забаненных ип адресах и персистентно ли это.

**Comment by pavel-odintsov** [comment]
Приветствую

С какой ошибкой-то?;)

On Wednesday, 13 January 2016, mdpuma <notifications@github.com> wrote:

> Здравствуйте,
>
> fastnetmon_api_client не собирается Последнюю версию пробую собрать
>
> Также, интересует где хранится информация о забаненных ип адресах и
> персистентно ли это
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/480>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by mdpuma** [comment]
Он в принципе не присутствует в папке в которой собирается софт.

Прикрепляю лог сборки.
[fastnetmon_install.log.txt](https://github.com/pavel-odintsov/fastnetmon/files/90032/fastnetmon_install.log.txt)

**Comment by pavel-odintsov** [comment]
Чтобы они собрались нужно включить поддержку GoBGP и готовится не поседеть от сборки. 

Раскомментируем в CmakeLists.txt:
```bash
# set(ENABLE_GOBGP_SUPPORT "yes")
```

**Comment by pavel-odintsov** [comment]
Но вообще это лучше делать в инсталлере, потому что без его помощи собирать это дело - дохлый номер. В инсталлере правим my $enable_gobgp_backend = ''; на  = '1' и собираем версию из гита.  Будет ОЧЕНЬ долго.

**Comment by mdpuma** [comment]
Понял,

А второй вопрос. Где хранится кроме как в памяти забаненные ип адреса ? и персистентность возможно сделать ?

**Comment by pavel-odintsov** [comment]
Нигде не хранятся. Только по API выдаются

**Comment by pavel-odintsov** [comment]
We've improved API support and you can try it here https://fastnetmon.com/docs/fastnetmon-community-api/
