### ISSUE TITLE
Unable to get exabgp announcement as next-hop fails

### ISSUE THREAD

**Issue by juesor** [pavel-odintsov/fastnetmon#482]
/etc/exabgp_blackhole.conf
http://pastebin/com/K0M52hW2

/etc/fastnetmon.conf
http://pastebin.com/qNTwvP7T

**Comment by pavel-odintsov** [comment]
Hello!

What's error / issue do you have here?

**Comment by juesor** [comment]
With those configs my ASR1K's are not receiving exabgp null route notices.

I am pretty sure that my two conf files look correct.

Do you agree?

I'll swing in my network admin if you have any thoughts on what could be an issue.

**Comment by pavel-odintsov** [comment]
Could you try directly to announce next hop with exabgp without FastNetMon?  Actually if issue with ExaBGP I could not help here.

You could switch from ExaBGP to GoBGP and use gobgp's CLI for announces from nofity script. GoBGP working pretty well and could be debugged. 

But ExaBGP debugging is a _HUGE_ pain actually.

**Comment by juesor** [comment]
So installing GoBGP.

I need to reinstall FastNetMon?  or can i just edit my fastnetmon.conf to add goBGP info I don't see an install command 

https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/GOBGP.md

**Comment by pavel-odintsov** [comment]
Hello!

GoBGP support is very complicated. So I could recommend to install GoBGP stand alone and interact with it with notify_script.

**Comment by juesor** [comment]
root@ACENTEK-FastNetMon2:/etc# /opt/gobgp_1_0_0/gobgpd -f /etc/gobgpd.conf
{"level":"info","msg":"gobgpd started","time":"2016-01-18T09:05:36-06:00"}
{"level":"fatal","msg":"can't read config file /etc/gobgpd.conf, 1 error(s) decoding:\n\n* 'neighbors': source data must be an array or slice, got map","time":"2016-01-18T09:05:36-06:00"}

**Comment by pavel-odintsov** [comment]
Just a second :) I will fix my configuration example because they changed format.

**Comment by pavel-odintsov** [comment]
Please try updated configuration example for GoBGP: https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/GOBGP.md

**Comment by juesor** [comment]
just throwing this out there while you were updating configs 

Can't build fastnetmon! at fastnetmon_install.pl line 1478, <STDIN> line 1.


i threw up a test vm and did the install from perl modifiying the gobgp to 1 and thats what i got when trying to install fastnetmon

**Comment by pavel-odintsov** [comment]
It's bad idea. I could not help with this installer when GoBGP enabled because it required so big amount of fixes for compatibility.

Just try console integration with GoBGP instead full integration.
