### ISSUE TITLE
Segfault when using Netflow LUA

### ISSUE THREAD

**Issue by fargox** [pavel-odintsov/fastnetmon#483]
Hi,

i've compiled fastnetmon with lua as described in the doc. I am using netflow which is working as expected but not giving any attack details in the email, just the normal summary. I hope for this with lua. As soon as i uncomment the lua part, fastnetmon is directly dying. 

[202160.956315] fastnetmon[15558]: segfault at 8 ip 00007fb79fcc4210 sp 00007fb793fee6b8 error 4 in libluajit-5.1.so.2.0.4[7fb79fcb0000+6d000]
[202177.968145] fastnetmon[15577]: segfault at 8 ip 00007f99b281c210 sp 00007f99ab7096b8 error 4 in libluajit-5.1.so.2.0.4[7f99b2808000+6d000]

I am running Ubuntu LTS 14.04 and also loaded the patch files mentioned in the doc. 

Any idea?

Best regards

**Comment by pavel-odintsov** [comment]
Hello!

Could you install git version with install script?

```bash
wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl --use-git-master
```

**Comment by fargox** [comment]
Still the same issue:

[375680.952637] fastnetmon[1231]: segfault at 8 ip 00007f2329baa210 sp 00007f23229056b8 error 4 in libluajit-5.1.so.2.0.4[7f2329b96000+6d000]

**Comment by pavel-odintsov** [comment]
Hi

Very sad.

Could you run debugger on produced core file?

gdb /opt/fastnetmon/fastnetmon Core

Then call command: backtrace

And send output to me.

So will be fine to know your task and I could try to offer some workaround
for it.

On Monday, 18 January 2016, fargox <notifications@github.com> wrote:

> Still the same issue:
>
> [375680.952637] fastnetmon[1231]: segfault at 8 ip 00007f2329baa210 sp
> 00007f23229056b8 error 4 in libluajit-5.1.so.2.0.4[7f2329b96000+6d000]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/483#issuecomment-172649870>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Please reopen if you still have this issue.
