### ISSUE TITLE
Не компилируется pf_ring

### ISSUE THREAD

**Issue by lexesv** [pavel-odintsov/fastnetmon#484]
Добрый день!

При попытке установить fastnetmon возникает ошибка с pf_ring.

ОС: Linux 3.2.0-4-rt-amd64 #1 SMP PREEMPT RT Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
gcc version 4.7.2 
Сетевая карта: product: 82579V Gigabit Network Connection, vendor: Intel Corporation

Пробовал скомпилировать его вручную:

webmaster@shost:/build/pf_ring/PF_RING-6.0.3/kernel$ make
make -C /lib/modules/3.2.0-4-rt-amd64/build SUBDIRS=/build/pf_ring/PF_RING-6.0.3/kernel EXTRA_CFLAGS='-I/build/pf_ring/PF_RING-6.0.3/kernel -DSVN_REV="\"exported\""' modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-4-rt-amd64'
  CC [M]  /build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.o
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:176:3: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:176:3: error: (near initialization for ‘virtual_filtering_lock’)
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:178:1: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:186:3: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:186:3: error: (near initialization for ‘ring_cluster_lock’)
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:188:1: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:214:3: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:214:3: error: (near initialization for ‘cluster_fragments_lock’)
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:216:1: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:233:3: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:233:3: error: (near initialization for ‘dna_cluster_lock’)
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:235:1: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:243:3: error: initializer element is not constant
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:243:3: error: (near initialization for ‘cluster_referee_lock’)
/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.c:245:1: error: initializer element is not constant
make[4]: *** [/build/pf_ring/PF_RING-6.0.3/kernel/pf_ring.o] Error 1
make[3]: *** [_module_/build/pf_ring/PF_RING-6.0.3/kernel] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-4-rt-amd64'
make: *** [all] Error 2

С версией 6.2.0:

make -C /lib/modules/3.2.0-4-rt-amd64/build SUBDIRS=/build/pf_ring/PF_RING-6.2.0/kernel EXTRA_CFLAGS='-I/build/pf_ring/PF_RING-6.2.0/kernel -DGIT_REV="\"6.2.0-stable:6e64d978b8877c61b68da1ec3f9e2bde80ca8892\""' modules
make[1]: Entering directory `/usr/src/linux-headers-3.2.0-4-rt-amd64'
  CC [M]  /build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.o
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c: In function ‘init_ring_readers’:
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c:288:5: error: expected expression before ‘{’ token
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c: In function ‘init_lockless_list’:
/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.c:520:5: error: expected expression before ‘{’ token
make[4]: *** [/build/pf_ring/PF_RING-6.2.0/kernel/pf_ring.o] Error 1
make[3]: *** [_module_/build/pf_ring/PF_RING-6.2.0/kernel] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.2.0-4-rt-amd64'
make: *** [all] Error 2

Не подскажите в чем может быть проблема и как её исправить?
Заранее спасибо.

**Comment by pavel-odintsov** [comment]
Добрый день!

Я думаю дело в -rt- ядре, попробуйте обычное ядро загрузить и собраться на нем.

**Comment by lexesv** [comment]
Получилось. Спасибо огромное!

**Comment by pavel-odintsov** [comment]
Я рад :) Отлично! Может попробуете сообщить о баге в PF_RING - https://github.com/ntop/PF_RING ? Они смогут оценить, сложно ли сделать саппорт RT ядра.

**Comment by lexesv** [comment]
Написал.
https://github.com/ntop/PF_RING/issues/65

**Comment by pavel-odintsov** [comment]
Круто, спасибо :)

**Comment by lexesv** [comment]
Я вот подумал, а что если его компилить не с linux-headers-3.2.0-4-rt-amd64 а с linux-headers-3.2.0-4-amd64.
В Makefile прописать статично переменную, вместо
BUILD_KERNEL=$(shell uname -r)
BUILD_KERNEL='3.2.0-4-amd64'

Но, что то страшновато экспериментировать на рабочем сервере : )

**Comment by pavel-odintsov** [comment]
Да, RT ядра отличаются и это может поломать фишки PF_RING.

**Comment by lexesv** [comment]
Извиняюсь за reopen.

Поддержка PF_RING проигнорировала проблему с RT ядрами. Тему закрыли : (

Может кому пригодиться:
1. aptitude install linux-image-3.2.0-4-amd64 linux-headers-3.2.0-4-amd64
2. Меняем /etc/default/grub GRUB_DEFAULT на нужное для загрузки ядро (у меня было 0, сменил на 2). Посмотреть очередность можно в grub.cfg
3. update-grub
4. reboot
После этого fastnetmon устанавливается без проблем.

PS. в 32 битной Ubuntu монитор падает при трафике >100 Мбит/с (проверял на домашнем сервере копированием видеофайла через самбу) В kern.log: kernel: [26124.993240] fastnetmon[6513]: segfault at 80de9 ip b72d4fef sp b50714c0 error 4 in libc-2.19.so[b728d000+1a8000]

**Comment by pavel-odintsov** [comment]
Ага. спасибо, я думаю кому-либо явно пригодится.
