### ISSUE TITLE
Stdin errors using notify_about_attack.sh

### ISSUE THREAD

**Issue by cuddylier** [pavel-odintsov/fastnetmon#485]
Hi

I'm using the notify_about_attack.sh script here: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/notify_about_attack.sh on the github master version but get the following errors in my logs during an attack: http://pastebin.com/raw/jDiDhB75

I am using CentOS 6.6 64 bit and have postfix installed.

Config: http://pastebin.com/raw/NEbMFhQN

**Comment by pavel-odintsov** [comment]
Could you run your notify script manually with "ban" athument option and
check it?

On Saturday, 23 January 2016, cuddylier <notifications@github.com> wrote:

> Hi
>
> I'm using the notify_about_attack.sh script here:
> https://github.com/pavel-odintsov/fastnetmon/blob/master/src/notify_about_attack.sh
> on the github master version but get the following errors in my logs during
> an attack: http://pastebin.com/raw/jDiDhB75
>
> I am using CentOS 6.6 64 bit and have postfix installed.
>
> Config: http://pastebin.com/raw/NEbMFhQN
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/485>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by cuddylier** [comment]
How would I exactly do that? Just type 'ban /usr/local/bin/notify_about_attack.sh'?

**Comment by pavel-odintsov** [comment]
Just simulate options which fastnetmon passes to script and run your notify
script with this option.

I.e. ./notify-script.sh ban 11.22.33.44

On Sunday, 24 January 2016, cuddylier <notifications@github.com> wrote:

> How would I exactly do that? Just type 'ban
> /usr/local/bin/notify_about_attack.sh'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/485#issuecomment-174225105>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by cuddylier** [comment]
I tried that and there was no output in SSH and the /var/log/maillog had nothing new either.

**Comment by pavel-odintsov** [comment]
You will never get something in maillof or fastnetmon.log. This just for testing your script. Because actually there are no problem in FNM here. I suppose it's related with broken notify script.

**Comment by cuddylier** [comment]
I found out the 'mail' command wasn't actually installed, after installing e.g. echo "hi" | mail -s "FastNetMon Guard: IP hgfgh blocked because fghfgh attack with power fgh pps" [myemail]; works fine however doing './notify_about_attack.sh ban [ip]' does nothing and no email is received.

I added code to output the $4 value and it returned a blank so it's not accepting the 'ban' parameter.

**Comment by cuddylier** [comment]
It seems to have randomly fixed itself after I installed 'mailx' for the 'mail' command.

**Comment by pavel-odintsov** [comment]
That's nice! Good hit ;)

On Monday, 25 January 2016, cuddylier <notifications@github.com> wrote:

> Closed #485 <https://github.com/pavel-odintsov/fastnetmon/issues/485>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/485#event-525533249>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by williangarcia** [comment]
Hello , help me please , How do I import the script "/usr/local/bin/notify_about_attack.sh" into an InfluxDB database.

**Comment by pavel-odintsov** [comment]
Hello!

You writing into closed ticket. The problem in this ticket was solved. Please raise a new one.
