### ISSUE TITLE
hostgroup not working, seems to whitelist hosts?

### ISSUE THREAD

**Issue by paracusia** [pavel-odintsov/fastnetmon#486]
hello,

i tried the hostgroup feature like this:

added 1.2.3.0/24 to /etc/networks_list

added this to the config:

hostgroup = mytest:1.2.3.0/24
mytest_enable_ban = yes
mytest_ban_for_pps = yes
mytest_ban_for_bandwidth = yes
mytest_ban_for_flows = no
mytest_threshold_pps = 200000
mytest_threshold_mbps = 1000
mytest_threshold_flows = 0

i tested with 250kpps and it didnt reacted to it at all, seams like the hostgroup feature is misunderstood as whitelist from the code? please explain that to me :)

thank you

**Comment by pavel-odintsov** [comment]
Hello!

Please replace ''yes" to "on" and everything will work fine :)

**Comment by paracusia** [comment]
thank you! :-)

**Comment by pavel-odintsov** [comment]
Have you solved your issue?

**Comment by paracusia** [comment]
yes. its working now, thank you very much! :-)

**Comment by pavel-odintsov** [comment]
NIce!
