### ISSUE TITLE
wrong speed and pps count 

### ISSUE THREAD

**Issue by elibeker** [pavel-odintsov/fastnetmon#489]
running fastnetmon on 10Gbps internet connection using span port on Cisco ASR 9000 and Ixia port dup. 
the issue is with the traffic count by fastnetmon that is 1.5 and more of the real throughput of the span port. we have multiple tools measuring this traffic as well as throughput on the fastnetmon server that shoes same number, so I believe the problem is with fastnetmon.
I've tested both netmap and pf_ring drivers but they both give the same 'wrong' numbers.  
any help, plz.

FastNetMon v1.0 FastVPS Eesti OU (c) VPS and dedicated: http://FastVPS.host
IPs ordered by: packets
Incoming traffic        455028 pps   6346 mbps      0 flows
XXX.Y6.102.215           14601 pps    293 mbps      0 flows
XXX.Y4.113.44             9329 pps    298 mbps      0 flows
XXX.Y39.200.4             8723 pps    149 mbps      0 flows
XXX.Y39.200.7             8279 pps    123 mbps      0 flows
XXX.Y39.200.5             9189 pps    121 mbps      0 flows
XXX.Y14.102.174            159 pps      0 mbps      0 flows
XXX.Y14.91.215            6987 pps     71 mbps      0 flows
XXX.Y39.200.6             7716 pps    118 mbps      0 flows
XXX.Y4.113.140            3660 pps     29 mbps      0 flows
XXX.Y6.80.106             6227 pps    490 mbps      0 flows

Outgoing traffic        548742 pps   3117 mbps      0 flows
XXX.Y39.196.102          22065 pps    164 mbps      0 flows
XXX.Y6.102.215           13864 pps      8 mbps      0 flows
XXX.Y4.113.44            10548 pps      5 mbps      0 flows
XXX.Y14.102.174            520 pps     45 mbps      0 flows
XXX.Y2.114.206             169 pps      0 mbps      0 flows
XXX.Y14.91.215            8414 pps     38 mbps      0 flows
XXX.Y14.91.214            6056 pps     26 mbps      0 flows
XXX.Y14.23.209            7887 pps     27 mbps      0 flows
XXX.Y6.110.100            3559 pps     25 mbps      0 flows
XXX.Y14.105.254           7600 pps     19 mbps      0 flows

Internal traffic             0 pps      0 mbps

Other traffic            17900 pps    171 mbps

Screen updated in:              11 sec 283317 microseconds
Traffic calculated in:          2 sec 744975 microseconds
Total amount of not processed packets: 420641
Packets received:       191806836
Packets dropped:        76037
Packets dropped:        0.0 %

Subnet load:
XXX.Y4.0.0/15           pps in: 53984 out: 56672 mbps in: 632 out: 214
XXX.Y6.0.0/15           pps in: 111145 out: 122553 mbps in: 1107 out: 527
XXX.Y8.0.0/15           pps in: 46065 out: 40610 mbps in: 547 out: 252
XXX.Y0.0.0/15           pps in: 32611 out: 31232 mbps in: 318 out: 103
XXX.Y2.0.0/15           pps in: 47159 out: 47510 mbps in: 736 out: 95
XXX.Y4.0.0/15           pps in: 56436 out: 65464 mbps in: 768 out: 207
XXX.Y6.0.0/15           pps in: 40941 out: 41456 mbps in: 1290 out: 187
XXX.Y14.0.0/17          pps in: 96104 out: 106558 mbps in: 1839 out: 1361
XXX.Y39.0.0/16          pps in: 63166 out: 47222 mbps in: 942 out: 259
XXX.Y33.0.0/16          pps in: 2350 out: 296 mbps in: 3 out: 2
XXX.Y15.64.0/23         pps in: 394 out: 3 mbps in: 3 out: 0
XXX.Y17.80.0/20         pps in: 113 out: 0 mbps in: 0 out: 0
XXX.Y39.197.124/32      pps in: 0 out: 0 mbps in: 0 out: 0

Traffic load with nload on the interface:
Incoming:
  Curr: 3.02 GBit/s
  Avg: 2.78 GBit/s
  Min: 2.42 GBit/s
  Max: 3.06 GBit/s
  Ttl: 491.16 GByte
Outgoing:
  Curr: 0.00 Bit/s
  Avg: 0.00 Bit/s
  Min: 0.00 Bit/s
  Max: 0.00 Bit/s
  Ttl: 648.00 Byte

**Comment by pavel-odintsov** [comment]
Hello!

Traffic mirror offer best accuracy for traffic bandwidth. But we are traffic smoothing and it could broke your data :)

Actually you have very slow server or very big amount of networks:
```bash
Traffic calculated in: 2 sec 744975 microseconds
```

This value SHOULD be less than 1 second. In other case you could get incorrect speed.

**Comment by elibeker** [comment]
Hi,
Thanks for the prompt reply.
Do you have any recommendation for a decent server that will take this
amount of traffic?
tnx, -eli

**Comment by pavel-odintsov** [comment]
How much network do you have? I need size in hosts. i7 2600 will be enough for 10 /20 networks.

**Comment by elibeker** [comment]
We have about 17 class B networks, split into 7 classless network (/15), 2
class B (/16) and half class B (/17).
Hosts we have about 20K.
Traffic may reach the 10Gbs inbound and outbound.
-eli

**Comment by pavel-odintsov** [comment]
That's very big amount of traffic. We could handle about 2*/16 on single box. You could spread traffic to multiple FastNetMon instances.

**Comment by pavel-odintsov** [comment]
Just split your networks between two FastNetMon instances and each box will handle traffic in 1 second :)

**Comment by elibeker** [comment]
will try that.
will filter the traffic on the Ixia to only half of the segments and see
who's dying first, the Ixia or the server. ;)
Do you believe a stronger server, e.g. CPU and memory, will be able to
handle this traffic? any experience at ISP level with FastNetMon?
I will update you back.
-eli

**Comment by pavel-odintsov** [comment]
Really any box with least 4 cores could handle 10GE at line rate in netmap mode. It's not a challenge. 

But traffic calculation thread uses only single core and you need as fast as possible cpu to handle all traffic on single box.

There are a lot of ISP experience. We have top customers with ~140GE of total capacity.

**Comment by elibeker** [comment]
so if I run it on a VM server, will I be able to better allocate CPU for
each instance?

**Comment by pavel-odintsov** [comment]
Yes, you could try.

**Comment by elibeker** [comment]
Tnx a lot.. your support is better than commercial products.. ;-)

**Comment by pavel-odintsov** [comment]
You are welcome ;)

**Comment by jemcek** [comment]
Hi Pavel!

I have a similar question. My incoming traffic counters shown by the Fastnetmon are higher than those on the router. 

For example, Juniper MX is showing me 65000 incoming packets per second, while Fastnetmon Incoming traffic is 80000 pps at the same moment. The difference is always about 15-20% on average. I have two instances of FastNetMon, one is pcap based capture and another netmap based and both have almost the same result.

But the ifconfig based results give me the same values as the router's one, I assume those are correct.

Typical values for "Traffic calculated in" are 0.6-0.7 secons.  

What could be the reason for that, do I have something misconfigured?

**Comment by pavel-odintsov** [comment]
Hello!

What's your netflow active / inactive timeouts (Juniper MX side) and average_calculation_time (FastNetMon side)?

**Comment by jemcek** [comment]
Hi Pavel!

The flow-active-timeout on the MX side is set to 300, however the values on the router side were taken from "monitor interface traffic” command, so this is probably not related?

On the FastNetMon side the average_calculation_time is 5. I tried also to set this value to 1, but didn’t notice any difference.

**Comment by pavel-odintsov** [comment]
300 seconds is really HUGE. I recommend 30 seconds for active and 30 seconds for inactive. average_calculation_time should be 45-60 seconds  for 30/30 configuration,

**Comment by elibeker** [comment]
Hi Pavel,
Splitting fastnetmon into few VM's did help. it reduced the load on single server while better utilizing the cpu cores on this physical server.
While switching into couple of vm's and pushing the results to grafana, I've noticed the graphite_prefix variable is fixed from fastnetmon.cpp and not from the conf file.
Is it right or something wrong on my side?
Many Thanks, eli

**Comment by pavel-odintsov** [comment]
Are you using master version or stable?  In master branch it should work correctly.

**Comment by pavel-odintsov** [comment]
So I'm closing this ticket. Please open new if you need help :)

**Comment by elibeker** [comment]
Tnx!
