### ISSUE TITLE
configuration options (plaintext packet dump and notify script parameters)

### ISSUE THREAD

**Issue by waszi** [pavel-odintsov/fastnetmon#492]
Please consider adding configurable option, I would like to disable collecting plain text packet dumps

I would like also to get information about pcap file name in notify script (attack_details). I am collecting
all attacks to database, and I would like to link to pcap file.

**Comment by pavel-odintsov** [comment]
Hello!

Actually we could not pass pcap file name because we generate in when it collected (few seconds later initial notify call). 

Maybe you could remove senstive information and share your attack database? It could improve detection logic for FNM.

**Comment by pavel-odintsov** [comment]
It's pretty complex to implement due to FNM's design. We may work on adding more information in callback scripts.
