### ISSUE TITLE
Sending data to Influxdb 

### ISSUE THREAD

**Issue by Lupul** [pavel-odintsov/fastnetmon#494]
Hello,
i have setup fastnetmon with influxdb and it looks to be working ok,
but I see that fastnetmon logs this error:
 "[ERROR] Can't store data to Graphite"

Can I increase the log level to see what measurement is failing?

**Comment by pavel-odintsov** [comment]
It could be related with short time network issues. If you havent so much
this records you could safely ignore they.

On Thursday, 25 February 2016, Zollner Robert <notifications@github.com>
wrote:

> Hello,
> i have setup fastnetmon with influxdb and it looks to be working ok,
> but I see that fastnetmon logs this error:
> "[ERROR] Can't store data to Graphite"
>
> Can I increase the log level to see what measurement is failing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/494>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by angry-tony** [comment]
@Lupul   awesome .. please share it..
i would like to see your instructions.. i've failed setting fastetmen with influxdb..

**Comment by pavel-odintsov** [comment]
Just follow this https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/GRAPHITE_INTEGRATION.md and this https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/INFLUXDB_INTEGRATION.md

**Comment by angry-tony** [comment]
ok.. thanks. i will do this..
