### ISSUE TITLE
Cann't detect icmp flood with fastnetmo!

### ISSUE THREAD

**Issue by mahdi1001** [pavel-odintsov/fastnetmon#495]
Hi
We edited  fastnetmon_config and change icmp_pps to 100 and ban_icmp is on, but cant't detect icmp flood attack with config.

threshold_tcp_mbps = 10
threshold_udp_mbps = 10
threshold_icmp_mbps = 10

threshold_tcp_pps = 100
threshold_udp_pps = 100
threshold_icmp_pps = 100

ban_for_tcp_bandwidth = on
ban_for_udp_bandwidth = on
ban_for_icmp_bandwidth = on

ban_for_tcp_pps = on
ban_for_udp_pps = on
ban_for_icmp_pps = on

# Different approaches to attack detection
ban_for_pps = on
ban_for_bandwidth = on
ban_for_flows = off

# Limits for Dos/DDoS attacks
threshold_pps = 2000000
threshold_mbps = 100000
threshold_flows = 350000

What's the problem???

**Comment by pavel-odintsov** [comment]
Two questions: 1) what capture method are you using (sflow / netflow / mirror) 2)You definitely should install latest version "--master option for installer"

**Comment by mahdi1001** [comment]
My capture method is mirror and use the pfring.
fastnetmon --version
Version: 1.1.3 master git-

**Comment by mahdi1001** [comment]
Excuse me.
Lasted revision is OK.
I think you need a 2 branch trunk and master., and set correct revision number after change code in master.
TNX

**Comment by pavel-odintsov** [comment]
Perfect!
