### ISSUE TITLE
How to black ATTACKER IP in fastnetmon?!

### ISSUE THREAD

**Issue by mahdi1001** [pavel-odintsov/fastnetmon#496]
Hello
I need black ip for attacker ip in notify_about_attack.sh.
In notify_about_attack.sh just show victim IP I need the Attacker IP?!!!

**Comment by pavel-odintsov** [comment]
Hello

Its impossible with current version. You could analyze attack dump manually
and detect attacker ip.

On Sunday, 28 February 2016, mahdi1001 <notifications@github.com> wrote:

> Hello
> I need black ip for attacker ip in notify_about_attack.sh.
> In notify_about_attack.sh just show victim IP I need the Attacker IP?!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/496>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by mahdi1001** [comment]
Just log/fastnetmon_attacks  contain attack details .
Also we should process  fastnetmon_attacks and show attackers ip.
Can show attackers ip in notify_about_attack.sh???

**Comment by pavel-odintsov** [comment]
No. You should process pcap dump or text attack details manually with your
custom code.

On Sunday, 28 February 2016, mahdi1001 <notifications@github.com> wrote:

> Just log/fastnetmon_attacks contain attack details .
> Also we should process fastnetmon_attacks and show attackers ip.
> Can show attackers ip in notify_about_attack.sh???
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/496#issuecomment-189842547>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by mahdi1001** [comment]
TNX

**Comment by mahdi1001** [comment]
Just Attack type is unknown!
why?!

**Comment by pavel-odintsov** [comment]
Hello

Because this attack type is unknown and you havent't offered any details or
pcap dump of attack.

We are open source project and you should not expect complete support for
all possible attack types until you contribute anything.

If you have new attack type - just contribute as much as possible details
or contribute code.

On Sunday, 28 February 2016, mahdi1001 <notifications@github.com> wrote:

> Just Attack type is unknown!
> why?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/496#issuecomment-189880871>
> .
>


-- 
Sincerely yours, Pavel Odintsov
