### ISSUE TITLE
fastnetmon не обнаружил атаку (400М)

### ISSUE THREAD

**Issue by lexesv** [pavel-odintsov/fastnetmon#497]
Добрый день.

Была атака на сервер (скрин)
![default](https://cloud.githubusercontent.com/assets/15149258/13379760/75ad2b5a-de37-11e5-999e-0e666e32b235.PNG)

Но каталогах /var/log/fastnetmon_attacks  и /root после окончания атаки никаких логов не появилось.
Скрипт бана также ни разу не сработал.
Используется PF_RING.

Содержимое конфига и бан скрипта.
[fastnetmon.txt](https://github.com/pavel-odintsov/fastnetmon/files/149944/fastnetmon.txt)
[ban.txt](https://github.com/pavel-odintsov/fastnetmon/files/149947/ban.txt)

Подскажите пожалуйста, в чем может быть причина?

**Comment by pavel-odintsov** [comment]
Добрый день! 

А какая версия используется? В стабильной баг с определением атаки по полосе. Обновитесь на git версию?

**Comment by lexesv** [comment]
Использовал для установки скрипт из этой ссылки:
https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/INSTALL.md

Спасибо, попробую обновиться до git версии.

**Comment by pavel-odintsov** [comment]
Мастер ставится вот так:
```bash
wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl --use-git-master
```

**Comment by lexesv** [comment]
Git версия не хочет устанавливаться.

> Clone FastNetMon repo
> Can't build fastnetmon! at fastnetmon_install.pl line 1478, <STDIN> line 1.

**Comment by pavel-odintsov** [comment]
Looks like you are using old version of fastnetmon_install.pl because upstream version hasn't anything on line 1478: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/fastnetmon_install.pl#L1478 

Можете явно стянуть новую версию fastnetmon_install.pl ?

**Comment by lexesv** [comment]
![ddos1](https://cloud.githubusercontent.com/assets/15149258/13530037/fcc9c1b8-e227-11e5-9194-ce9e7ae642d5.png)


Новая версия так же не увидела атаку...

**Comment by pavel-odintsov** [comment]
А лог и fastnetmon_client'а выдачу можно?

**Comment by lexesv** [comment]
![ftm](https://cloud.githubusercontent.com/assets/15149258/13530197/dd1d8556-e228-11e5-8c95-ed087329c310.PNG)

Логов в /root и /var/log нет.

![log](https://cloud.githubusercontent.com/assets/15149258/13530272/45308abc-e229-11e5-992a-c4ab8fa955e9.PNG)

**Comment by Anito23** [comment]
Скажите, пожалуйста, по приведенному логу загрузки скрипта fastnetmon видно, что в файле /etc/networks_list находиться одна подсеть для наблюдения. При этом, в файле /etc/networks_whitelist находиться 10 подсетей, блокировка для которых игнорируется (т.е. они не блокируются). Далее, судя по строке "We loaded 2 subnets to our in-memory list of networks" в память загружается две подсети, одна из файла /etc/networks_list и вторая из файла /etc/networks_whitelist. Так же, судя по строке "I will allocate 1 records for subnet 533898684 cidr mask: 32" есть вероятность того, что из обоих ранее указанных файлов был загружен один и тот же IP адрес /32. Тем самым, атаки идущие на IP адрес не блокируются, так как он указан в списке белых сетей (игнорируемых). 

Уточните, пожалуйста, IP адрес указанный в файле /etc/networks_list присутствует в файле /etc/networks_whitelist?

**Comment by lexesv** [comment]
Добрый день.
Большое спасибо!
Да, в /etc/networks_whitelist есть IP данного сервера.
Просто я не предполагал, что указав его в whitelist, атаки будут игнорироваться. Я думал что белые списки работают только для IP источников атаки, а не целей.

**Comment by lexesv** [comment]
Убрал IP сервера из networks_whitelist. И появилась другая проблема.
На сервере работают голосовые сервера, которые генерируют большой трафик:
Attack type: udp_flood
Initial attack power: 10168 packets per second
Peak attack power: 10168 packets per second
Attack direction: outgoing
Attack protocol: udp
Total incoming traffic: 3 mbps
Total outgoing traffic: 9 mbps
Total incoming pps: 4210 packets per second
Total outgoing pps: 10168 packets per second

И получается, что fastnetmon блокирует адрес самого сервера ):
Как решить эту проблему?

**Comment by Anito23** [comment]
Судя по всему, в Вашем случае не подойдет fastnetmon. Fastnetmon рассчитан для наблюдения за трафиком на роутерах и в случае атаки на определенный адрес, блокирование трафика на атакуемый адрес, к примеру, путем добавления его в блэкхол интернет провайдеров. 
В случае защиты конечного сервера fastnetmon не подойдет. Попробуйте использовать для своей задачи правила iptables ограничивающие количества подключений с IP адресов. К примеру, в статье http://www.linuxquestions.org/questions/linux-server-73/iptables-configuration-for-udp-flood-864070/ описан пример, как это сделать. В гугл можно найти много примеров решения подобной задачи.

**Comment by lexesv** [comment]
Дело в том, что мои я арендую сервера в OVH (SYS) c защитой от DDoS. Но как видно на скриншотах, атаки проходят, и в техподдержке порекомендовали мониторить трафик fastnetmon, что бы понять, почему так происходит. И логи отправить в службу AntiDDoS.

Фаервол настроен, стандартные правила защиты, плюс фильтры Азии, Южной Америки и т.д.
Но это не помогает, канал просто забивают. 

Вероятно, решением станет отключение блокирующего скрипта. Просто собирать логи...

**Comment by Anito23** [comment]
В данном случае, Вам лучше отключить все блокирующие правила в скрипте нотификации. оставив отправку письма. В файле конфигурации /etc/fastnetmon.conf активируйте два параметра:

# collect a full dump of the attack with full payload in pcap compatible format
collect_attack_pcap_dumps = on

# Execute Deep Packet Inspection on captured PCAP packets
process_pcap_attack_dumps_with_dpi = on

При этом, при атаке трафик на сервер не будет блокироваться, а будет собран pcap дамп трафика идущего на сервер во время атаки. После чего, pcap дамп и текстовый отчет можно будет найти в директории /var/log/fastnetmon_attacks. Просмотреть pcap дамп можно программой Wireshark. Сам дамп Вы можете отправить в службу AntiDDoS.

**Comment by Anito23** [comment]
Так же, судя по предоставленному отчету об исходящей атаке, рекомендуем повысить значение параметра threshold_pps до такого значения, чтобы скрипт не реагировал на нормальную работу сервера.

**Comment by lexesv** [comment]
Спасибо.
А если установить monitor_local_ip_addresses=off
то, возможно, fastnetmon не будет банить IP сервера?

**Comment by Anito23** [comment]
Данный параметр позволяет включить мониторинг трафика идущего на IP адреса принадлежащие серверу, на котором запущен скрипт fastnetmon. В Вашем случае, как раз такой IP адрес и нужно мониторить. Только в случае обнаружения атаки, Вам необходимо убрать какие либо действия блокирующие трафик, оставив только сбор статистики.

**Comment by lexesv** [comment]
Еще раз спасибо.

А если в бан скрипт прописать следующее, IP сервера баниться не будет?
```
if [ "$4" = "ban" ]; then
    # cat | mail -s "FastNetMon Guard: IP $1 blocked because $2 attack with power $3 pps" $email_notify;
    # You can add ban code here!
    if [ "$1" != "SERVER_IP" ] then
	  iptables -I INPUT -s $1 -j DROP
	  /usr/sbin/tcpdump -v -n -c 300 >> /root/attack_$time.log
	  /usr/sbin/tcpdump -v -x -n -w /root/ddos_$time.log -c 300
      exit 0
    fi
fi
```

**Comment by Anito23** [comment]
Правило iptables "iptables -I INPUT -s $1 -j DROP" в данном случае бесполезно, так как, fastnetmon установлен на конечном сервере, то в скрипт нотификации в качестве параметра $1 всегда будет передаваться IP самого сервера. При этом, получиться правило запрещающее входящий трафик с самого себя. Что в некоторых случаях может только навредить.

**Comment by pavel-odintsov** [comment]
I think conversation moved away from original issue :)
