### ISSUE TITLE
False positive in dos detection!

### ISSUE THREAD

**Issue by mahdi1001** [pavel-odintsov/fastnetmon#498]
Hello
Fastnetmon has false positive in ddos detection.
We send tcp (12pps) and udp (12pps) traffic.
config file:
threshold_tcp_mbps = 10
threshold_udp_mbps = 300
threshold_icmp_mbps = 10

threshold_tcp_pps = 10
threshold_udp_pps = 300
threshold_icmp_pps = 10

ban_for_tcp_bandwidth = off
ban_for_udp_bandwidth = off
ban_for_icmp_bandwidth = off

ban_for_tcp_pps = on
ban_for_udp_pps = on
ban_for_icmp_pps = on

# Different approaches to attack detection
ban_for_pps = on
ban_for_bandwidth = on
ban_for_flows = on

# Limits for Dos/DDoS attacks
threshold_pps = 700
threshold_mbps = 500
threshold_flows = 3500

and result is:
IP: 10.10.10.2
Attack type: unknown
Initial attack power: 23 packets per second
Peak attack power: 23 packets per second
Attack direction: incoming
Attack protocol: tcp
Total incoming traffic: 0 mbps
Total outgoing traffic: 0 mbps
Total incoming pps: 23 packets per second
Total outgoing pps: 0 packets per second
Total incoming flows: 23 flows per second
Total outgoing flows: 0 flows per second
Average incoming traffic: 0 mbps
Average outgoing traffic: 0 mbps
Average incoming pps: 23 packets per second
Average outgoing pps: 0 packets per second
Average incoming flows: 23 flows per second
Average outgoing flows: 0 flows per second
Incoming ip fragmented traffic: 0 mbps
Outgoing ip fragmented traffic: 0 mbps
Incoming ip fragmented pps: 0 packets per second
Outgoing ip fragmented pps: 0 packets per second
Incoming tcp traffic: 0 mbps
Outgoing tcp traffic: 0 mbps
Incoming tcp pps: 11 packets per second
Outgoing tcp pps: 0 packets per second
Incoming syn tcp traffic: 0 mbps
Outgoing syn tcp traffic: 0 mbps
Incoming syn tcp pps: 0 packets per second
Outgoing syn tcp pps: 0 packets per second
Incoming udp traffic: 0 mbps
Outgoing udp traffic: 0 mbps
Incoming udp pps: 11 packets per second
Outgoing udp pps: 0 packets per second
Incoming icmp traffic: 0 mbps
Outgoing icmp traffic: 0 mbps
Incoming icmp pps: 0 packets per second
Outgoing icmp pps: 0 packets per second

Network: 10.10.10.2/32
Network incoming traffic: 0 mbps
Network outgoing traffic: 0 mbps
Network incoming pps: 24 packets per second
Network outgoing pps: 0 packets per second
Average network incoming traffic: 0 mbps
Average network outgoing traffic: 0 mbps
Average network incoming pps: 23 packets per second
Average network outgoing pps: 0 packets per second
Average packet size for incoming traffic: 61.5 bytes
Average packet size for outgoing traffic: 0.0 bytes
Incoming

TCP flows: 12
10.10.10.2:0 < 23.144.32.37:2084 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2085 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2086 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2087 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2088 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2089 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2090 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2091 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2092 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2093 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2094 60 bytes 1 packets
10.10.10.2:0 < 23.144.32.37:2095 60 bytes 1 packets

UDP flows: 12
10.10.10.2:0 < 92.168.20.20:2623 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2624 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2625 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2626 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2627 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2628 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2629 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2630 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2631 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2632 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2633 60 bytes 1 packets
10.10.10.2:0 < 92.168.20.20:2634 60 bytes 1 packets

what's the problem??!

**Comment by pavel-odintsov** [comment]
Are you using latest version from git? Please upgrade.  Old version has bugs with per protocol counters.

**Comment by mahdi1001** [comment]
My fastnetmon was updated.
I get it at 2 days ago.
Last code edit for 14 days ago.

**Comment by pavel-odintsov** [comment]
Nothing about bug here.

Just check your configuration:
```bash
threshold_tcp_pps = 10
```
And you have more than 10 pps:
```bash
Incoming tcp pps: 11 packets per second
```

It working as expected.

**Comment by mahdi1001** [comment]
OK, but in detail file show UDP flows: 12.
why show the UDP flows???

**Comment by pavel-odintsov** [comment]
It show they because you have UDP flows. It show all traffic (normal + malicious)
