### ISSUE TITLE
Email Attack

### ISSUE THREAD

**Issue by cpn76** [pavel-odintsov/fastnetmon#500]
I'm using fastnetmon to 6 months and this funcinando well ! But in some cases attacks it does not send a second email with details of the attack. What could be ? My version is 1.1.3

is an example of the received email:

Attack type: unknown
Initial attack power: 1680827 packets per second
Peak attack power: 1680827 packets per second
Attack direction: outgoing
Attack protocol: tcp
Total incoming traffic: 0 mbps
Total outgoing traffic: 4397 mbps
Total incoming pps: 0 packets per second
Total outgoing pps: 1680827 packets per second
Total incoming flows: 0 flows per second
Total outgoing flows: 0 flows per second
Average incoming traffic: 0 mbps
Average outgoing traffic: 4397 mbps
Average incoming pps: 0 packets per second
Average outgoing pps: 1680827 packets per second
Average incoming flows: 0 flows per second
Average outgoing flows: 0 flows per second
Incoming ip fragmented traffic: 0 mbps
Outgoing ip fragmented traffic: 0 mbps
Incoming ip fragmented pps: 0 packets per second
Outgoing ip fragmented pps: 0 packets per second
Incoming tcp traffic: 0 mbps
Outgoing tcp traffic: 0 mbps
Incoming tcp pps: 0 packets per second
Outgoing tcp pps: 0 packets per second
Incoming syn tcp traffic: 0 mbps
Outgoing syn tcp traffic: 0 mbps
Incoming syn tcp pps: 0 packets per second
Outgoing syn tcp pps: 0 packets per second
Incoming udp traffic: 0 mbps
Outgoing udp traffic: 0 mbps
Incoming udp pps: 0 packets per second
Outgoing udp pps: 0 packets per second
Incoming icmp traffic: 0 mbps
Outgoing icmp traffic: 0 mbps
Incoming icmp pps: 0 packets per second
Outgoing icmp pps: 0 packets per second

Average packet size for incoming traffic: 0.0 bytes 
Average packet size for outgoing traffic: 342.9 bytes

**Comment by pavel-odintsov** [comment]
Hello!

It could occur if your attack is enough slow and we could not collect required amount of packets (500 by default). You could try to decrease number of collected packets with option: ban_details_records_count.

**Comment by cpn76** [comment]
Thanks Pavel. 

My options ban_details_records_count was 1000, I change for 100.

**Comment by pavel-odintsov** [comment]
Yep, good idea!
