### ISSUE TITLE
исключение сетей из анализа

### ISSUE THREAD

**Issue by ugenk** [pavel-odintsov/fastnetmon#506]
Добрый день!

У нас в стране есть два типа каналов - местный, пиринговый, дешевый, и дорогой внешний.
Список сетей в пиринге заранее известен.

Можно ли настроить fastnetmon таким образом, что бы при анализе трафика, трафик из пиринговых сетей не анализировался? Либо анализировался по другим правилам?

Поясню на примере: PPS 50k из/в интернет - это DDOS, а PPS 50k в пиринг - это нормальная рабочая ситуация.

**Comment by pavel-odintsov** [comment]
Приветствую

Вайтлистинга по destination сетям как такового нету, но можно попробовать
фильтровать нетфлоу/сфлоу до момента пока он доберется до FNM.

Есть возможность писать фильтры (sflow/netflow) на lua, но там весьма
проблемно со стабильностью - не у всех работает.

On Thursday, 7 April 2016, ugenk <notifications@github.com> wrote:

> Добрый день!
>
> У нас в стране есть два типа каналов - местный, пиринговый, дешевый, и
> дорогой внешний.
> Список сетей в пиринге заранее известен.
>
> Можно ли настроить fastnetmon таким образом, что бы при анализе трафика,
> трафик из пиринговых сетей не анализировался? Либо анализировался по другим
> правилам?
>
> Поясню на примере: PPS 50k из/в интернет - это DDOS, а PPS 50k в пиринг -
> это нормальная рабочая ситуация.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/506>
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by ugenk** [comment]
Спасибо  за совет, так и сделали - убрали лишние интерфейсы, оставили только внешние каналы в netflow.

Вообще, если думать над этой идеей - было бы супер добавить фильтр даже не по IP-сетям, а по AS Path (выгружать по bgp routing table, и по заданным as path убирать сети из анализа)

**Comment by pavel-odintsov** [comment]
Была такая мысль, но форматы выгрузки bgp full view очень не универсальны межлу роутинг демонами и какой-то общий протокол / формат отсутствует...

**Comment by ugenk** [comment]
Можно сделать, как это сделал pmacctd - они просто откусили кусок от какого-то bgp-демона, и встроили себе. Либо заточиться на конкретный bgp-демон.

**Comment by pavel-odintsov** [comment]
Но это все равно очень специфичная задачка, это скорее задача для софта класса pmacct - аггрегатора трафика с возможностью выборки. Я думаю над тем, чтобы сделать такой слой (опционально) для FNM и на нем осуществлять гибкую фильтрацию трафика, но вот для целей ддос митигации - эта задачка довольно редкая, имхо, лучше сделать белый список по destination сетям и забивать туда неугодные сети вручную / выгрузкой с BGP демона :)

**Comment by ugenk** [comment]
да :)

**Comment by pavel-odintsov** [comment]
Actually it's duplicate of https://github.com/pavel-odintsov/fastnetmon/issues/564
