### ISSUE TITLE
ban_for_bandwidth not working

### ISSUE THREAD

**Issue by paracusia** [pavel-odintsov/fastnetmon#507]
Hi,

its not banning with these settings:

# Different approaches to attack detection
ban_for_pps = on
ban_for_bandwidth = on
ban_for_flows = off

# Limits for Dos/DDoS attacks
threshold_pps = 12000000
threshold_mbps = 1000
threshold_flows = 3500

I can see more than 1000mbps in the client, is that a bug?

thank you beforehand!

paracusia

**Comment by pavel-odintsov** [comment]
Hello!

Looks like you have global trigger about ban actions disabled.


Make sure you have following:


# Enable/Disable any actions in case of attack
enable_ban = on

On Friday, 8 April 2016, paracusia <notifications@github.com> wrote:

> Hi,
>
> its not banning with these settings:
> Different approaches to attack detection
>
> ban_for_pps = on
> ban_for_bandwidth = on
> ban_for_flows = off
> Limits for Dos/DDoS attacks
>
> threshold_pps = 12000000
> threshold_mbps = 1000
> threshold_flows = 3500
>
> I can see more than 1000mbps in the client, is that a bug?
>
> thank you beforehand!
>
> paracusia
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/507>
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by paracusia** [comment]
thanks you were right :-)

**Comment by pavel-odintsov** [comment]
Awesome!
