### ISSUE TITLE
[FR] Per prefix thresholds

### ISSUE THREAD

**Issue by winkmichael** [pavel-odintsov/fastnetmon#508]
Hello Pavel,

Loving Fastnetmon, great work. One thing that we keep coming across is the idea of having per prefix thresholds. We have a great many prefixes and sure would love the option of having triggers hit at different points depending on the prefix, and ideally different scripts to be run depending on the prefix or allow the prefix to be passed to the script instead of just the /32.

Thanks for your time!

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for your contribution! I already have idea for per subnet counters.
And it could be implemented with more common approach.

As option we coukd summarize all traffic for certain hostgroup and trigger
attack notification when whole hostgroup exceed limits.

On Wednesday, 27 April 2016, winkmichael <notifications@github.com> wrote:

> Hello Pavel,
>
> Loving Fastnetmon, great work. One thing that we keep coming across is the
> idea of having per prefix thresholds. We have a great many prefixes and
> sure would love the option of having triggers hit at different points
> depending on the prefix, and ideally different scripts to be run depending
> on the prefix or allow the prefix to be passed to the script instead of
> just the /32.
>
> Thanks for your time!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/508>
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by Wintereise** [comment]
+1 for this one, did you get a moment to look Pavel?

**Comment by pavel-odintsov** [comment]
Hello!

That's really hard to implement with current design, really.

**Comment by pavel-odintsov** [comment]
Hello!

Community edition got this feature years ago. Please check "hostgroup" section in configuration file.
