### ISSUE TITLE
Host groups, filtering

### ISSUE THREAD

**Issue by kszysiu94** [pavel-odintsov/fastnetmon#509]
Hello

I think that it would be nice to have functionality to group servers by network speed.

For example we can create two groups - one would be default and have 100mb/100kpps limit and second (declared list of ips like in white-list) with for example 1000mb/1mpps limits. Different settings for incoming and outgoing traffic would be nice too...

It would be nice to have ability to filter packets by some fields like subnet, vlans etc. I have links in switch with few vlans, and i would like to get only traffic from one vlan(by sflow), but i can't do this... in some cases same packet goes trough both vlans, so i see 2 times more bandwidth than i should...

Sorry for my English if its bad.

Regards
Krzysztof

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for feedback!

We already have lua bindings for traffic filtering by separate fileds. Just
check lua hooks for sflow and netflow.

Separate limits for incoming and outgoing are already in issues and we have
some ideas about it.

On Wednesday, 27 April 2016, kszysiu94 <notifications@github.com> wrote:

> Hello
>
> I think that it would be nice to have functionality to group servers by
> network speed.
>
> For example we can create two groups - one would be default and have
> 100mb/100kpps limit and second (declared list of ips like in white-list)
> with for example 1000mb/1mpps limits. Different settings for incoming and
> outgoing traffic would be nice too...
>
> It would be nice to have ability to filter packets by some fields like
> subnet, vlans etc. I have links in switch with few vlans, and i would like
> to get only traffic from one vlan(by sflow), but i can't do this... in some
> cases same packet goes trough both vlans, so i see 2 times more bandwidth
> than i should...
>
> Sorry for my English if its bad.
>
> Regards
> Krzysztof
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/509>
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by kszysiu94** [comment]
Is there any documentation how to use lua hooks?

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately there are no doc about it. But we have examples https://github.com/pavel-odintsov/fastnetmon/blob/master/src/netflow_hooks.lua and https://github.com/pavel-odintsov/fastnetmon/blob/master/src/sflow_hooks.lua
