### ISSUE TITLE
Ошибка сборки Dev версии на FreeBSD 10.2

### ISSUE THREAD

**Issue by lerkh-d** [pavel-odintsov/fastnetmon#510]
При сборке обычной версии FastnetMon 1.1.2, без ошибок, но в логах после запуска демона такая ошибка.

```
2016-04-28 11:34:19,007 [INFO] Time from last run of speed_recalc is soooo big, we got ugly lags: 2
2016-04-28 11:34:39,026 [INFO] Time from last run of speed_recalc is soooo big, we got ugly lags: 2

```

Dev же версия собирается с ошибкой.

[http://pastebin.com/raw/rfK6QVZJ](url)

Собирать из исходников что либо приходилось редко, не могу разобраться с ошибкой.

**Comment by pavel-odintsov** [comment]
Добрый день

Это не ошибка, ее можно игнорировать. По поводу сборки - под Фрей дев версия не собирается, простите, только Linux, там много вещей, которых во Фре нету и очень-очень-очень мало юзеров, кто использует Фрю, поэтому она по тстаточнмоу принципу.

**Comment by lerkh-d** [comment]
Понятно, новые "свистелки" только для linux.

Спасибо. =)
