### ISSUE TITLE
Problem with templates in influxdb integration

### ISSUE THREAD

**Issue by cristianbarbaro** [pavel-odintsov/fastnetmon#511]
Hello,  I'm trying to execute and integrate `fastnetmon` with `influxdb` and templates **hosts**, **networks** and **total** doesn't create. 
I followed the instructions in [INFLUXDB_INTEGRATION.md](https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/INFLUXDB_INTEGRATION.md). but when I execute `show measurements` I see: 

```
name
fastnetmon.172_17_0_2.incoming.flows
fastnetmon.172_17_0_2.incoming.mbps
fastnetmon.172_17_0_2.incoming.pps
fastnetmon.172_17_0_2.outgoing.flows
fastnetmon.172_17_0_2.outgoing.mbps
fastnetmon.172_17_0_2.outgoing.pps
fastnetmon.incoming.mbps
fastnetmon.incoming.pps
fastnetmon.incomingflows
fastnetmon.outgoing.mbps
fastnetmon.outgoing.pps
fastnetmon.outgoingflows
```

This is my configuration (into Docker container):

* /etc/fastnetmon.conf:

```
# Graphite monitoring
graphite = on
graphite_host = 127.0.0.1
graphite_port = 2003
graphite_prefix = fastnetmon
```

* /etc/influxdb/influxdb.conf:

```
[[graphite]]
  enabled = true
  database = "graphite"
  bind-address = ":2003"
  protocol = "tcp"
  consistency-level = "one"
  name-separator = "."

  batch-size = 5000 # will flush if this many points get buffered
  batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit

  templates = [
    "fastnetmon.hosts.* app.measurement.cidr.direction.function.resource",
    "fastnetmon.networks.* app.measurement.cidr.direction.resource",
    "fastnetmon.total.* app.measurement.direction.resource"
  ]
```

Sorry for my english.
Thank you. Regards.

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately, I do not use InfluxDB and could not help here. Please ask at mail list instead. We have few users who uses it and could help

**Comment by cristianbarbaro** [comment]
Ok. Thank you.

**Comment by juesor** [comment]
Did you ever get an answer from the mail list and I to don't see networks.
> show measurements
name: measurements
------------------
name
hosts
total

**Comment by cristianbarbaro** [comment]
Fixed in this version. I don't know how but it works :D

Thanks for this.

**Comment by chasgames** [comment]
I don't see "networks" either in measurements, what was the fix?

**Comment by holywyvern** [comment]
We are having exactly the same problem as chasgames, is there a bug on the networks template or something bad about the demo ?

Our configuration is exactly as the example:

```
  templates = [
    "fastnetmon.hosts.* app.measurement.cidr.direction.function.resource",
    "fastnetmon.networks.* app.measurement.cidr.direction.resource",
    "fastnetmon.total.* app.measurement.direction.resource"
  ]
```
Yet when we do a "show measurements" query it returns:

hosts
total

**Comment by pavel-odintsov** [comment]
If you want per-network stats you should enable this option in FastNetMon configuration: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/fastnetmon.conf#L37

**Comment by chasgames** [comment]
Thanks can see the network series now

**Comment by pavel-odintsov** [comment]
welcome :)
