### ISSUE TITLE
Сильно нагружено одно ядро CPU

### ISSUE THREAD

**Issue by zar1n** [pavel-odintsov/fastnetmon#513]
Приветствую. И спасибо за отличную разработку :)
При внедрении столкнулся проблемой высокой загрузки одного ядра CPU. Соответственно, как только загрузка приближается к 100%, начинаются дропы.

Трафик (одно ядро ~70%, остальные ~8%): 
`Incoming traffic        430389 pps   3552 mbps      0 flows`

Это 1/3 входящего трафика, полученная путем собирания из 4-x 10GE интерфейсов при помощи zbalance (zbalance_ipc -i zc:eth4,zc:eth5,zc:eth6,zc:eth7 -c 1 -n 3).

Процессоры:
`Model name:            Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz`

Сетевые карты:
`Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)`

Используется PF_RING ZC (лицензии есть). Версия PF_RING 6.3. (начинал тесты с 6.0.3, ситуация та же)
Жизненно важные параметры конфигурации выглядят следующим образом:

```
process_incoming_traffic = on
process_outgoing_traffic = off

enable_subnet_counters = off

check_period = 1

enable_connection_tracking = off

mirror = on
pfring_sampling_ratio = 1
enable_pf_ring_zc_mode = on
interfaces = zc:1@0
```

В networks_list, 5 крупных сетей, в среднем /21 префикс.
Ссылка на запись профилировщика - https://www.dropbox.com/s/q8l123perwwiurv/perf.data?dl=0

Спасибо.

**Comment by pavel-odintsov** [comment]
Приветствую!

Сапсибо за приятный фидбэк!

А почему не обойтись  без zbounce и не прописать все zc интерфейсы явно в FNM? Тогда можно будет понимать, почему идет перекос и по какой карте.

**Comment by zar1n** [comment]
Добрый день, Павел. 
Если указать в конфигурации FNM более одного zc интерфейса. FNM не запускается с ошибкой:

```
2016-05-23 10:10:46,302 [ERROR] pfring_zc_open_device error Socket operation on non-socket Please check that device is up and not already used
2016-05-23 10:10:46,302 [ERROR] PF_RING initilization failed, exit from programm
```

Параметр конфигурации выглядит следующим образом:

`interfaces = zc:eth4,zc:eth5`

**Comment by pavel-odintsov** [comment]
Похоже, да, так и есть. 

Я в свое время так и не дописал этот код:
````bash
// TODO: add support for multiple devices!
    u_int32_t num_devices = 1;
```

Да, тогда только zbounce либо использовать netmap, для него точно держится несколько ифейсов.

**Comment by zar1n** [comment]
Павел, добавить возможность работы с несколькими ZС интерфейсами в ближайших планах случаем нет ? :) 

Просмотрел все возможные варианты с zbalance, многопоточности  у него нет. Да и вообще, это по большей части пример.

**Comment by pavel-odintsov** [comment]
PF_RING - платный продукт, очень немногие готовы выбросить на него 250 евро за лицензию. Поэтому планов нету, netmap на мой взгляд более интересен и предоставляет идентичный по скорости функционал, но несколько более сложен в сборке. Хотя на Фре он искаропки.

**Comment by zar1n** [comment]
Можно закрывать. Перешел на netmap. Купленные лицензии использую потом для suricata :)
Спасибо.

**Comment by pavel-odintsov** [comment]
Вполне нормальное :) Один поток - это скорее калькулятор скоростей потоков, если сетей много - это нормально, что он грузит. 

Нужно смотреть успеевает ли он, покажите выдачу клиента на тему времени расчета скоростей.

**Comment by zar1n** [comment]
```
Screen updated in:              0 sec 3073 microseconds
Traffic calculated in:          0 sec 5719 microseconds
```

При:

```
Incoming traffic        1530351 pps  12619 mbps      0 flows
Outgoing traffic        1155612 pps   3205 mbps      0 flows
```

**Comment by pavel-odintsov** [comment]
Первое ядро в полку потому что на нем прерывания, их нужно размазать по ядрам равномерно. Попробуйте поставить birq для этой задачи и нагрузка распределится равномерно и не будет ядер в полку.

**Comment by zar1n** [comment]
Павел, установил irqbalance. 

Ситуация сразу стала лучше. Трафик стал реальным. :
```
Incoming traffic        2146699 pps  17762 mbps      0 flows
Outgoing traffic        1631776 pps   4441 mbps      0 flows
```
Время расчета выросло, но похоже это нормально.
```
Screen updated in:              0 sec 4103 microseconds
Traffic calculated in:          0 sec 15047 microseconds
```
Но ядра с 17 по 24 простаивают, как на прикрепленной картинке. По остальным нагрузка размазалась равномерно. Это нормально ?

Спасибо.

**Comment by pavel-odintsov** [comment]
Да, нормально.  1 поток на 1 очередь сетевой. Можете увеличить число RSS очередей. Для оперативности можете меня добавить в скайпе - energy_true.

**Comment by zar1n** [comment]
Павел, спасибо. Завтра поменяю параметры RSS, по результатам напишу )

**Comment by zar1n** [comment]
Павел, добрый день. Посмотрел, драйвера ixgbe не умеет больше чем 16 очередей.
Возможно одно из решений, выключить HT и сделать 12 очередей. В системе 12 реальных ядер.
Или сделать по 6 очередей и попытаться растянуть их по порядку на 24-ядра.

**Comment by pavel-odintsov** [comment]
Да, неплохая идея :)

**Comment by pavel-odintsov** [comment]
Finally, I think that original issue was solved :)
