### ISSUE TITLE
fastnetmon CLI arguments not working

### ISSUE THREAD

**Issue by sielpower** [pavel-odintsov/fastnetmon#518]
freshly built fastnetmon and it doesn't seem to read the arguments passed to the program.

I need to run multiple instances and I'm not able to do so.

./fastnetmon --configuration_file=/etc/fastnetmon-six.conf
Can't open config file /etc/fastnetmon.conf, please create it!
./fastnetmon --version
Can't open config file /etc/fastnetmon.conf, please create it!

**Comment by pavel-odintsov** [comment]
Hello!

Please install git version with following command:
```bash
wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl --use-git-master
```

**Comment by sielpower** [comment]
Awesome. Thanks a lot, where should I send cookies to ?

And Thanks for a great product. Please don't stop supporting it :)

**Comment by pavel-odintsov** [comment]
You are welcome! :)
