### ISSUE TITLE
Can't download PF_RING sources

### ISSUE THREAD

**Issue by quickpacket** [pavel-odintsov/fastnetmon#519]
When trying to install:

> Install PF_RING dependencies with package manager
> Download PF_RING 6.0.3 sources
> Downloaded archive has incorrect sha1: 2210478ecb07929fb362a81fa87e81c8e567533d expected: 9fb8080defd1a079ad5f0097e8a8adb5bc264d00
> Can't download PF_RING sources

The installer exits at this point and cannot proceed any further.

This is on CentOS 6 64-bit using the standard install:

> wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
> perl fastnetmon_install.pl

**Comment by pavel-odintsov** [comment]
You could try to ask PF_RING guys about this issue and why they have changed sources for old stable version. But this songs dangerous.

**Comment by pavel-odintsov** [comment]
I have downloaded PF_ring manually from the URL https://github.com/ntop/PF_RING/archive/v6.0.3.tar.gz 

Main URL is: https://github.com/ntop/PF_RING/releases

Amd then I've calculalated SHA1 for it:
```9fb8080defd1a079ad5f0097e8a8adb5bc264d00  PF_RING-6.0.3.tar.gz```

As you can see checksumm is correct and equal to checksumm hardcoded in installer.

Looks like your ISP fakes your download or broke they, please be careful.
