### ISSUE TITLE
Install failed because of LUA json module

### ISSUE THREAD

**Issue by quickpacket** [pavel-odintsov/fastnetmon#520]
Looks like sha1 has changed:

> Install LUA json module
> Download archive
> Downloaded archive has incorrect sha1: fca38ac28a7cceb2aec88fcd75a70f1dc657ef91 expected: 53455f697c3f1d7cc955202062e97bbafbea0779
> Can't download lua json

**Comment by pavel-odintsov** [comment]
Same issue as  https://github.com/pavel-odintsov/fastnetmon/issues/519
