### ISSUE TITLE
Странная ситуация при использовании нескольких интерфейсов 

### ISSUE THREAD

**Issue by Anito23** [pavel-odintsov/fastnetmon#522]
Привет!!!

Наблюдаю очень странную картину. У нас скрипт fastnetmon смотрит за 5 интерфейсам, два из которых используют пропатченный драйвер igb, а три e1000e. Так вот, если в конфигурации fastnetmon указать сначала два интерфейса igb, а затем три интерфейса e1000e, трафик с igb не берется в расчет. 

К примеру, у нас есть 5 интерфейсов:

eth3,eth4 - используют igb драйвер
eth5,eth6,eth7 - используют драйвер.

Трафик со всех миррор портов приходит - проверили. 

Если указать в конфигурации "interfaces = eth3,eth4" или "interfaces = eth5,eth6,eth7", то мы видим трафик на этих интерфейсах в полном объеме. Так же, все работает нормально если указывать по одному интерфейсу.  А вот если указать, к примеру, "interfaces = eth3,eth4,eth5", то fastnetmon будет работать только с трафиком интерфейса eth5 (eth3 и eth4 он как будто не видит). Если указать "interfaces = eth5,eth3,eth4", то трафик с интерфейсов eth3 и eth4 берется в расчет, а с eth5 нет. 

К сожалению, igb драйвер патчитца только тот что идет в дистрибутиве Debian 8. Компиляции обоих патченных драйверов igb, которые есть в гит igb-linux-netmap по инструкции http://www.stableit.ru/2014/10/netmap-debian-7-wheezy-intel-82599.html с корректировками под igb, заканчивается ошибкой. 

Драйвер же e1000e компилируется без проблем, даже актуальный с https://sourceforge.net/projects/e1000/files/.

**Comment by Anito23** [comment]
Еще добавлю. 

К примеру, сейчас провел еще один тест. 

Установил "interfaces = eth3,eth4,eth5" и запустил fastnetmon. Трафик начало показывать в районе 20Мбит. На свиче отключил порт к которому подключен интерфейс eth5. Трафик просел до 0Мбит и 100-200 пакетов. При том, что на портах свича к которым подключены интерфейсы eth3 и eth4 регистрируется более 2000 пакетов и около 40Мбит. 
Т.е. получается что скрипт видит трафик с интерфейсов eth3 и eth4, но учитывает только малую часть трафика.

**Comment by pavel-odintsov** [comment]
Ой какой баг. Слушай, даже не знаю почему так. Из-за кода прибивания
процессов к ядрам может не хвататься потоков на все ядра, но вроде у меня
там случай когда суммарное число очередей сетевых в системе больше числа
ядер.

On Wednesday, 22 June 2016, Anito23 <notifications@github.com> wrote:

> Еще добавлю.
>
> К примеру, сейчас провел еще один тест.
>
> Установил "interfaces = eth3,eth4,eth5" и запустил fastnetmon. Трафик
> начало показывать в районе 20Мбит. На свиче отключил порт к которому
> подключен интерфейс eth5. Трафик просел до 0Мбит и 100-200 пакетов. При
> том, что на портах свича к которым подключены интерфейсы eth3 и eth4
> регистрируется более 2000 пакетов и около 40Мбит.
> Т.е. получается что скрипт видит трафик с интерфейсов eth3 и eth4, но
> учитывает только малую часть трафика.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/522#issuecomment-227743239>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZgdIDvl6IEIZHUvgTFoIaktJz3tiks5qOTiOgaJpZM4I7w-W>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by Anito23** [comment]
На сервере на котором зафиксировали этот баг стоит процессор с 4 ядрами без HT Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz. Так что, ядер точно не больше числа потоков.

**Comment by pavel-odintsov** [comment]
Попробуй как вариант вырубить RSS, чтобы каждая сетевая юзала не более 1го
процесса.

2016-06-22 22:56 GMT-07:00 Anito23 <notifications@github.com>:

> На сервере на котором зафиксировали этот баг стоит процессор с 4 ядрами
> без HT Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz. Так что, ядер точно не
> больше числа потоков.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/522#issuecomment-227957057>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZonA9kJH965QPs4tiTOBLpEqxGd2ks5qOh_-gaJpZM4I7w-W>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by Anito23** [comment]
Похоже ты прав и проблема связана с прерываниями. 

Сейчас я видел это наглядно. Просмотрел прерывания в /proc/interrupts для всех сетевых карт и заметил что для сетевых igb их как то маловато, по сравнению с e1000e, при том что сейчас идет трафик в 150Мбит и 5К пакетов по одному из igb интерфейсов. При этом счетчик у igb увеличивается очень медленно. 
Далее, я останавливаю работу скрипта fastnetmon и смотрю изменения в /proc/interrupts. Счетчики igb интерфейсов начинают увеличиваться как угорелые. Как только включаю fastnetmon счетчики прерываний опять еле живые.

**Comment by Anito23** [comment]
Вот прикол. Могу точно сказать, что на igb интерфейсах в момент работы скрипта fastnetmon регистрируется ровно одно прерывание (на интерфейс) в секунду.

**Comment by pavel-odintsov** [comment]
Возможно, это ожидаемо. Просто они отключаются от стека, когда включается нетмап.

**Comment by Anito23** [comment]
К сожалению, думаю что нет. Так как, на интерфейсах e1000e при включении fastnetmon ничего не меняется - прерывания как прибавлялись тысячами так и прибавляются. 
Тоже самое вижу и при использовании ixgbe интерфейсов - так же в момент включенного fastnetmon прерывания увеличиваются с той же скоростью, что и в момент выключенного fastnetmon.

**Comment by pavel-odintsov** [comment]
Загадка. Может быть патч не встал и захват не включается?

2016-06-22 23:44 GMT-07:00 Anito23 <notifications@github.com>:

> К сожалению, думаю что нет. Так как, на интерфейсах e1000e при включении
> fastnetmon ничего не меняется - прерывания как прибавлялись тысячами так и
> прибавляются.
> Тоже самое вижу и при использовании ixgbe интерфейсов - так же в момент
> включенного fastnetmon прерывания увеличиваются с той же скоростью, что и в
> момент выключенного fastnetmon.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/522#issuecomment-227963754>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZplVQUILgqYq0iUOczUkSiXofuVjks5qOitBgaJpZM4I7w-W>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Все же я грешу на код развешивания... Кривой он когда несколько сетевых: We have number of CPUs bigger than number of NIC RX queues. Set number of CPU's to number of threads

**Comment by Anito23** [comment]
Сейчас сделал небольшой тест. 

Сначала выставил "interfaces = eth3,eth4" и запустил fastnetmon. В /proc/interrupts видно, что прерывания на igb интерфейсах eth3 и eth4 увеличиваются на тысячи. 

Затем выставил "interfaces = eth3,eth4,eth5" и перезапустил fastnetmon. В /proc/interrupts видно, что прерывания на igb интерфейсах eth3 и eth4 увеличиваются на единицу в секунду.  Что интересно, если разбить сетевые очереди по ядрам процессора (4 очереди по 4 ядрам), то прерывания увеличиваются на 1 в секунду на всех 4 ядрах. То есть, на всех четырех сетевых очередях срабатывает по одному прерыванию в секунду. А если загрузить igb драйвер только с одной сетевой очередью, то в секунду добавляется 1 прерывание к одной сетевой очереди. 

Таже картина наблюдается если выставить только два интерфейса "interfaces = eth3,eth5". При этом, на igb интерфейсе прерывания увеличиваются на 1 в секунду.

**Comment by pavel-odintsov** [comment]
Может попробуешь на AF_PACKET запуститься? Я не помню в каком он состоянии,
но вроде работать должен и не требует патченых дров в принципе.

2016-06-23 0:48 GMT-07:00 Anito23 <notifications@github.com>:

> Сейчас сделал небольшой тест.
>
> Сначала выставил "interfaces = eth3,eth4" и запустил fastnetmon. В
> /proc/interrupts видно, что прерывания на igb интерфейсах eth3 и eth4
> увеличиваются на тысячи.
>
> Затем выставил "interfaces = eth3,eth4,eth5" и перезапустил fastnetmon. В
> /proc/interrupts видно, что прерывания на igb интерфейсах eth3 и eth4
> увеличиваются на единицу в секунду. Что интересно, если разбить сетевые
> очереди по ядрам процессора (4 очереди по 4 ядрам), то прерывания
> увеличиваются на 1 в секунду на всех 4 ядрах. То есть, на всех четырех
> сетевых очередях срабатывает по одному прерыванию в секунду. А если
> загрузить igb драйвер только с одной сетевой очередью, то в секунду
> добавляется 1 прерывание к одной сетевой очереди.
>
> Таже картина наблюдается если выставить только два интерфейса "interfaces
> = eth3,eth5". При этом, на igb интерфейсе прерывания увеличиваются на 1 в
> секунду.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/522#issuecomment-227975219>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZlNAncEnW9fEt12nVexmTKeywjnuks5qOjpjgaJpZM4I7w-W>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by Anito23** [comment]
Поподробнее про AF_PACKET можно?

**Comment by pavel-odintsov** [comment]
Оно стандартно собирается, конфигурится ровно также, просто mirror_afpacket
= on и поперли) Ни патчей, ничего не требуется, работает на обычном ядре.
Но там код может быть кривой....

On Thu, Jun 23, 2016 at 12:54 AM, Anito23 <notifications@github.com> wrote:

> Поподробнее про AF_PACKET можно?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/522#issuecomment-227976368>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZlbHUsspkGSu8HmECcQVV5y4Rm3Uks5qOjuzgaJpZM4I7w-W>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by Anito23** [comment]
Персобрал актуальную версию fastnetmon. Скомпилировал драйвера с соруфорджа для igb и e1000e. Включил mirror_afpacket. С исходящим трафиком картина улутшилась - его стало больше фиксироваться. А вот входящий почти пропал 0 Мбит при реальных 5Мбитах. 

Ладно заменим e1000e интерфейсы на igb. Так как есть такая возможность. Потом сообщу поможет ли это.

**Comment by Anito23** [comment]
Спасибо за помощь.

**Comment by Anito23** [comment]
Времено включил PF_RING. С ним трафик фиксируется корректно.

**Comment by pavel-odintsov** [comment]
Отличная идея)

On Thursday, 23 June 2016, Anito23 <notifications@github.com> wrote:

> Времено включил PF_RING. С ним трафик фиксируется корректно.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/522#issuecomment-228002144>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZlQZBTXZ3xdU1b4J3-24CPLzgrpTks5qOlZrgaJpZM4I7w-W>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
Кстати, а что в дмесге? У нетмапа есть лими на число буферов. Мб их не
хватало?)

On Thursday, 23 June 2016, Pavel Odintsov <pavel.odintsov@gmail.com> wrote:

> Отличная идея)
>
> On Thursday, 23 June 2016, Anito23 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Времено включил PF_RING. С ним трафик фиксируется корректно.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pavel-odintsov/fastnetmon/issues/522#issuecomment-228002144>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ACnfZlQZBTXZ3xdU1b4J3-24CPLzgrpTks5qOlZrgaJpZM4I7w-W>
>> .
>>
>
>
> --
> Sincerely yours, Pavel Odintsov
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by Anito23** [comment]
Привет!!!

Проблема решилась заменой сетевой карты использующей драйвера e1000e и установкой сетевой карты использующей драйвера igb. Т.е. теперь все 5 интерфейсов использую пропатченный igb драйвер.

Все таки, есть подозрение, что не корректно работало из-за одновременного использования пропатченных драйверов e1000e и igb.

Спасибо за помощь.
