### ISSUE TITLE
Support SNMP monitoring

### ISSUE THREAD

**Issue by melsom** [pavel-odintsov/fastnetmon#523]
Hello,

Is it easy to include something like SMTP-monitoring for sent emails or SMTP connections in addition to PPS and MBps? Basically monitor connections to port 25. We're finding it difficult sourcing software which easily lets us monitor SMTP traffic to block spammers in our network.

A feature like this would be greatly appreciated. Could include some form of limit in the configuration, trigger at e.x 50 connections per second.

**Comment by pavel-odintsov** [comment]
Helllo

Unfortunately, it's out of scope for DDoS mitigation toolkit. I like rhis
idea but it's suitable only for another toolkit.

On Thursday, 23 June 2016, Andreas Melsom Haakonsen <
notifications@github.com> wrote:

> Hello,
>
> Is it easy to include something like SMTP-monitoring for sent emails or
> SMTP connections in addition to PPS and MBps? Basically monitor connections
> to port 25. We're finding it difficult sourcing software which easily lets
> us monitor SMTP traffic to block spammers in our network.
>
> A feature like this would be greatly appreciated. Could include some form
> of limit in the configuration, trigger at e.x 50 connections per second.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/523>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ACnfZkZoGeqa6MqAowpli32AfurnY1emks5qOohwgaJpZM4I8zWm>
> .
>


-- 
Sincerely yours, Pavel Odintsov
