### ISSUE TITLE
Wrong src_ip reported for incoming attack

### ISSUE THREAD

**Issue by ldep30** [pavel-odintsov/fastnetmon#525]
Hello,

I'm currently trying Fastnetmon on a Debian Jessie box (VM). I use the ipt_NETFLOW module with iptables, which works fine. Fastnetmon is configured to just use the Netflow input plugin.

Here is my lab network setup (fake public IP addresses are used) :

Box 1 (running Fastnetmon) : 66.66.66.66/24
Box 2 (DDoS simulation) : 66.66.66.67/24

In order to simulate a small DDoS attack, I use hping3 on Box 2 :
`hping3 66.66.66.66 -p 766 --udp --faster --spoof 54.87.65.32`

When running Fastnetmon like that :
`DUMP_ALL_PACKETS=true /opt/fastnetmon/fastnetmon`

I get this result in the log file which confirms correct Netflow "interception" :
`2016-06-24 17:52:56,621 [INFO] Dump: 2016-06-24 17:52:56.620696 54.87.65.32:2871 > 66.66.66.66:766 protocol: udp frag: 0  packets: 1 size: 28 bytes sample ratio: 50`

However, Fastnetmon reports an incorrect source/incoming IP for the attack and seems to be using the destination address (66.66.66.66) instead :

```
FastNetMon v1.0 FastVPS Eesti OU (c) VPS and dedicated: http://FastVPS.host
IPs ordered by: packets
Incoming traffic             0 pps      0 mbps      0 flows
66.66.66.66              12536 pps      2 mbps     81 flows  *banned*

Outgoing traffic             0 pps      0 mbps      0 flows
66.66.66.66                  0 pps      0 mbps      0 flows  *banned*

Internal traffic             0 pps      0 mbps

Other traffic                0 pps      0 mbps

Screen updated in:              0 sec 217 microseconds
Traffic calculated in:          0 sec 7 microseconds
Total amount of not processed packets: 0

Ban list:
66.66.66.66/27904 pps incoming at 24_06_16_17:51:32
```
And the sample notify script sends :
`FastNetMon Guard: IP 66.66.66.66 blocked because incoming attack with power 23123 pps`

My networks_whitelist file is empty and networks_list contains 66.66.66.66/32. I've tried a lot of other options (66.66.66.0/24, and so on), but the result is always the same.

By looking at the [source code](https://github.com/pavel-odintsov/fastnetmon/blob/11522e4d905ca2bacb1510a107b7bd654f58016e/src/fastnetmon.cpp#L1961), I notice that current_packet.dst_ip is used for banning when packet direction is INCOMING.

Did I misunderstood something ?

Thanks for your help.

**Comment by pavel-odintsov** [comment]
Hello

We are _not_ banning remote attackers. We are banning our own host in the interest of whole DC reliability. 

So, I means it's by design.
