### ISSUE TITLE
The directory /var/log/fastnetmon_attacks is without any .pcap file

### ISSUE THREAD

**Issue by itsjoke** [pavel-odintsov/fastnetmon#526]
Hello

The directory /var/log/fastnetmon_attacks is without any .pcap file when I enable collect_attack_pcap_dumps  in /etc/fastnetmon.conf. How can I troubleshoot ?

regards
David

**Comment by pavel-odintsov** [comment]
Hi

What's your traffic information source?

On Saturday, 25 June 2016, itsjoke <notifications@github.com> wrote:

> Hello
>
> The directory /var/log/fastnetmon_attacks is without any .pcap file when I
> enable collect_attack_pcap_dumps in /etc/fastnetmon.conf. How can I
> troubleshoot ?
>
> regards
> David
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/526>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ACnfZmlU3ddiCCGV8lx5eEDmf9f5ZmoOks5qPUJUgaJpZM4I-XI6>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by itsjoke** [comment]
The source is Port mirror.

**Comment by pavel-odintsov** [comment]
Hi

Please share fastnetmon.log for investigation.

On Sunday, 26 June 2016, itsjoke <notifications@github.com> wrote:

> The source is Port mirror.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/526#issuecomment-228603852>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZp-dOpqPGwzmtlsu44S29-VbXchvks5qPovrgaJpZM4I-XI6>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by itsjoke** [comment]
Hi
for some reason, I replaced the ip address like "192.168.x.x".
[fastnetmon.txt](https://github.com/pavel-odintsov/fastnetmon/files/336111/fastnetmon.txt)

**Comment by pavel-odintsov** [comment]
Hi

Could not find something strange in your logs. This code is supposed to be
very buggy. Please check configuration and install latest version. If
configuration is OK I could not help you because for fixing this code we
need to rewrite it from scratch.

On Mon, Jun 27, 2016 at 6:43 PM, itsjoke <notifications@github.com> wrote:

> Hi
> for some reason, I replaced the ip address like "192.168.x.x".
> fastnetmon.txt
> <https://github.com/pavel-odintsov/fastnetmon/files/336111/fastnetmon.txt>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/526#issuecomment-228925876>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZoD5MKsPC4XSQw7eIbgJ8o3cROtqks5qQHxEgaJpZM4I-XI6>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by itsjoke** [comment]
Hi
I used the fastnetmon_install.pl to install latest fastnetmon ,could you help me check the configuration is correct?

* * *
    [root@Traffic ~]#      stat fastnetmon_install.pl 
      File: `fastnetmon_install.pl'
      Size: 51993           Blocks: 104        IO Block: 4096   regular file
    Device: 812h/2066d      Inode: 918074      Links: 1
    Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
    Access: 2016-06-24 16:30:04.553814335 +0800
    Modify: 2016-06-24 16:29:52.591414493 +0800
    Change: 2016-06-24 16:29:52.591414493 +0800
    [root@Traffic ~]# ll /opt/fastnetmon/fastnetmon
    -rwxr-xr-x 1 root root 828115 Jun 24 16:37 /opt/fastnetmon/fastnetmon
    [root@Traffic ~]# ll /opt/fastnetmonold/fastnetmon
    -rwxr-xr-x 1 root root 712861 Oct 14  2015 /opt/fastnetmonold/fastnetmon
* * *
[fastnetmon.conf](https://github.com/pavel-odintsov/fastnetmon/files/338492/fastnetmon.txt)

**Comment by pavel-odintsov** [comment]
Hello

Yes, it looks correct.

On Tue, Jun 28, 2016 at 8:24 PM, itsjoke <notifications@github.com> wrote:

> Hi
> I used the fastnetmon_install.pl to install latest fastnetmon ,could you
> help me check the configuration is correct?
> ------------------------------
>
> [root@Traffic ~]#      stat fastnetmon_install.pl
>   File: `fastnetmon_install.pl'
>   Size: 51993           Blocks: 104        IO Block: 4096   regular file
> Device: 812h/2066d      Inode: 918074      Links: 1
> Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
> Access: 2016-06-24 16:30:04.553814335 +0800
> Modify: 2016-06-24 16:29:52.591414493 +0800
> Change: 2016-06-24 16:29:52.591414493 +0800
> [root@Traffic ~]# ll /opt/fastnetmon/fastnetmon
> -rwxr-xr-x 1 root root 828115 Jun 24 16:37 /opt/fastnetmon/fastnetmon
> [root@Traffic ~]# ll /opt/fastnetmonold/fastnetmon
> -rwxr-xr-x 1 root root 712861 Oct 14  2015 /opt/fastnetmonold/fastnetmon
>
> ------------------------------
>
> fastnetmon.conf
> <https://github.com/pavel-odintsov/fastnetmon/files/338492/fastnetmon.txt>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/526#issuecomment-229246732>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZtHGoSW_8yR2tvWxmu_k0MTkzLzyks5qQeVQgaJpZM4I-XI6>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by itsjoke** [comment]
Hello

could you give me some advice and how to fix the issue?

**Comment by pavel-odintsov** [comment]
Hello

Unfortunately, I do not know how to fix it without hacking code.

This code works for me and it should work for you. But for some reasons
it's did not working with completely correct configuration.

On Tuesday, 28 June 2016, itsjoke <notifications@github.com> wrote:

> Hello
>
> could you give me some advice and how to fix the issue?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/526#issuecomment-229260590>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZqa_QiIXz6d_HdbDedib_iynww3Eks5qQgOCgaJpZM4I-XI6>
> .
>


-- 
Sincerely yours, Pavel Odintsov
