### ISSUE TITLE
what means "Limits for Dos/DDoS attacks"

### ISSUE THREAD

**Issue by shining-github** [pavel-odintsov/fastnetmon#527]
# Limits for Dos/DDoS attacks
threshold_pps = 20000
threshold_mbps = 1000
threshold_flows = 3500

This is for monitor ip **attacks traffic** or **all traffic** more than config to execute script?
Which of these configurations are in the mail?

IP: 111.1.1.2
Attack type: unknown
Initial attack power: 5427 packets per second
Peak attack power: 5427 packets per second
Attack direction: outgoing
Attack protocol: tcp
Network: 111.1.1.0/24
Network incoming traffic: 3 mbps
Network outgoing traffic: 0 mbps
Network incoming pps: 312 packets per second
Network outgoing pps: 308 packets per second
Average network incoming traffic: 469 mbps
Average network outgoing traffic: 407 mbps
Average network incoming pps: 94224 packets per second
Average network outgoing pps: 82861 packets per second
Total incoming traffic: 5 mbps
Total outgoing traffic: 22 mbps
Total incoming pps: 6247 packets per second
Total outgoing pps: 5427 packets per second
Total incoming flows: 0 flows per second
Total outgoing flows: 0 flows per second
Average incoming traffic: 5 mbps
Average outgoing traffic: 22 mbps
Average incoming pps: 6247 packets per second
Average outgoing pps: 5427 packets per second
Average incoming flows: 0 flows per second
Average outgoing flows: 0 flows per second
Incoming ip fragmented traffic: 0 mbps
Outgoing ip fragmented traffic: 0 mbps
Incoming ip fragmented pps: 0 packets per second
Outgoing ip fragmented pps: 0 packets per second
Incoming tcp traffic: 13 mbps
Outgoing tcp traffic: 56 mbps
Incoming tcp pps: 15441 packets per second
Outgoing tcp pps: 13766 packets per second
Incoming syn tcp traffic: 0 mbps
Outgoing syn tcp traffic: 0 mbps
Incoming syn tcp pps: 1871 packets per second
Outgoing syn tcp pps: 1023 packets per second
Incoming udp traffic: 0 mbps
Outgoing udp traffic: 0 mbps
Incoming udp pps: 412 packets per second
Outgoing udp pps: 15 packets per second
Incoming icmp traffic: 0 mbps
Outgoing icmp traffic: 0 mbps
Incoming icmp pps: 24 packets per second
Outgoing icmp pps: 0 packets per second
Average packet size for incoming traffic: 110.2 bytes 
Average packet size for outgoing traffic: 536.3 bytes

**Comment by pavel-odintsov** [comment]
Hello,

This is traffic per /32 host in our network.

**Comment by shining-github** [comment]
That is, when the normal traffic (no attack traffic) to reach the value of this set will also trigger the execution of the script.

**Comment by pavel-odintsov** [comment]
Yes, it will

On Wednesday, 29 June 2016, shining-github <notifications@github.com> wrote:

> That is, when the normal traffic (no attack traffic) to reach the value of
> this set will also trigger the execution of the script.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/527#issuecomment-229526757>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZoa0LWHxUBBSZJHAvYrhQA0wKaPPks5qQwrngaJpZM4JA824>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by shining-github** [comment]
If there is an attack traffic, but does not reach the set value, will trigger the script？

**Comment by pavel-odintsov** [comment]
No. It will not.

On Wednesday, 29 June 2016, shining-github <notifications@github.com> wrote:

> If there is an attack traffic, but does not reach the set value, will
> trigger the script？
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/527#issuecomment-229531430>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZmBEA7B5WCjf9cn3ZtBND9Ky_ieAks5qQxM3gaJpZM4JA824>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by shining-github** [comment]
Ok，I see. Whether it is normal traffic or attack traffic or they have, when reaching the set value will trigger the script.Thanks a lot.
