### ISSUE TITLE
Error when try to install git version

### ISSUE THREAD

**Issue by elmaxid** [pavel-odintsov/fastnetmon#530]
When i try to run:

`perl fastnetmon_install.pl --use-git-master
`

this appear

> syntax error at fastnetmon_install.pl line 13, near "my "
> Global symbol "$temp_folder_for_building_project" requires explicit package name at fastnetmon_install.pl line 13.
> Global symbol "$temp_folder_for_building_project" requires explicit package name at fastnetmon_install.pl line 14.
> Global symbol "$temp_folder_for_building_project" requires explicit package name at fastnetmon_install.pl line 16.

on line 12 appear:

> 1.

I remove it and the script run again

**Comment by elmaxid** [comment]
i wrote a fix and pull request it

**Comment by ZerxXxes** [comment]
I had the same problem, after removing the 1. the script started but still
failed the install.
Any clues?
http://p.ip.fi/uLxk



2016-07-05 17:08 GMT+02:00 Max Dobladez <notifications@github.com>:

**Comment by elmaxid** [comment]
Your problem appear like problem when try to install nDPI not with the script 
M.

**Comment by pavel-odintsov** [comment]
@elmaxid thank a lot :)
