### ISSUE TITLE
Пустые письма репортов

### ISSUE THREAD

**Issue by lerkh-d** [pavel-odintsov/fastnetmon#532]
Система построена на базе FreeBSD 10.2 и intel X520 10G

Интернет <-> SoftRouter <-> сервера

2016-07-07 11:49:25,767 [INFO] We run execute_ip_ban code with following params in_pps: 4891 out_pps: 0 in_bps: 1099744 out_bps: 0 and w
2016-07-07 11:49:25,767 [INFO] Attack with direction: incoming IP: 141.8.193.51 Power: 4891
2016-07-07 11:49:25,767 [INFO] Call script for ban client: 141.8.193.51
2016-07-07 11:49:25,767 [INFO] Script for ban client is finished: 141.8.193.51
2016-07-07 11:49:25,768 [ERROR] Can't pass data to stdin of programm /etc/fastnetmon_notify_attack.py 141.8.193.51 incoming 4891 attack_details

На выходе мы получаем корректно отработавший скрипт, 
OK - задача по добавлению правила в фаервол
OK - письмо репорт
но без информации о потоках `UDP flows:` или `TCP flows:`

Вызов скрипта из консоли выполняется корректно и мы получаем полный репорт. (все содержимое файла /tmp/att_test2.tmp)
`cat /tmp/att_test2.tmp | /opt/scripts/fastnetmon/fastnetmon_notify_attack.py 141.8.198.19 incoming 179819 attack_details`

**Comment by lerkh-d** [comment]
доступный в портах fastnetmon 1.1.2 имеет багу, не подгружает информацию о сетях из /etc/networks_list
посему был собран из исходников 1.1.2

**Comment by lerkh-d** [comment]
Нее проблема точно не в этом, и поправил первый пост. 

def main():
...
    if action == "unban":
...
    elif action == "ban":
...
    elif action == "attack_details":

**Comment by lerkh-d** [comment]
Предположу что виной опции:

ban_details_records_count = 500
ban_time = 30

Попробую по тестировать с другим параметрами.

**Comment by pavel-odintsov** [comment]
Маловероятно, этот код надежен как гранит;)

Проверьте стрейсом, что происходит с FNM когда он дергает хук скрипт и
сразу станет ясно. Может переменная среды можеь что-то еще ломает скрипт
когда его дергают из попена, а не с консоли.

On Thursday, 7 July 2016, Dmitry <notifications@github.com> wrote:

> Предположу что виной опции:
>
> ban_details_records_count = 500
> ban_time = 30
>
> Попробую по тестировать с другим параметрами.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/532#issuecomment-231108467>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZjmwSBLEfbpq0OE0AdQwoAtlvOwnks5qTReGgaJpZM4JG84G>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by lerkh-d** [comment]
Поправил параметры 30 > 600 и выкатил на все софтроутеры. Последняя атака ночью 56k pps syn_flood, была корректно детектирована и репорт пришел спустя 3 минуты с метриками потоков.
В качестве источника данных используется netgraph модуль ng_netflow. Данные льются в festnetmon немного с опозданиями 10-30 сек, на низком уровне трафика. 
На более крупных атаках, на той неделе в 4M pps, DNS amp, 30 сек хватало собрать метрику.

В итоге за 30 сек ban_time коллектор FNM просто не успевал нечего насобирать. 

Спасиба, все заработало.

**Comment by lerkh-d** [comment]
Если кому интересно, netgraph собран вот так.

#Сперва добавлем ноды в netgraph
/usr/sbin/ngctl -f- <<-SEQ
mkpeer ipfw: netflow 100 iface0
name ipfw:100 netflow
connect ipfw: netflow: 108 out0
msg netflow: setdlt { iface=0 dlt=12 }
msg netflow: settimeouts { inactive=15 active=60 }
mkpeer netflow: hub export hook0
name netflow:export hub
mkpeer hub: ksocket hook1 inet/dgram/udp
name hub:hook1 ExpToLocal
msg ExpToLocal: connect inet/127.0.0.1:2055
mkpeer hub: ksocket hook2 inet/dgram/udp
name hub:hook2 ExpToGW3
msg ExpToHub: connect inet/10.10.32.103:10002
SEQ

#Теперь отправляем пакетики в netgraph для подсчета
/sbin/ipfw -q add 2210 netgraph 100 ip from any to any via vlan10 in

**Comment by pavel-odintsov** [comment]
Круто! :) Рад что починилось! :)

2016-07-08 10:38 GMT+03:00 Dmitry <notifications@github.com>:

> Если кому интересно, netgraph собран вот так.
>
> #Сперва добавлем ноды в netgraph
> /usr/sbin/ngctl -f- <<-SEQ
> mkpeer ipfw: netflow 100 iface0
> name ipfw:100 netflow
> connect ipfw: netflow: 108 out0
> msg netflow: setdlt { iface=0 dlt=12 }
> msg netflow: settimeouts { inactive=15 active=60 }
> mkpeer netflow: hub export hook0
> name netflow:export hub
> mkpeer hub: ksocket hook1 inet/dgram/udp
> name hub:hook1 ExpToLocal
> msg ExpToLocal: connect inet/127.0.0.1:2055
> mkpeer hub: ksocket hook2 inet/dgram/udp
> name hub:hook2 ExpToGW3
> msg ExpToHub: connect inet/10.10.32.103:10002
> SEQ
>
> #Теперь отправляем пакетики в netgraph для подсчета
> /sbin/ipfw -q add 2210 netgraph 100 ip from any to any via vlan10 in
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/532#issuecomment-231295389>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZoxXDdaUrzYJmjDtHBTvqYkOLNz_ks5qTf5sgaJpZM4JG84G>
> .
>



-- 
Sincerely yours, Pavel Odintsov
