### ISSUE TITLE
graphite logs are eating all my storage

### ISSUE THREAD

**Issue by elibeker** [pavel-odintsov/fastnetmon#535]
Hi,
I've upgraded fastnetmon to 1.1.3 couple of days ago from git-master, and since then graphite is consuming 100GB of storage in less than 15min.
We are monitoring a 10Gbps loaded link with few thousands of systems using netmap compiled drivers.
Not sure what version I had before but this behavior is new. before it took 30 days to fill 100GB.
Is there a way to control it?
Regards, eli

**Comment by pavel-odintsov** [comment]
Hi! 

Nice to hear you!

You need to look at this article about Graphite's storage format: http://graphite.readthedocs.io/en/latest/config-carbon.html#storage-schemas-conf

In 1.1.2 I used Graphite to store only traffic which exceed's 1Mbps. But in 1.1.3 I've introduced ability to store all non zero traffic. 

By default, Graphite will store data for each metric for 1 day with single point of data (12 bytes each) for each 5 seconds. That's about 207k of data for single day. If you have thousands of zones you will have about 207K for each host in your network.

You could reduce storage time with graphite reconfiguration but you need to remove all old data from /var/lib/graphite/whisper and you lost history data in this case.

**Comment by elibeker** [comment]
Thanks for the prompt reply.
I will look into the Graphite configuration to reduce the retention period.
Also noticed the store location under the graphite_prefix have been changed while ago.
BR
