### ISSUE TITLE
Different valuesfor total/networks/hosts

### ISSUE THREAD

**Issue by iceman91176** [pavel-odintsov/fastnetmon#538]
We are using fastnetmon and storign the data to influxdb. That is workingn and we are able to query/graph the data.

I realized that the values we are getting for total/ networks/hosts do not add up.
I wuld expect that for example sum of pps inbound for all networks would be the same (or at least near) as total pps inbound.  But instead it is 4-5 times higer. Same with bps.

When summing values from hosts of one network the total is lower than the value for the network.
Is there any explanation for that ?

**Comment by pavel-odintsov** [comment]
Hello!

Please check that you have equal values for host and networks average recalculation time:
```
average_calculation_time = 5
average_calculation_time_for_subnets = 5
```
