### ISSUE TITLE
Collecting Netflow from remote devices

### ISSUE THREAD

**Issue by xUmaRix** [pavel-odintsov/fastnetmon#544]
Hi,

I setup fastnetmon on ubuntu.
everything looks good.
the netflow collector is running and it receive flow from another server.
The server forward the flow using fprobe.
However when i ran fastnetmon_client it only show other traffic.
I added my internal network prefix to network_list yet it is still the same.

`FastNetMon 1.1.3 master git-11522e4d905ca2bacb1510a107b7bd654f58016e Pavel Odintsov: stableit.ru
IPs ordered by: packets`
`Incoming traffic 0 pps 0 mbps 0 flows`

`Outgoing traffic 0 pps 0 mbps 0 flows`

`Internal traffic 0 pps 0 mbps`

`Other traffic 122040 pps 338 mbps`

`Screen updated in: 0 sec 300 microseconds
Traffic calculated in: 0 sec 25 microseconds Total amount of IPv6 packets related to our own network: 0 Not processed packets: 0 pps`

`Subnet load:`
`192.168.219.1/32 pps in: 0 out: 0 mbps in: 0 out: 0`
`192.168.224.1/32 pps in: 0 out: 0 mbps in: 0 out: 0`

**Comment by pavel-odintsov** [comment]
Hello!

Please check this: https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/INSTALL.md

You need to configure /etc/networks_list and fill it with your networks list

**Comment by xUmaRix** [comment]
thx pavel..that helps
