### ISSUE TITLE
[ERROR] Can't store network load data to Graphite

### ISSUE THREAD

**Issue by xUmaRix** [pavel-odintsov/fastnetmon#545]
Hi Pavel,

I found this error from the log file.
I had setup influxdb and it is running on port 2003
I made some change in influxdb.conf

> [[graphite]]
>   enabled = true
>   database = "fastnetmon"
>   bind-address = "127.0.0.1:2003"
>   protocol = "tcp"
>   consistency-level = "one"
>   templates = [
>     "fastnetmon.hosts.\* app.measurement.cidr.direction.function.resource",
>     "fastnetmon.networks.\* app.measurement.cidr.direction.resource",
>     "fastnetmon.total.\* app.measurement.direction.resource"
>   ]

I made some changes in fastnetmon.conf

> graphite = on
> graphite_host = 127.0.0.1
> graphite_port = 2003
> graphite_prefix = fastnetmon

However there is data in influxdb but it won't follow the template defined.

> Connected to http://localhost:8086 version 0.13.0
> InfluxDB shell version: 0.13.0
> show databases;
> ## name: databases
> 
> name
> _internal
> fastnetmon
> 
> use fastnetmon
> Using database fastnetmon
> select mean(value) from networks where direction = 'incoming' and resource = 'bps'
> ## name: networks
> 
> time    mean
> 0   122883.09241694775

I try to find simple grafana dashboard that could work for ddos monitoring but there is none.
It is something like this [https://raw.githubusercontent.com/zenvdeluca/net_healer/master/extra/nethealer.png](url)
However I couldn't configure it to be up and running.
I try to create a dashboard like this 

[http://echohn.github.io/2016/06/03/use-fastnetmon-and-grafana-to-build-a-graphical-ddos-early-warning-system/](url)

If anyone can help it would be great.

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately, I could not help with InfluxDB. You could try graphite. It's working without any magic :)

**Comment by dalibort** [comment]
Hi,
if you run 
select mean(value) from networks where direction = 'incoming' and resource = 'bps'

you calculate mean value of all values with bps and incoming attributes. It is one number. If you want a data for grafana you have to group them:
select mean(value) from networks where direction = 'incoming' and resource = 'bps' and time>'2016-08-24 00:00:00' group by time(10s)

The grafana itself construct the query which does grouping - something like:
SELECT mean("value") FROM "total" WHERE "direction" = 'incoming' AND "resource" = 'bps' AND $timeFilter GROUP BY time($interval) fill(null)
