### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by AjdinGH** [pavel-odintsov/fastnetmon#559]
I remove previous fastnetmon installation and try to install new one with gobgp.
Here are errors:
fastnetmon_install.log
`We are calling command: cmake ..  -DBoost_NO_BOOST_CMAKE=BOOL:ON -DENABLE_GOBGP_SUPPORT=ON

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- C++ compilation flags: -O3 -DNDEBUG -std=c++11
-- Setting build type to Release as none was specified.
-- You are running Linux and we can build PF_RING support
-- We found PF_RING ZC headers and will build PF_RING ZC support
-- We have enabled PF_RING's hardware filtering option
-- You are running old Linux kernel and we can't build AF_PACKET support
-- We will enable nDPI support
-- We will enable LuaJIT support
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring incomplete, errors occurred!
See also "/tmp/fastnetmon.build.dir.WSCOvLTR1y/fastnetmon/src/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/fastnetmon.build.dir.WSCOvLTR1y/fastnetmon/src/build/CMakeFiles/CMakeError.log".
Command finished with code 256

We are calling command: make -j 4

Command finished with code 512
`
Also here are errors from CmakeError.log:
`Run Build Command:/usr/bin/gmake "cmTryCompileExec3669783590/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3669783590.dir/build.make CMakeFiles/cmTryCompileExec3669783590.dir/build
gmake[1]: Entering directory `/tmp/fastnetmon.build.dir.WSCOvLTR1y/fastnetmon/src/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /tmp/fastnetmon.build.dir.WSCOvLTR1y/fastnetmon/src/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3669783590.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec3669783590.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec3669783590
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec3669783590.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec3669783590.dir/CheckFunctionExists.c.o  -o cmTryCompileExec3669783590 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: ld returned 1 exit status
gmake[1]: *** [cmTryCompileExec3669783590] Error 1
gmake[1]: Leaving directory`/tmp/fastnetmon.build.dir.WSCOvLTR1y/fastnetmon/src/build/CMakeFiles/CMakeTmp'
gmake: **\* [cmTryCompileExec3669783590/fast] Error 2
`

Kind regards.

**Comment by AjdinGH** [comment]
Now when fastnetmon try to link gobgp and fastnetmon we have error:
`CMake Error at CMakeLists.txt:270 (message):
  Could not find libgobgp


-- Configuring incomplete, errors occurred!
See also "/tmp/fastnetmon.build.dir.D66qkC5t2i/fastnetmon/src/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/fastnetmon.build.dir.D66qkC5t2i/fastnetmon/src/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
Can't build fastnetmon! at fastnetmon_install.pl line 1476, <STDIN> line 1.`

Best regards.

**Comment by pavel-odintsov** [comment]
You need to build this library manually from GoBGP project. It could be outdated and you need to fix it manually. That's why we are using ExaBGP as recommended way. GoBGP build is very complicated and I could not help there.  I'm really sorry.

**Comment by AjdinGH** [comment]
Tnx for that.
I will return old configurration and exabgp but last time when we have huge ddos attack about 40 G fastnetmon didn't detect it if freeze.
Do we need to enable pf_ring for this huge attack or do you have other solution because we did't have any errors.

**Comment by pavel-odintsov** [comment]
sflow is a better option for such big attacks.

**Comment by pavel-odintsov** [comment]
GoBGP support is experimental and targeted only for the developers.
