### ISSUE TITLE
Website: remove mousewheel event blocker (smoothscroll.js)

### ISSUE THREAD

**Issue by cookiengineer** [pavel-odintsov/fastnetmon#560]
Description:

Smoothscroll.js does not work and blocks the mousewheel event as scroll is never fired.
It is not possible to scroll the website with a mouse on a standard Desktop machine.

What causes it:

[smoothscroll.js#L199](https://fastnetmon.com/wp-content/themes/zerif-lite/js/smoothscroll.js?ver=20120206)

How to reproduce:
- Go to website
- Open Blink Dev Tools
- Event listeners on body
- Select mousewheel (bound by smoothscroll.js), click remove
- Fixed

**Comment by pavel-odintsov** [comment]
Thanks for feedback! Will check it soon!

**Comment by pavel-odintsov** [comment]
Hello!

We recently migrated to new version of theme and issue should disappear.
