### ISSUE TITLE
Json code rework 

### ISSUE THREAD

**Issue by damiankam** [pavel-odintsov/fastnetmon#577]
I think it is not bad idea to remove library `json_c` and use instead http://www.boost.org/doc/libs/1_41_0/doc/html/boost/property_tree/json_parser/write_json_id910467.html
Especially if you prefer boost. I can help.

**Comment by pavel-odintsov** [comment]
Hello!

I really hate code related with json here but boost also is not perfect for such task. I like Mongo C++ 11 interface and it also has json builder capability. But unfortunately due to wide list of supported platforms we could not use C++ :(

**Comment by pavel-odintsov** [comment]
I do not think that we have any issues with json-c. It works pretty well.
