### ISSUE TITLE
Attack Details Notify

### ISSUE THREAD

**Issue by alxbob** [pavel-odintsov/fastnetmon#578]
I run the sample notify script with details enabled but i dont get any details nor on stdin nor on email also no error in output. I get a sample email FastNetMon Guard: IP 192.168.0.1 blocked because incoming attack with power 3948 pps . Any idea?

I thing it was suppose to send something like 

IP: 192.168.0.11
Attack type: syn_flood
Initial attack power: 1282 packets per second
Peak attack power: 1282 packets per second
Attack direction: incoming
Attack protocol: tcp
Total incoming traffic: 1 mbps
Total outgoing traffic: 0 mbps
Total incoming pps: 1282 packets per second
Total outgoing pps: 0 packets per second
Total incoming flows: 1282 flows per second
Total outgoing flows: 0 flows per second
Average incoming traffic: 1 mbps
Average outgoing traffic: 0 mbps
Average incoming pps: 1282 packets per second
Average outgoing pps: 0 packets per second
Average incoming flows: 1282 flows per second
Average outgoing flows: 0 flows per second
Incoming ip fragmented traffic: 0 mbps
Outgoing ip fragmented traffic: 0 mbps
Incoming ip fragmented pps: 0 packets per second
Outgoing ip fragmented pps: 0 packets per second
Incoming tcp traffic: 1 mbps
Outgoing tcp traffic: 0 mbps
Incoming tcp pps: 1282 packets per second
Outgoing tcp pps: 0 packets per second
Incoming syn tcp traffic: 1 mbps
Outgoing syn tcp traffic: 0 mbps
Incoming syn tcp pps: 1282 packets per second
Outgoing syn tcp pps: 0 packets per second
Incoming udp traffic: 0 mbps
Outgoing udp traffic: 0 mbps
Incoming udp pps: 0 packets per second
Outgoing udp pps: 0 packets per second
Incoming icmp traffic: 0 mbps
Outgoing icmp traffic: 0 mbps
Incoming icmp pps: 0 packets per second
Outgoing icmp pps: 0 packets per second

**Comment by pavel-odintsov** [comment]
Hello!

Please share /var/log/fastnetmon.log output :)

**Comment by alxbob** [comment]
Fixed after messing with mail in linux thanks :)
