### ISSUE TITLE
No emails sent

### ISSUE THREAD

**Issue by pteratech** [pavel-odintsov/fastnetmon#584]
Using this script -

```
> #!/usr/bin/env bash
> 
> #
> # Hello, lovely FastNetMon customer! I'm really happy to see you here!
> #  Pavel Odintsov, author 
> #
> 
> # This script will get following params:
> #  $1 client_ip_as_string
> #  $2 data_direction
> #  $3 pps_as_string
> #  $4 action (ban or unban)
> 
> email_notify="**********@********.com"
> 
> #
> # Please be carefult! You should not remove cat > 
> #
> 
> if [ "$4" = "unban" ]; then
>     # No details arrived to stdin here
> 
>     # Unban actions if used
>     exit 0
> fi
> 
> #
> # For ban and attack_details actions we will receive attack details to stdin
> # if option notify_script_pass_details enabled in FastNetMon's configuration file
> # 
> # If you do not need this details, please set option notify_script_pass_details to "no".
> #
> # Please do not remove "cat" command if you have notify_script_pass_details enabled, because
> # FastNetMon will crash in this case (it expect read of data from script side).
> #
> 
> if [ "$4" = "ban" ]; then
>     cat | mail -s "FastNetMon Guard: IP $1 blocked because $2 attack with power $3 pps" $email_notify;
>     # You can add ban code here!
>     exit 0
> fi
> 
> if [ "$4" == "attack_details" ]; then
>     cat | mail -s "FastNetMon Guard: IP $1 blocked because $2 attack with power $3 pps" $email_notify;
>     
>     exit 0
> fi
```

Nothing happens yet the log has these...

> 2016-10-13 15:03:18,571 [INFO] We have found host group for this host as: global
> 2016-10-13 15:03:18,571 [INFO] We do not ban: 69.28.40.232 because ban disabled completely
> 2016-10-13 15:04:30,982 [INFO] We detected this attack by pps limit
> 2016-10-13 15:04:30,982 [INFO] We have found host group for this host as: global
> 2016-10-13 15:04:30,982 [INFO] We do not ban: 69.28.40.232 because ban disabled completely
> 2016-10-13 15:05:42,402 [INFO] We detected this attack by pps limit
> 2016-10-13 15:05:42,403 [INFO] We have found host group for this host as: global
> 2016-10-13 15:05:42,403 [INFO] We do not ban: 69.28.40.232 because ban disabled completely
> 2016-10-13 15:08:06,227 [INFO] We detected this attack by pps limit
> 2016-10-13 15:08:06,228 [INFO] We have found host group for this host as: global
> 2016-10-13 15:08:06,228 [INFO] We do not ban: 69.28.40.232 because ban disabled completely
> 2016-10-13 15:09:10,602 [INFO] We detected this attack by pps limit
> 2016-10-13 15:09:10,602 [INFO] We have found host group for this host as: global
> 2016-10-13 15:09:10,602 [INFO] We do not ban: 69.28.40.232 because ban disabled completely
> 2016-10-13 15:10:23,033 [INFO] We detected this attack by pps limit
> 2016-10-13 15:10:23,033 [INFO] We have found host group for this host as: global
> 2016-10-13 15:10:23,033 [INFO] We do not ban: 69.28.40.232 because ban disabled completely
> 2016-10-13 15:11:34,429 [INFO] We detected this attack by pps limit
> 2016-10-13 15:11:34,429 [INFO] We have found host group for this host as: global
> 2016-10-13 15:11:34,429 [INFO] We do not ban: 69.28.40.232 because ban disabled completely

Which I believe I was supposed to get an email or two for each one or is it not sending email because I have ban disabled?

**Comment by pavel-odintsov** [comment]
You have disabled ban actions "because ban disabled completely". It means "do not call notify script in case of ddos" :) Just enable it.
