### ISSUE TITLE
Can't build on Freebsd 10

### ISSUE THREAD

**Issue by eschoedler** [pavel-odintsov/fastnetmon#590]
I can't build Fastnetmon here on my Freebsd 10.
I'm not sure what is causing this problem.
http://pastebin.com/7CDCJ7Yt

Thank you!

**Comment by Milpher** [comment]
In fact, i'm currently facing the same problem with the same error.

Trying on the newest 11.0 release,

**Comment by wcc526** [comment]
You can use CentOS 7.2.I have try this work with netmap + fastnetmon

**Comment by pavel-odintsov** [comment]
Yes, for FreeBSD please use the version from ports OR use Linux and install script.
