### ISSUE TITLE
graphite_host не резолвится через DNS

### ISSUE THREAD

**Issue by evgkrsk** [pavel-odintsov/fastnetmon#594]
При указании graphite_host в виде FQDN десять раз в секунду в лог падает сообщение, что не получается отправить данные в графит. Оказалось, имя не резолвится через DNS, при указании IP всё работает. Хотя документация на это не указывает и в других местах FQDN резолвится.

Конечно, по хорошему нужно кэшировать результат резолвинга.

**Comment by pavel-odintsov** [comment]
Добрый день

В коде graphite пушера данных используется inet_pton, оно не умеет резолвинг хоста. Резолвинг красиво и с кэшированием сделать довольно сложно, поэтому придется всех просить ставить локальный кэширующий DNS. А поэтому - лучше пока с IP.

**Comment by evgkrsk** [comment]
Ну, хотя бы документировать явно.

**Comment by pavel-odintsov** [comment]
Добавил: https://github.com/pavel-odintsov/fastnetmon/commit/ec092ae7023cf779bd1360191c999cad53df081b

**Comment by evgkrsk** [comment]
Ну ладушки.
