### ISSUE TITLE
[FR] Actions persistence and segfaults with ExaBGP

### ISSUE THREAD

**Issue by evgkrsk** [pavel-odintsov/fastnetmon#596]
Скорее, идея на будущее.

Сталкиваюсь с тем, что сразу после детектирования атаки и анонса в ExaBGP Fastnetmon скоропостижно падает с SIGABRT/SIGSEGV. Через какое-то время его перезапускает systemd.

Но новый экземпляр ничего не знает о предыдущем. В частности, забаненные в ExaBGP IP-адреса никто уже никогда не разблокирует (до перезапуска ExaBGP).

Первая же мысль, которая у меня возникает: возможно, стоит все свои шаги фиксировать в чём-то вроде SQLite-базы. Например, намерение забанить IP в ExaBGP и по завершению факт бана. Чтобы, в частности, свежезапущенный экземпляр приложения подхватывал результаты работы предыдущего. Т.е. я вижу это как защиту от крэшей.

**Comment by pavel-odintsov** [comment]
Скорее вопрос стоит в том, чтобы понять, от чего он падает и это починить :) Persistency анонсов имеется в Advanced версии, https://fastnetmon.com/fastnetmon-advanced/

**Comment by evgkrsk** [comment]
Починить надо, это да. Но сегфолты в подобном приложении неизбежно будут, лучше подстелить соломки на уровне дизайна. Как понимаю классическое решение - журнал транзакций. Что собственно и предлагается.

**Comment by pavel-odintsov** [comment]
Угу, это нужно. Во многом ради этого была втянута Монга. В Advanced версии это решается тоже довольно топорно - после перезапуска удаляются все анонсы и все начинается заново.

**Comment by evgkrsk** [comment]
Я пока "обошел" добавлением такого в юнит-файл exabgp.service:
```
[Unit]

# Make exabgp part of fastnetmon service, so restarting FNM leads to exabgp restart:
PartOf=fastnetmon.service
```

возможно стОит это где-то в FNM задокументировать как вариант страховки.

**Comment by pavel-odintsov** [comment]
Тоже вараинт, в целом :) Спасибо за фикс!

**Comment by pavel-odintsov** [comment]
We've switched from ExaBGP to GoBGP as recommended daemon. I believe that anything like this will not happen with GoBGP. Please reopen if needed.
