### ISSUE TITLE
Install script (fastnetmon_install.pl) ignoring installed pfring packages 

### ISSUE THREAD

**Issue by papage** [pavel-odintsov/fastnetmon#600]
Hi,

The install script tries to do things that are already been done. For example it tries to install EPEL repo when EPEL is already installed. The same with other packages. 

My bigger problem is with pf_ring where I have a licensed version that works (6.5.0-985) and fastnetmon tries to install an older version.

Please update the script to handle these kind of things. 

Thanx,
Sp

# If you want to solve your issue please read following information below

First of all, please check following steps:
* Do you have latest FastNetMon version? If not, please upgrade to 1.1.3 version.
* Do we have similar tickets already? Please check [bug tracker](https://github.com/pavel-odintsov/fastnetmon/issues) and [Mailing list](https://groups.google.com/forum/#!forum/fastnetmon) about similar issues.

If it does not help, please fill information below:
* Your operating system name and version?
* Please attach your /etc/fastnetmon.conf configuration file
* What capture engine are you using: netflow, sflow, miror?
* If you are using netflow or sflow, please specify version, vendor name, model name and firmware of agent device.  
* Please attach /var/log/fastnetmon.log

Then please describe your issue as detailed as possible! Thanks you :)

**Comment by jemcek** [comment]
I have same problem. 

I have a valid license for PF_RING ZC v.6.5.0 for my dual port IntelXL710 40G card. On the first port I run applications like pfcount, ntopng etc. On the second port I would like to run fastnetmon with the same licensed PF_RING ZC driver v.6.5.0. 

Now if I want to install Fastnetmon using the fastnetmon_install.pl, the install script tries to load an older version of pf_ring, what makes my license useless. 

Is it possible to add a switch to fastnetmon_install.pl script to not install pf_ring modules if not desired and to use the existing one?

**Comment by pavel-odintsov** [comment]
Hello

I do not have ability to port FNM to next branch of PF_RING because I do not have dev server for performance testing. 

That's reasons why it uses outdated PF_RING.

You could download install.pl and comment out following line with "#":
```
    if ($we_have_pfring_support) {
        install_pf_ring();
    }
```

Then you need to install PF_RING manually into folder:
````
./configure --prefix=/opt/pf_ring_6.0.3
make install
```

Than you could install FNM with standard install script.
