### ISSUE TITLE
Logs filled by "Can't store data to Graphite" when monitoring interface going down

### ISSUE THREAD

**Issue by evgkrsk** [pavel-odintsov/fastnetmon#602]
Крайний коммит fnm, собран в CentOS7 с репозитариями EPEL и ntop, запущен с методом захвата PF_RING, настроен экспорт в графит. При падении линка на интерфейсе мониторинга весь лог забивается сообщениями "Can't store data to Graphite" (примерно каждую секунду).

Удобно, конечно, чтобы видеть когда линк упал. Но графит то здесь не при чём. Хорошо было бы просто писать, когда пропал/появился линк.

**Comment by pavel-odintsov** [comment]
Hello!

It's not expected behaviour. Monitoring interface and graphite are not related at all. Something in your configuration triggers such behaviour.

**Comment by evgkrsk** [comment]
Ну как же не связаны. По логу видно, что сообщения о графите и о падении сетевого интерфейса коррелируют между собой.

Насколько я помню свои ковыряния в коде в прошлом году,  остановился на таком куске кода в store_data_to_graphite:
```
    int write_result = write(client_sockfd, buffer_as_string.c_str(), buffer_as_string.size());

    close(client_sockfd);

    if (write_result > 0) {
        return true;
    } else {
        return false;
    }
```
т.е. если tcp-соединение к графиту записало ему больше нуля байт, то функция возвращает успех, иначе неудачу. Соответственно, моя теория в том, что когда падает слушаемый интерфейс, то размер отправляемых в графит данных становится нулевым (нечего отправлять) и это ведёт к тому что ежесекундная посылка статистики в графит по сути не отправляется и забивает лог излишними сообщениями.

Эту теорию я так и не проверил практически, но возможно вам ситуация будет более очевидна в силу лучшего знакомства с кодом.

**Comment by pavel-odintsov** [comment]
Бррр, не понимаю. Какой именно интерфейс перезапускается? Тот, с которого идет захват трафика для аналитики или тот, через который отправляется телеметрия на графит?

**Comment by evgkrsk** [comment]
Тот, с которого идет захват трафика для аналитики

**Comment by pavel-odintsov** [comment]
Тогда вдвойне не понимаю :)

Они не могут быть связаны, нииикаккк. Возможно, это PF_RING вызывает какие-то проблемы на других интерфейсах когда идет подъем/спуск интерфейса, но сетевой стек линукса (через который идет отправка данных в графит) совершенно отдельно работает от PF_RING, для PF_RING даже нет понятия сокета и открытие интерфейса идет через специальные системные вызовы, которые предоставляет модуль ядра PF_RING.

Стоит посмотреть, что происходит в момент перезапуска интерфейса просто изолировав код, который укладывает данные в графит в виде бэш скрипта или простого перл скрипта и посмотреть, как он себя ведет.

**Comment by evgkrsk** [comment]
Интерфейс через который отправляется телеметрия на графит - loopback, он не падает пока работает ОС :-)

Про PF_RING знаю. Но с админской т.з., как уже говорил, связь между ним и графитом очевидна - через сам FNM - нет линка на интерфейсе, нет и статистики. Почему "нет статистики" отзывается излишней руганью в логе - вопрос к коду.

Я планировал при возникновении проблемы в следующий  раз просто захватить трафик до графита и проанализировать, чем он отличается от обычного, но нам починили линк с зеркалом и проблемы давненько не было слышно :-)

**Comment by pavel-odintsov** [comment]
Возможно, переполнялся какой-то буфер из-за этого, что вызвало сбой в стеке. Сложный баг и, честно говоря, проще его решить именно так - "а вы так не делайте" :)

**Comment by evgkrsk** [comment]
Ну как-бы физические линки имеют свойство падать, не знаю, чего тут можно "не делать" :-)

**Comment by pavel-odintsov** [comment]
Если удастся воспроизвести - попробуем разобраться, в чем дело. Кстати, имело бы смысл попробовать новый PF_RING для этого.

**Comment by dmitry-sinina** [comment]
Принимаем нетфлоу и сохраняем данные в Influx. Если  добавить в iptables правило которое дропает входящие netflow пакеты, через ~2 минуты в логе начинает валить 
`[ERROR] Can't store data to Graphite`
Как только правило удаляется, ошибки больше не появляются. Таким образом как и у автора тикета, у нас fastnetmon ошибочно говорит про  "Can't store data to Graphite" в том случае если на входе нет данных.

**Comment by dmitry-sinina** [comment]
```
    int write_result = write(client_sockfd, buffer_as_string.c_str(), buffer_as_string.size());

    close(client_sockfd);

    if (write_result > 0) {
        return true;
    } else {
        return false;
    }
```
тут нельзя считать write_result=0 ошибкой если buffer_as_string.size() тоже был 0

**Comment by pavel-odintsov** [comment]
Спасибо :) Да! Отличная находка, запушил изменения, пожалуйста, попробуйте нвоую версию, поставить ее можно вот так:
```
