### ISSUE TITLE
Speedtest is detected as an attack

### ISSUE THREAD

**Issue by chasgames** [pavel-odintsov/fastnetmon#606]
Hi Pavel

When i do a speedtest.net test, it is detected as an attack. 

How can I resolve this?

Also Pavel, what is the best method to contact you by?

Thanks

**Comment by pavel-odintsov** [comment]
You could filter out traffic to/from this hosts from sflow/netflow feed with some third party tool.

You could contact me with: pavel.odintsov@gmail.com but I could not guarantee any response time.

**Comment by chasgames** [comment]
Great thanks
