### ISSUE TITLE
mixed attack type

### ISSUE THREAD

**Issue by pubyun** [pavel-odintsov/fastnetmon#611]
there is mixed type in DDOS
fastnetmon support only one attach type in report.

77 enum attack_type_t {
78     ATTACK_UNKNOWN = 1,
79     ATTACK_SYN_FLOOD = 2,
80     ATTACK_ICMP_FLOOD = 3,
81     ATTACK_UDP_FLOOD = 4,
82      ATTACK_IP_FRAGMENTATION_FLOOD = 5,
83  };
84  
85  // Amplification types

86  enum amplification_attack_type_t {
87      AMPLIFICATION_ATTACK_UNKNOWN = 1,
88      AMPLIFICATION_ATTACK_DNS     = 2,
89      AMPLIFICATION_ATTACK_NTP     = 3,
90      AMPLIFICATION_ATTACK_SSDP    = 4,
91      AMPLIFICATION_ATTACK_SNMP    = 5,
92      AMPLIFICATION_ATTACK_CHARGEN = 6,
93  };
94

**Comment by pavel-odintsov** [comment]
Mixed ddos types are not supported yet

**Comment by pavel-odintsov** [comment]
You could try to use FNM Advanced https://fastnetmon.com/fastnetmon-advanced/ and it supports mixed attacks.
