### ISSUE TITLE
InfluxDB graphite database missing

### ISSUE THREAD

**Issue by rwrocket** [pavel-odintsov/fastnetmon#612]
I followed the guides to install fastnetmon on debian 8 + graphite
Had it working but now decided I want to use grafana
So I follow the guide to install influxdb. After finding a problem with influxdb paths I reinstalled influxdb and have it working correctly now.

My problem is that I have no graphite database in influxdb when I check using influx>show databases
I have tried stopping carbon and restarting fastnetmon but it doesn't create the database.

What could be going wrong?
[influxdb-configs.zip](https://github.com/pavel-odintsov/fastnetmon/files/638216/influxdb-configs.zip)

**Comment by rwrocket** [comment]
Ok So I found I had missed a # in the influxdb config for graphite, fixed that and it creates the graphite database now. But I am not sure if it is putting data in there or not as fastnetmon.log still saying failed to write to database Graphite and my grafana graphs still empty.

I am receiving flows too because I can see them using the client monitor

**Comment by chasgames** [comment]
What output do you get in influx if you run
use graphite
select * from /.*/ limit 5

Also what query are you using to populate your grafana graphs?

For network to display see https://github.com/pavel-odintsov/fastnetmon/issues/511#issuecomment-265268120

**Comment by pavel-odintsov** [comment]
Hello

Sorry but I could not help with Influx. You could ask authors of it for
more details.

**Comment by rwrocket** [comment]
> select * from /.*/ limit 5
name: hosts
time                    app             cidr            direction       function                              resource        value
----                    ---             ----            ---------       --------                              --------        -----
1481172990000000000     fastnetmon      103_241_240_9   outgoing        averageb                              ps              3976
1481172990000000000     fastnetmon      103_27_175_18   outgoing        averageb                              ps              10672
1481172990000000000     fastnetmon      103_27_175_18   incoming        averageb                              ps              109392
1481172990000000000     fastnetmon      103_60_98_67    outgoing        averageb                              ps              8
1481172990000000000     fastnetmon      103_60_98_63    outgoing        averageb                              ps              24

name: networks
time                    app             cidr                    direction      f                              unction resource        value
----                    ---             ----                    ---------      -                              ------- --------        -----
1481237299000000000     fastnetmon      103_X_X_0_24        incoming       b                              ps              0
1481237299000000000     fastnetmon      192_168_X_140_32       outgoing       p                              ps              0
1481237299000000000     fastnetmon      103_X_X_0_24        outgoing       b                              ps              0
1481237299000000000     fastnetmon      103_X_X_0_24        outgoing       b                              ps              0
1481237299000000000     fastnetmon      103_X_X_0_24          outgoing       b                              ps              0

name: total
time                    app             cidr    direction       function       r                              esource value
----                    ---             ----    ---------       --------       -                              ------- -----
1481172990000000000     fastnetmon              incoming                       b                              ps              7.151708e+07
1481172990000000000     fastnetmon              outgoing                       p                              ps              6224
1481172990000000000     fastnetmon              incoming                       p                              ps              8319
1481172990000000000     fastnetmon              incoming                       f                              lows            103
1481172990000000000     fastnetmon              outgoing                       f                              lows            126

**Comment by rwrocket** [comment]
Attached my grafana graphs.
I followed instructions here:
http://echohn.github.io/2016/06/03/use-fastnetmon-and-grafana-to-build-a-graphical-ddos-early-warning-system/

[Fastnetmon-1481237529981.zip](https://github.com/pavel-odintsov/fastnetmon/files/640791/Fastnetmon-1481237529981.zip)

**Comment by chasgames** [comment]
Looks like your data is in the database. Check your Grafana queries.

Here are my graphs and query:
![fastnetmon_graph2](https://cloud.githubusercontent.com/assets/9719722/21108071/a8ed9f54-c08b-11e6-9ea0-fb7bb8ac2f8c.PNG)
![fastnetmon_graph](https://cloud.githubusercontent.com/assets/9719722/21108072/a8ef5a4c-c08b-11e6-846c-6be9408a75ca.PNG)

**Comment by rwrocket** [comment]
Thank you this is just what I needed :)
