### ISSUE TITLE
ALERT! Toolkit working incorrectly! We should calculate speed in ~1 second

### ISSUE THREAD

**Issue by rwrocket** [pavel-odintsov/fastnetmon#613]
ALERT! Toolkit working incorrectly! We should calculate speed in ~1 second
what does this mean exactly and how to fix it?

I am trying to get pfring with port mirror working and I keep getting this show up in client monitor.

Could this be why the mbps readings seem to be inaccurate? as in 1 or 0 when should be 25+

```
fastnetmon.conf
###
### Main configuration params
###

### Logging configuration

# enable this option if you want to send logs to local syslog facility
logging:local_syslog_logging = off

# enable this option if you want to send logs to a remote syslog server via UDP
logging:remote_syslog_logging = off

# specify a custom server and port for remote logging
logging:remote_syslog_server = 10.10.10.10
logging:remote_syslog_port = 514

# Enable/Disable any actions in case of attack
enable_ban = on

# disable processing for certain direction of traffic
process_incoming_traffic = on
process_outgoing_traffic = on

# How many packets will be collected from attack traffic
ban_details_records_count = 500

# How long (in seconds) we should keep an IP in blocked state
# If you set 0 here it completely disables unban capability
ban_time = 1900

# Check if the attack is still active, before triggering an unban callback with this option
# If the attack is still active, check each run of the unban watchdog
unban_only_if_attack_finished = on

# enable per subnet speed meters
# For each subnet, list track speed in bps and pps for both directions
enable_subnet_counters = off

# list of all your networks in CIDR format
networks_list_path = /etc/networks_list

# list networks in CIDR format which will be not monitored for attacks
white_list_path = /etc/networks_whitelist

# redraw period for client's screen
check_period = 1

# Connection tracking is very useful for attack detection because it provides huge amounts of information,
# but it's very CPU intensive and not recommended in big networks
enable_connection_tracking = on

# Different approaches to attack detection
ban_for_pps = on
ban_for_bandwidth = on
ban_for_flows = off

# Limits for Dos/DDoS attacks
threshold_pps = 20000
threshold_mbps = 1000
threshold_flows = 3500

# Per protocol attack thresholds
# We don't implement per protocol flow limits, sorry :(
# These limits should be smaller than global pps/mbps limits

threshold_tcp_mbps = 100000
threshold_udp_mbps = 100000
threshold_icmp_mbps = 100000

threshold_tcp_pps = 100000
threshold_udp_pps = 100000
threshold_icmp_pps = 100000

ban_for_tcp_bandwidth = off
ban_for_udp_bandwidth = off
ban_for_icmp_bandwidth = off

ban_for_tcp_pps = on 
ban_for_udp_pps = on
ban_for_icmp_pps = on

###
### Traffic capture methods
###

# PF_RING traffic capture, fast enough but the wirespeed version needs a paid license
mirror = on

# Port mirroring sample rate
pfring_sampling_ratio = 1

# Netmap traffic capture (very fast but needs patched drivers)
mirror_netmap = off

# SnabbSwitch traffic capture
mirror_snabbswitch = off

# AF_PACKET capture engine
# Please use it only with modern Linux kernels (3.6 and more)
# And please install birq for irq ditribution over cores
mirror_afpacket = off

# use PCI-e addresses here instead of OS device names. You can find them in "lspci" output
interfaces = pci@0000:04:00.1

# Port mirroring sampling ratio
netmap_sampling_ratio = 1

# This option should be enabled if you are using Juniper with mirroring of the first X bytes of packet: maximum-packet-length 110;
netmap_read_packet_length_from_ip_header = off

# Pcap mode, very slow and thus not suitable for production
pcap = off
# Netflow capture method with v5, v9 and IPFIX support
netflow = off
# sFLOW capture suitable for switches
sflow = off

# PF_RING configuration
# If you have a license for PF_RING ZC, enable this mode and it might achieve wire speed for 10GE
enable_pf_ring_zc_mode = off

# Configuration for netmap, mirror, pcap modes
# For pcap and PF_RING we could specify "any"
# For netmap and PF_RING we could specify multiple interfaces = eth0,eth1,eth2
interfaces = eth1

# We use average values for traffic speed to certain IP and we calculate average over this time slice
average_calculation_time = 5

# We use average values for traffic speed for subnet and we calculate average over this time slice
average_calculation_time_for_subnets = 20

# Netflow configuration

# it's possible to specify multiple ports here, using commas as delimiter
netflow_port = 2055
netflow_host = 0.0.0.0

# To bind to all interfaces = eth0,eth1,eth2
# To bind to all interfaces = eth0,eth1,eth2
# To bind to localhost for a specific protocol:      ::1 or 127.0.0.1

# Netflow v9 and IPFIX agents use different and very complex approaches for notifying about sample ratio
# Here you could specify a sampling ratio for all this agents
# For NetFLOW v5 we extract sampling ratio from packets directely and this option not used
netflow_sampling_ratio = 1

# In some cases with NetFlow we could get huge bursts related to aggregated data nature
# We could try to get smoother data with this option, i.e. we will divide counters on collection interval time
netflow_divide_counters_on_interval_length = off

# Process each netflow packet with LUA
# This option is not default and you need build it additionally
# netflow_lua_hooks_path = /usr/src/fastnetmon/src/netflow_hooks.lua

# sFLOW configuration

# It's possible to specify multiple ports here, using commas as delimiter
sflow_port = 6343
# sflow_port = 6343,6344
sflow_host = 0.0.0.0

# process each sFLOW packet with LUA
# This option is not default and you need build it additionally
# sflow_lua_hooks_path = /usr/src/fastnetmon/src/sflow_hooks.lua

###
### Actions when attack detected
###

# This script executed for ban, unban and attack detail collection
notify_script_path = /usr/local/bin/notify_about_attack.sh

# pass attack details to notify_script via stdin
# Pass details only in case of "ban" call
# No details will be passed for "unban" call
notify_script_pass_details = on

# collect a full dump of the attack with full payload in pcap compatible format
collect_attack_pcap_dumps = off

# Execute Deep Packet Inspection on captured PCAP packets
process_pcap_attack_dumps_with_dpi = off

# Save attack details to Redis
redis_enabled = off

# Redis configuration
redis_port = 6379
redis_host = 127.0.0.1

# specify a custom prefix here
redis_prefix = mydc1

# We could store attack information to MongoDB
mongodb_enabled = off
mongodb_host = localhost
mongodb_port = 27017
mongodb_database_name = fastnetmon

# If you are using PF_RING non ZC version you could block traffic on host with hardware filters
# Please be aware! We can not remove blocks with this action plugin
pfring_hardware_filters_enabled = off

# announce blocked IPs with BGP protocol with ExaBGP
exabgp = off
exabgp_command_pipe = /var/run/exabgp.cmd
exabgp_community = 65001:666

# specify multiple communities with this syntax:
# exabgp_community = [65001:666 65001:777]

# specify different communities for host and subnet announces
# exabgp_community_subnet = 65001:667
# exabgp_community_host = 65001:668

exabgp_next_hop = 10.0.3.114

# In complex cases you could have both options enabled and announce host and subnet simultaneously

# Announce /32 host itself with BGP
exabgp_announce_host = on

# Announce origin subnet of IP address instead IP itself
exabgp_announce_whole_subnet = off

# Announce Flow Spec rules when we could detect certain attack type
# Please we aware! Flow Spec announce triggered when we collect some details about attack,
# i.e. when we call attack_details script
# Please disable exabgp_announce_host and exabgp_announce_whole_subnet if you want to use this feature
# Please use ExaBGP v4 only (Git version), for more details: https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/BGP_FLOW_SPEC.md
exabgp_flow_spec_announces = off

# GoBGP intergation
gobgp = off
gobgp_next_hop = 0.0.0.0
gobgp_announce_host = on
gobgp_announce_whole_subnet = off

# Graphite monitoring
# InfluxDB is also supported, please check our reference:
# https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/INFLUXDB_INTEGRATION.md
graphite = on
graphite_host = 127.0.0.1
graphite_port = 2003

# Default namespace for Graphite data
graphite_prefix = fastnetmon

# Add local IP addresses and aliases to monitoring list
# Works only for Linux
monitor_local_ip_addresses = on

# Create group of hosts with non-standard thresholds
# You should create this group before (in configuration file) specifying any limits
hostgroup = my_hosts:10.10.10.221/32,10.10.10.222/32

# Configure this group
my_hosts_enable_ban = off

my_hosts_ban_for_pps = off
my_hosts_ban_for_bandwidth = off
my_hosts_ban_for_flows = off

my_hosts_threshold_pps = 20000
my_hosts_threshold_mbps = 1000
my_hosts_threshold_flows = 3500

# Path to pid file for checking "if another copy of tool is running", it's useful when you run multiple instances of tool
pid_path = /var/run/fastnetmon.pid

# Path to file where we store information for fastnetmon_client
cli_stats_file_path = /tmp/fastnetmon.dat

# Enable gRPC api (required for fastnetmon_api_client tool)
enable_api = off

###
### Client configuration
###

# Field used for sorting in client, valid values are: packets, bytes or flows
sort_parameter = packets
# How much IPs will be listed for incoming and outgoing channel eaters
max_ips_in_list = 7


```

**Comment by rwrocket** [comment]
Occasionally I get incoming and outgoing IP in my networks_list showing up briefly but always 0pps

![no_packets](https://cloud.githubusercontent.com/assets/24306959/21169282/fbb0cf8e-c20e-11e6-9131-051a9d896c71.png)

**Comment by pavel-odintsov** [comment]
First error about processing time coukd have two mail reasons:
1. Huge, very long list of networks
2. Very very slow cpu

You could try to use sflow instead. But pfring is so reliable way to
capture traffic. You definitely have some specific issues on your box.

**Comment by rwrocket** [comment]
I got that message to go away now,  sflow not possible as my hardware
doesn't support. Netflow works well but it's slow.

I have simple port mirror connected to eth1 on fastnetmon box and as you
can see by the last screenshot of monitor it is getting some packets but
the totals remain 0. Perhaps it is not calculating properly?

**Comment by rwrocket** [comment]
There is only one /24 network in my networks_list and here is my cpu info.
Not the most fastest but not too bad either.

Do I need to manually install BIRQ? I haven't done anything yet other than setting up mail and installing fastnetmon following the install instructions on Debian 8.

`processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5140  @ 2.33GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 2000.000
cache size      : 4096 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4667.17
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5140  @ 2.33GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 2000.000
cache size      : 4096 KB
physical id     : 3
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4667.22
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5140  @ 2.33GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 2000.000
cache size      : 4096 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4667.17
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5140  @ 2.33GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 2000.000
cache size      : 4096 KB
physical id     : 3
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dtherm tpr_shadow vnmi flexpriority
bogomips        : 4667.22
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:
`

**Comment by rwrocket** [comment]
![fastnetmon](https://cloud.githubusercontent.com/assets/24306959/21246135/e2cbc47a-c37a-11e6-8d95-dd38d37f059b.png)

**Comment by pavel-odintsov** [comment]
FastNetMon could not find your traffic. For some reasons and I do not know why. You could ignore "ALERT! Toolkit working incorrectly! We should calculate speed in ~1 second" error if it occurs from time to time. It's pretty safe.

**Comment by pavel-odintsov** [comment]
PF_RING is pretty reliable capture method and it should work. But you could play with AF_PACKET. Just enable it in configuration instead of PF_RING (and disable PF_RING for sure).

**Comment by rwrocket** [comment]
Well with AFPACKET I am getting all 0s. Not listing packets received at all.
2016-12-16 11:21:54,966 [INFO] We loaded 2 IPv4 subnets to our in-memory list of networks
2016-12-16 11:21:54,967 [INFO] AF_PACKET plugin started
2016-12-16 11:21:54,967 [INFO] Run banlist cleanup thread, we will awake every 60 seconds
2016-12-16 11:21:54,967 [INFO] AF_PACKET will listen on 1 interfaces

Could it be the interface? I tried to specify PCI-e address instead of OS name like the config said but fastnetmon was never able to start that way. instead on my config I just list eth1

**Comment by pavel-odintsov** [comment]
Yes, it should be an interface. PCI-E is only snabbswitch (not recommended).

**Comment by rwrocket** [comment]
Ok so with AFPACKET I get nothing. With PFRING it gets Packets Received and if I do a ping or something from outside to inside my network I see the destination IP pop up in incoming traffic and outgoing traffic on the monitor. Just it always reads 0 pps and 0 mbps

**Comment by pavel-odintsov** [comment]
That's time to use another linux distribution. I recommend to use Ubuntu 14/04, it's working really well for almost all.

**Comment by rwrocket** [comment]
:(
Hmmm ouch... I see

**Comment by pavel-odintsov** [comment]
Actually you have something strange on your box which prevent FNM from correct working. It working really well, really. But sometimes due to some conflicting configuration options / custom kernels it's not working.

**Comment by rwrocket** [comment]
Is there any configs and logs I can add that might help you understand what it might be?

**Comment by pavel-odintsov** [comment]
/var/log/fastnetmon.log.

**Comment by rwrocket** [comment]
Here is the log and the conf, keep in mind I changed settings and fixed a few problems previously and the log has never been cleared.

[fastnetmon.zip](https://github.com/pavel-odintsov/fastnetmon/files/656247/fastnetmon.zip)

**Comment by pavel-odintsov** [comment]
Everything looks fine. That's time to check firewall / increase power of testing traffic.

**Comment by pavel-odintsov** [comment]
Check this one  https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/FINE_TUNING.md

You could force FNM to print all captured packets. It's very handy for debug.

**Comment by rwrocket** [comment]
I have reinstalled using ubuntu server 14.04 as I figured it would be easier than trying the link above. I now have the exact same problem. I am wondering it it could be something wrong with my mirror config? but I can see some packets received and when I do a speedtest I get Incoming and Outgoing IP come up but always 0pps 0 mbps??

I have tried different network interfaces, same result. Maybe it is my mirror setup? I did try two different switches for the port mirror but I don't have any experience using port mirroring :(

**Comment by rwrocket** [comment]
OMG I just discovered it was my port mirror !! I am now getting pps readings
I think it might need some tweaking but at least I can troubleshoot further now I am actually getting packets

**Comment by pavel-odintsov** [comment]
Cool! My congratulations!
