### ISSUE TITLE
Lack of information about atack

### ISSUE THREAD

**Issue by mcflyspb** [pavel-odintsov/fastnetmon#616]
Полная информация по атаке из файла, но нет никакой детализации. (This is full information about atack but no detail (src ip, proto...))
cat 82.112.190.135_15_12_16_18\:46\:10 | mail ...............

IP: 82.112.190.135
Attack type: unknown
Initial attack power: 178163 packets per second
Peak attack power: 178163 packets per second
Attack direction: incoming
Attack protocol: tcp
Total incoming traffic: 971 mbps
Total outgoing traffic: 0 mbps
Total incoming pps: 178163 packets per second
Total outgoing pps: 0 packets per second
Total incoming flows: 0 flows per second
Total outgoing flows: 0 flows per second
Average incoming traffic: 971 mbps
Average outgoing traffic: 0 mbps
Average incoming pps: 178163 packets per second
Average outgoing pps: 0 packets per second
Average incoming flows: 0 flows per second
Average outgoing flows: 0 flows per second
Incoming ip fragmented traffic: 0 mbps
Outgoing ip fragmented traffic: 0 mbps
Incoming ip fragmented pps: 0 packets per second
Outgoing ip fragmented pps: 0 packets per second
Incoming tcp traffic: 0 mbps
Outgoing tcp traffic: 0 mbps
Incoming tcp pps: 0 packets per second
Outgoing tcp pps: 0 packets per second
Incoming syn tcp traffic: 0 mbps
Outgoing syn tcp traffic: 0 mbps
Incoming syn tcp pps: 0 packets per second
Outgoing syn tcp pps: 0 packets per second
Incoming udp traffic: 0 mbps
Outgoing udp traffic: 0 mbps
Incoming udp pps: 0 packets per second
Outgoing udp pps: 0 packets per second
Incoming icmp traffic: 0 mbps
Outgoing icmp traffic: 0 mbps
Incoming icmp pps: 0 packets per second
Outgoing icmp pps: 0 packets per second

Average packet size for incoming traffic: 714.9 bytes 
Average packet size for outgoing traffic: 0.0 bytes

**Comment by pavel-odintsov** [comment]
Детализации нет в том, случае, если connection_tracking отключен, включите его и появится (но заодно и вырастет нагрузка на процессор и упадет пропускная способность)
