### ISSUE TITLE
Grafana Queries

### ISSUE THREAD

**Issue by chasgames** [pavel-odintsov/fastnetmon#622]
Hi Pavel

Do you mind sharing how you got the detailed FastNetMon attack report to show up on your Grafana graphs. I noticed this in your presentation. Also any other queries that would be helpful for us?

Thanks

![image](https://cloud.githubusercontent.com/assets/9719722/21719571/5ce31974-d416-11e6-95f6-8510bc573005.png)

**Comment by pavel-odintsov** [comment]
Hello

It was community contributed. You could ask for it with mail list;)

**Comment by chasgames** [comment]
Oki Doki
