### ISSUE TITLE
[INFO] Time from last run of speed_recalc is soooo big, we got ugly lags: 2 [INFO] We skip one iteration of speed_calc because it runs so early! 

### ISSUE THREAD

**Issue by rwrocket** [pavel-odintsov/fastnetmon#623]
[INFO] Time from last run of speed_recalc is soooo big, we got ugly lags: 2 [INFO] We skip one iteration of speed_calc because it runs so early! 

I keep getting this showing in my fastnetmon log

I am using pfring

conf attached

[fastnetmon.zip](https://github.com/pavel-odintsov/fastnetmon/files/725628/fastnetmon.zip)

**Comment by pavel-odintsov** [comment]
It's not crytical. You have slow cpu / big nubrr of hosts / another cpu
intensive processes on same server.
