### ISSUE TITLE
Уточнения по поводу порогов срабатывания

### ISSUE THREAD

**Issue by Anito23** [pavel-odintsov/fastnetmon#625]
Привет!!!

Хотел немного уточнить по вопросу установки нескольких порогов срабатывания. 

В конфигурационном файле fastnetmon.conf есть следующие параметры для определения порогов:

#Общие (глобальные) пороги по количеству сетевых пакетов
threshold_pps 

#Пороги по протоколам
threshold_tcp_pps
threshold_udp_pps
threshold_icmp_pps

А есть еще 

my_hosts_threshold_pps

К примеру, если мы установили общий порог срабатывания threshold_pps в 100К и порог срабатывания для TCP протокола threshold_tcp_pps в 50К. После чего, любую TCP атаку начало блокировать уже при превышении 50К pps. Тут все правильно. 

Далее для определенного IP или подсети решили увеличить порог срабатывания для TCP протокола. Для этого добавили IP адрес в параметр hostgroup и установили следующие параметры:

hostgroup = my_hosts:10.10.10.221/32
my_hosts_enable_ban = on
my_hosts_ban_for_pps = on
my_hosts_threshold_pps = 100000

Т.е. для IP 10.10.10.221/32 должен теперь действовать свой порог срабатывания в 100К. 

В результате настройки получили срабатывание при 50К pps при TCP атаке на IP 10.10.10.221/32. Т.е. срабатывает порог срабатывания установленный для TCP протокола.

Вопрос. Так и было задумано?

Возможно ли для hostgroup сделать отдельные пороги срабатывания для протоколов?

**Comment by evgkrsk** [comment]
Насколько я помню PDF-ку мануала из исходников, да, так и задумано, т.к. групповые лимиты должны быть меньше глобальных чтобы работать (ну и CIDR-ы их должны быть в networks_list).

Пороги для групп вроде не реализовывались.

**Comment by Anito23** [comment]
Оказалось, что нужно добавить IP или сеть, которые указаны в параметре hostgroup, отдельно в файл networks_list. 

Т.е. если в hostgroup указан IP адрес 10.10.10.221/32, то его нужно добавить в файл networks_list, даже если там уже присутствует сеть 10.10.10.0/24.

После добавления IP адреса в файл networks_list отдельный порог заданный параметром my_hosts_threshold_pps начал работать и атака стала блокироваться только при 100К пакетов.  

В hostgroup можно указать и сеть. К примеру, мы добавили сеть /24. Затем добавили ее в файл networks_list (хотя она уже была указана в общей сети /20) и все заработало. Для всех IP адресов сети /24 заработал отдельный порог. 

Спасибо за помощь Павлу.

**Comment by pavel-odintsov** [comment]
Всегда пожалуйста :) Да, фича неприятная, но без нее реализация групп заняла бы нааамного больше времени.
