### ISSUE TITLE
Multiple instances not working

### ISSUE THREAD

**Issue by plojr** [pavel-odintsov/fastnetmon#628]
I'm running fastnetmon on a Debian 8 with 128GB of RAM and 4 six cores 2,4GHz. I've only installed fasnetmon and graphite/carbon till now.

When I start the service (with service fastnetmon start), everything works fine. I can even capture data using Graphite via browser and I can see incoming/outgoing data being drawn. So far so good.

But, when I run ./fastnetmon configuration_file=/etc/fastnetmon_firewall.conf --daemonize for another instance, I got this error: [ERROR] FastNetMon is already running with pid: 40593 (seen in /var/log/fastnetmon.log).

As required, my /etc/fastnetmon_firewall.conf file has:

pid_path = /var/run/fastnetmon_firewall.pid
cli_stats_file_path = /tmp/fastnetmon_firewall.dat

I've also tested it on another machine (on a Debian 8 virtual machine) and everything worked fine there, but I don't know what I'm missing on this one. Could you help me with that?

Thanks in advance.

**Comment by plojr** [comment]
I've tested another situation:
- I stopped fastnetmon with service fastnetmon stop
- I ran it again with ./fastnetmon configuration_file=/etc/fastnetmon_firewall.conf --daemonize

It seems that, even with pid_path = /var/run/fastnetmon_firewall.pid, it's created fastnetmon.pid at /var/run.

I think it's not reading the configuration file.

**Comment by plojr** [comment]
After seeing this https://github.com/pavel-odintsov/fastnetmon/issues/518, I solved the problem.

**Comment by pavel-odintsov** [comment]
That's awesome! :) Glad to see fixed issue!
