### ISSUE TITLE
Doubts about integrating ExaBGP with Fastnetmon

### ISSUE THREAD

**Issue by plojr** [pavel-odintsov/fastnetmon#633]
As you can see with my other questions, I'm kinda lost, but with them, I'm going to understand what I need, and I'll stop asking, and start answering other's questions.

My doubt, this time, is: after doing that https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/EXABGP_INTEGRATION.md, 

1) how to blackhole an attacker? What code do I have to use (inside notify_about_attack.sh) in order to blackhole an attacker?

2) do I need to ask something for the Network Engineering guys, as I don't have access to the router's configuration?

Some details:

- We setup an sflow for the computer where the Fastnetmon is installed.
- We use Juniper here.

**Comment by pavel-odintsov** [comment]
Hello!

1. "how to blackhole an attacker?" it's impossible without BGP Flow Spec on your network. BGP Blackhole could block only your hosts.
2. Yes sure. Almost all tasks with volumetric attack mitigation need tight integration with your network and involves interaction with your network guys.

**Comment by plojr** [comment]
1. I'll read about BGP Flow Spec. It's my very first project in the field, and almost everything is new for me, and I'm learning "on demand".

2. Ok, and what do they (Network) have to do? I know that the router must allow FNM to negotiate a BGP session, but what do I need in order to do that?

**Comment by pavel-odintsov** [comment]
2. Yes. They need allow you to announce BGP Flow Spec announces. But be careful you could kill your routers with this announces very simple.
