### ISSUE TITLE
Incorrect warning about DDOS - Netflow version 9

### ISSUE THREAD

**Issue by tuda09081990** [pavel-odintsov/fastnetmon#635]
[fastnetmon-config.txt](https://github.com/pavel-odintsov/fastnetmon/files/837586/fastnetmon-config.txt)

[fastnetmon_log.txt](https://github.com/pavel-odintsov/fastnetmon/files/837616/fastnetmon_log.txt)

Hi,
Please help to check my problem. I was install Fastnetmon on Centos 7, config netflow version 9 on routers ASR9K Cisco for forward netflow information to server Fastnetmon. It's work but seem like something wrong because i recieved very much email alerts with incorrect information about bandwith. 
For example: I has a transit customer with bandwith limited for inbound and outbound is 900Mb, on my monitor system like cacti, prtg...i don't see congestion  but i recieved email of fastnetmon with information that an IP of customer has outgoing traffic reach to 1200mbps

Kindly check file config and log in files attachment. So sory because my Eng is not good :)

Here's netflow config on my router:
flow exporter-map NFEM
 version v9
  options interface-table timeout 120
  options sampler-table timeout 120
 !
 transport udp 9997
 source Loopback1
 destination x.x.x.x vrf AAAA

flow monitor-map NFMM
 record ipv4
 exporter NFEM
 cache entries 25000
 cache timeout active 2
 cache timeout inactive 2

interface Bundle-Ether500
 description PEERING_A
 service-policy input BW.Profile.Internet
 vrf AAAA
 ipv4 address 
 flow ipv4 monitor NFMM sampler NFSM ingress
 flow ipv4 monitor NFMM sampler NFSM egress

**Comment by pavel-odintsov** [comment]
Hello!

If you could provide pcap file with your netflow data for 5-10 minutes it would be nice. You could share it privately with me using pavel.odintsov@gmail.com

I think your device violates "active/inactive timeout" value and uses bigger value in reality. So you could try to change it to 10-30 seconds and check for improvements.

Also I noticed options templates:
```netflow_sampling_ratio = 2```

Is it correct value?

**Comment by pavel-odintsov** [comment]
Also I think you missed few networks:
```
2017-03-13 11:40:28,669 [ERROR] Can't parse line from subnet list: '112.78.10.0/24  '
2017-03-13 11:40:28,669 [ERROR] Can't parse line from subnet list: '112.78.11.0/24  '
2017-03-13 11:40:28,669 [ERROR] Can't parse line from subnet list: '112.78.12.0/23  '
2017-03-13 11:40:28,669 [ERROR] Can't parse line from subnet list: '112.78.13.0/24  '
2017-03-13 11:40:28,669 [ERROR] Can't parse line from subnet list: '112.78.14.0/24  '
2017-03-13 11:40:28,669 [ERROR] Can't parse line from subnet list: '112.78.15.0/24  '
2017-03-13 11:40:28,669 [ERROR] Can't parse line from subnet list: '103.9.0.0/22,'
```

Please remove all spaces at the end of lines.

And same for this option:
```
2017-03-13 11:40:28,575 [ERROR] Can't parse config line: 'ban_for_tcp_pps = off '
```

**Comment by tuda09081990** [comment]
Dear Pavel,
Thank you for your help. I sent pcap file to your email, pls check. I will try to edit config file as your suggest. About netflow_sampling_ratio, when it = 1 as default, total bandwith for all link is incorrect (It's less than the reality about 500Mbps) so i tried to change it = 2 like timeout active/inactive and had seen it's seem like correct. Do you have any suggest for the line ?

**Comment by pavel-odintsov** [comment]
Hello

I just received it. Actually you could debug such issues without my help. Recently I published article about it: https://fastnetmon.com/2017/01/20/netflow-flows-duration/

I extracted flow durations for your device:
```
tshark -o "cflow.netflow.ports: 2055,9996,9997" -r fastnetmon_netflow9.pcap -V -T fields -e cflow.timedelta|perl -e 'do{print join "\n", split ","}for<>'|hist -b 100
[        0.00000 -         4.14163]:    8509223 ##############################################################################
[        4.14163 -         8.28326]:     994008 #########
[        8.28326 -        12.42489]:     314169 ##
[       12.42489 -        16.56652]:     124899 #
[       16.56652 -        20.70815]:      71362 
[       20.70815 -        24.84978]:      32311 
[       24.84978 -        28.99141]:      19533 
[       28.99141 -        33.13304]:      21470 
[       33.13304 -        37.27467]:       5143 
[       37.27467 -        41.41630]:       2902 
[       41.41630 -        45.55793]:       1886 
[       45.55793 -        49.69956]:       1274 
[       49.69956 -        53.84119]:        990 
[       53.84119 -        57.98282]:        729 
```

So your configuration for:
```
average_calculation_time = 5
```

Is definitely incorrect because your device ignores active/inactive specified as 2. I would recommend to set 12-16.

**Comment by tuda09081990** [comment]
Dear Pavel,
Sorry for late reply. Thank you, now everything is okie :)
