### ISSUE TITLE
Limit data stream to graphite/influxdb

### ISSUE THREAD

**Issue by evgkrsk** [pavel-odintsov/fastnetmon#636]
I added /19 to the list of networks and did not immediately understand why the server became so sad, despite the fact that there was no more traffic at the entrance.

Graphite just started writing statistics for each address from /19. Up to nuclear traces deep into xfs.

I propose to introduce a custom prefix length, the minimum required to get into the statistics on hosts (graphite/influxdb). For example, with a value of 24 (bits), individual addresses from the /19 network (from the list of networks) will not be included in the statistics, only general indicators for the entire network. And addresses from networks /24, /25, etc. - will fall in full.

**Comment by pavel-odintsov** [comment]
Добрый день!

Ну, не знаю. Если юзать инфлакс - он провернет этот трафик без особых проблем. Проще просто закомментировать код, который пушит статистику по хостам и оставить статистику по сеткам. 

Статистики по различному уровню аггрегации сетей как таковой нету. Только хост и сеть, к которой он принадлежит даже если она /8.

**Comment by pavel-odintsov** [comment]
In case of any performance issues with InfluxDB I can recommend Victoria Metrics which uses compatible interface which can be done via new native InfluxDB interface: https://fastnetmon.com/docs/influxdb_integration/

In Advanced edition we support extremely efficient Clickhouse as metrics storage: https://fastnetmon.com/docs-fnm-advanced/traffic-metrics-in-clickhouse/
