### ISSUE TITLE
Huawei netstream v5 problem - vendor's implementation issue

### ISSUE THREAD

**Issue by pubyun** [pavel-odintsov/fastnetmon#649]
netstream v5 of huawei is similiar with netflow v5.
netstream v9 of huawei is similiar with netflow v9.

netstream v9 works fine with fastnetmon. and there is problem with netstream v5 parser of fastnetmon.

the Incoming traffic  and Outgoing traffic are not correct.
total traffic should be about 50 gbps, and fastnetmon only show 50mbps.

the sample ratio is 1000:1. here is config of fastnetmon:

netflow_port = 50040
netflow_sampling_ratio = 1000

we use nfcap and nfdump to process the netstream v5 of huawei , it's OK.

if we export netstream v9, then fastnetmon works fine.

v5 and v9 data attached.

[netstream.zip](https://github.com/pavel-odintsov/fastnetmon/files/902004/netstream.zip)

**Comment by pavel-odintsov** [comment]
Hello!

Could you clarify what's kind of issue do you have with netstream v5? I do not see any erros / error logs attached.

**Comment by pubyun** [comment]
total traffic should be about 50 gbps, and fastnetmon only show 50mbps.

**Comment by pavel-odintsov** [comment]
Hello!

I checked Netflow (Netstream) 5 dump and discovered following behaviour:

<img width="1196" alt="screen shot 2017-04-08 at 14 46 38" src="https://cloud.githubusercontent.com/assets/2744166/24828254/40ce05f4-1c6a-11e7-9632-e8c812ec9e2c.png">

As you can see we have "zero" in sampling rate field of Netflow 5 packet. I guess it's some kind of issue with your device and you need to check your support team about it.

Yes, we have special option to specify sampling rate in configuration but we use it only for Netflow9/IPFIX.

For Netflow v5 we use following logic:
```
   uint16_t netflow5_sampling_ratio = fast_ntoh(nf5_hdr->sampling_rate);

    // Sampling not enabled on device
    if (netflow5_sampling_ratio == 0) { 
        netflow5_sampling_ratio = 1; 
    } 
```

**Comment by pavel-odintsov** [comment]
Also, I could not find option templates in Netflow v9 dump. Could you capture data for 5-10 minutes to capture option's templates? 

But anyway, Netflow v9 should work fine if you specified sampling_rate in configuration.

**Comment by pavel-odintsov** [comment]
Hello!

Do you have any updates from your device support about such misbehaviour?

Thank you!

**Comment by pavel-odintsov** [comment]
@pubyun have you found time to ask your device vendor about this issue?

**Comment by pavel-odintsov** [comment]
I hope Huawei fixed this bug.
