### ISSUE TITLE
Global pps limit

### ISSUE THREAD

**Issue by dmayan** [pavel-odintsov/fastnetmon#651]
Hi Pavel,

I'm getting a lot of this errors on my logs:

```
2017-04-17 14:51:43,816 [INFO] We have found host group for this host as: global
2017-04-17 14:51:44,818 [INFO] We detected this attack by pps limit
2017-04-17 14:51:44,818 [INFO] We have found host group for this host as: global
2017-04-17 14:51:44,818 [INFO] We detected this attack by pps limit
2017-04-17 14:51:44,818 [INFO] We have found host group for this host as: global
2017-04-17 14:51:45,820 [INFO] We detected this attack by pps limit
2017-04-17 14:51:45,820 [INFO] We have found host group for this host as: global
```

I need to clarify if the following config lines are related to the global traffic of the router, or by /32.

```
# Limits for Dos/DDoS attacks
threshold_pps = 3500
threshold_mbps = 100
threshold_flows = 1000
```
Many thanks,
Diego

**Comment by pavel-odintsov** [comment]
Hello!

All FNM's thresholds are per /32.

**Comment by dmayan** [comment]
Thanks Pavel,

And where I can configure a global threshold so I don't get my logs cluttered by those msgs ?

**Comment by pavel-odintsov** [comment]
You already configured it. 

I guess this issue already fixed.

Could you pull new version from Git this way:
```
wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl --use-git-master
```

**Comment by dmayan** [comment]
I redownloaded and updated and I'm getting the same message cluttering the logs. I have attached my .conf so you can check it, please.

Thanks!

[fastnetmon.zip](https://github.com/pavel-odintsov/fastnetmon/files/926323/fastnetmon.zip)

**Comment by pavel-odintsov** [comment]
Hello!

I have committed few fixes regarding your issue.

Could you install FNM again from current git master's version:
```
wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl --use-git-master
```

Thank you!

**Comment by dmayan** [comment]
Now it's working perfectly!! Thanks!!

**Comment by pavel-odintsov** [comment]
Awesome! Thank you so much for checking it!
