### ISSUE TITLE
Is it possible to use nProbe in conjunction with fastnetmon on single machine?

### ISSUE THREAD

**Issue by rwrocket** [pavel-odintsov/fastnetmon#662]
I have fastnetmon running for a while now and I love it. I also use grafana for graphicing bandwidth and I am capturing traffic with port mirroring and pfring.

I want to try nProbe on the same server as it is already working in the port mirror configuration. My reason for using nProbe is to send information to ntopng 
http://www.ntop.org/products/netflow/nprobe/

I believe installing nProbe may update the pfring version and possibly break Fastnetmon?

Pavel are you able to confirm if it is safe or not ?

**Comment by pavel-odintsov** [comment]
Hello!

It's an interesting case and we support it for netmap already. In netmap mode could have multiple applications reading from the same mirror interface without any performance issues (we use netmap monitor interfaces for such task).

I have no idea how you could achieve this goal.

But it's worth to mention that cases of vanilla PF_RING and PF_RING ZC are completely different. So, you could not use PF_RING vanilla for FNM and PF_RING ZC for ntop.

Finally, I'm not aware of options to read data from multiple application from single PF_RING or PF_RING ZC socket.

As definitely working case you could rebuild PF_RING with the same version as ntop uses and add second mirror interface to the same machine from switch. I used such approach some time ago when I did not have options to run multiple apps in the same traffic.

**Comment by lucaderi** [comment]
We have nProbe builds for FreeBSD where we can use netmap (PF_RING ZC is a Linux-only technology). So if netmap is able to support multiple consumers, I don't see a problem here.
