### ISSUE TITLE
Network Ports/NIC filters on fastnetmon

### ISSUE THREAD

**Issue by nidotech** [pavel-odintsov/fastnetmon#666]
I've a Edge BGP router with multiple NICs/uplinks, however, current fastnetmon implementation doesn't allow differentiation of traffic from different uplinks and cannot stop incoming DDOS traffic from each of them.

Since all the traffic coming from a single host (only one sflow stream), I cannot run multiple copies of fastnetmon to deal with the problem.

On the other hand, current sflow implementation does have 'datasource id' and 'input/output ifindex fields' which should be able to deal with the problem with interface filter.

**Comment by pavel-odintsov** [comment]
Hello!

Yes, that's right. FNM removes all information about a source of packets to unified processing pipeline and then process it. It's near-to-impossible to change this behaviour.  

As an option, you could use port mirror and mirror each uplink to a different port and analyse with a different instance of FastNetMon.
