### ISSUE TITLE
Maximum power of attack

### ISSUE THREAD

**Issue by mdpuma** [pavel-odintsov/fastnetmon#667]
Hello!

As a result of testing, I often notice that as attacks reach threshold values, appropriate triggers are executed, in which attack data is indicated that can already be predicted, because they are + - equal to the set threshold.

It would be great when unblocking an IP address to get information about how big the attack was, in order to show the maximum packet rate and bandwidth achieved.

**Comment by pavel-odintsov** [comment]
Добрый день!

Пометил как улучшение. Но при текущем дизайне информации об атаке, когда делается анбан детально нету, надо пробрасывать, это немного нетривиально.

**Comment by pavel-odintsov** [comment]
Advanced version can do it: https://fastnetmon.com/docs-fnm-advanced/fastnetmon-advanced-json-notify-script-in-python/ We have plans to sync JSON callbacks between community and advanced edition in future.
