### ISSUE TITLE
Can't build on VyOS, though did it many times

### ISSUE THREAD

**Issue by creanovafi** [pavel-odintsov/fastnetmon#670]
Hi,

Thanks for the perfect project. 
Using it for some years. But now get the next error when try to build on the one of my VyOS machines.

Scanning dependencies of target netflow_plugin
[ 93%] Building CXX object CMakeFiles/netflow_plugin.dir/netflow_plugin/netflow_collector.cpp.o
Linking CXX static library libpfring_hardware_filter_action.a
[ 93%] Built target pfring_hardware_filter_action
Linking CXX static library libpfring_plugin.a
[ 93%] Built target pfring_plugin
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:67:27: error: field 'h1' has incomplete type
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp: In function 'void flush_block(block_desc*)':
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:92:10: error: 'struct block_desc' has no member named 'h1'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp: In function 'void walk_block(block_desc*, int)':
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:96:25: error: 'struct block_desc' has no member named 'h1'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:101:29: error: 'struct block_desc' has no member named 'h1'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:103:21: error: invalid use of incomplete type 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:98:12: error: forward declaration of 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:110:32: error: invalid use of incomplete type 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:98:12: error: forward declaration of 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:111:35: error: invalid use of incomplete type 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:98:12: error: forward declaration of 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:116:63: error: invalid use of incomplete type 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:98:12: error: forward declaration of 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:119:89: error: invalid use of incomplete type 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:98:12: error: forward declaration of 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:126:31: error: invalid use of incomplete type 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:98:12: error: forward declaration of 'struct walk_block(block_desc*, int)::tpacket3_hdr'
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp: In function 'int setup_socket(std::string, int)':
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:150:19: error: 'TPACKET_V3' was not declared in this scope
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:188:25: error: aggregate 'setup_socket(std::string, int)::tpacket_req3 req' has incomplete type and cannot be defined
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:197:31: error: 'TP_FT_REQ_FILL_RXHASH' was not declared in this scope
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:236:27: error: 'PACKET_FANOUT_CPU' was not declared in this scope
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:240:71: error: 'PACKET_FANOUT' was not declared in this scope
/tmp/fastnetmon.build.dir.ah7KHUBasE/fastnetmon/src/afpacket_plugin/afpacket_collector.cpp:260:19: error: 'struct block_desc' has no member named 'h1'
make[2]: *** [CMakeFiles/afpacket_plugin.dir/afpacket_plugin/afpacket_collector.cpp.o] Error 1
make[1]: *** [CMakeFiles/afpacket_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX static library libnetmap_plugin.a
[ 93%] Built target netmap_plugin
Linking CXX static library libsflow_plugin.a
[ 93%] Built target sflow_plugin
Linking CXX static library libnetflow_plugin.a
[ 93%] Built target netflow_plugin
Linking CXX static library libfast_library.a
[ 93%] Built target fast_library
make: *** [all] Error 2
Can't build fastnetmon! at ./fastnetmon_install.pl line 1475, <STDIN> line 1.

Please advise.
Thanks.

**Comment by pavel-odintsov** [comment]
Hello!

Could you check https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/VyOS_INSTALL.md ? 

Well, VyOS is a very-very outdated version of Debian.

And probably it ships new version of kernel with old kernel headers which do not have any AF_PACKET support. 

You need to check that you have kernel headers for an actually running version of kernel.

**Comment by pavel-odintsov** [comment]
Otherwise, you need to download FNM manually, remove line `set (ENABLE_AFPACKET_SUPPORT ON)` from CMakeLisrs.txt and build it again.

**Comment by creanovafi** [comment]
Yeah, I know maybe. Thanks for your notice. I'll try to exclude this module.

**Comment by creanovafi** [comment]
I removed all lines point to AD_PACKETS but installer still tries to build with it. Advise please

**Comment by pavel-odintsov** [comment]
Have you executed cmake .. in build folder before make? :)

**Comment by creanovafi** [comment]
upgrading to linux-libc-dev_3.13.11-1+vyos1+helium11_amd64.deb solved problem with AF_PACKETS
Thanks.

**Comment by pavel-odintsov** [comment]
That's awesome!
