### ISSUE TITLE
Sorry but CPU affinity did not supported for your platform

### ISSUE THREAD

**Issue by creanovafi** [pavel-odintsov/fastnetmon#675]
Здравствуйте Павел,

в лог вываливается вот такая ошибка
VyOS процессоры X5660 с включенным HT 32 получается. Я так понимаю не распределяет по ядрам. Но почему ? А на каких платформах работает CPU affinity?
Спасибо.

**Comment by pavel-odintsov** [comment]
Добрый день!

Это не процессоры виноваты, мы используем библиотеку Boost и в ней функицонал для управления affinitiy добаили в версии 1.50. 

Скорее всего, она у вас старее, поэтому и выводится данная ошибка. Фикс - просить авторов скорее обновиться на более новую версию Debian =)
