### ISSUE TITLE
detect attack on a prefix

### ISSUE THREAD

**Issue by jeansalim** [pavel-odintsov/fastnetmon#688]
You already have implemented a per subnet counter with pps and mbps.

I am not currently implementing BGP banning, just launching a script using the help of notify_about_attack.sh.

Is it possible in any way to trigger notifiy_about_attack.sh when a subnet pps reaches a specific threshold or even when the total pps of all counted subnets/hosts exceeds this threshold.

We are an ISP, and the attacks we are getting are very distributed with low bandwidth and high pps, where each IP gets attacked with as low as 3k pps no more, but the total through is high enough to cripple our network.

**Comment by pavel-odintsov** [comment]
Hello!

We have similar FR for Advanced version but it's not implemented yet.  Right now I could suggest only custom code which parser /tmp/fastnetmon.dat and when pps/mbps for specific network exceed specified value and triggers attack manually.
