### ISSUE TITLE
sh: netstat: command not found for centos

### ISSUE THREAD

**Issue by lastsky** [pavel-odintsov/fastnetmon#690]
![screen shot 2017-10-02 at 23 55 11](https://user-images.githubusercontent.com/334280/31094052-319471ec-a7cd-11e7-961f-2caea176685f.jpg)

https://github.com/pavel-odintsov/fastnetmon/pull/689

**Comment by pavel-odintsov** [comment]
Hello!

Could you show complete output from install command?

**Comment by pavel-odintsov** [comment]
Replaced by: https://github.com/pavel-odintsov/fastnetmon/commit/c74470e92d6c804306c14eeeeb682de8e22e11bf and merged.

**Comment by denji** [comment]
`ss` is replacing `netstat`
