### ISSUE TITLE
PF_ring 6.6 vmware only capturing outbound traffic.

### ISSUE THREAD

**Issue by rwrocket** [pavel-odintsov/fastnetmon#694]
Fastnetmon fresh install on VMWARE Esxi 5.5 Ubuntu 14.04.05
PFring 6.6
Influxdb 1.1.0
Fastnetmon installed using sudo perl fastnetmon_install.pl --use-modern-pf-ring (pfring 6.03 was failing with the default setup script)

Log says unable to store to graphite and I can't see any data in influxdb using grafana.

Using fastnetmon_client I see only outgoing traffic and 0 incoming traffic for some reason.
Nothing has changed on the mirror port since this was previously working with another installation, and I copied my previously working config files off the decommissioned server (bad RAID) to this new Virtual machine.

I have attached log,config,screenshot of what is happening.
[4Pavel.zip](https://github.com/pavel-odintsov/fastnetmon/files/1504704/4Pavel.zip)

**Comment by pavel-odintsov** [comment]
Hello!

Mirror mode in VM is complicated. You need to check VMWARE guides about it. We do not have any options to tune it from FNM or PF_RING side.
