### ISSUE TITLE
FastNetMon seems did not listen the Iperf DDos attack.

### ISSUE THREAD

**Issue by liaodalin19903** [pavel-odintsov/fastnetmon#696]
Hi, friends, I use fastnetmon, get an issue there, describe is too much for GitHub Issues, I have a detail description on the bellow ServerFault link, if you have spare time, you can  check it on the bellow link:
https://serverfault.com/questions/891072/the-fastnetmon-did-not-listen-the-iperf-udp-datagrams

**Comment by pavel-odintsov** [comment]
Looks like your issue was solved already/
