### ISSUE TITLE
fails to buid on mips(el): undefined reference to `__sync_fetch_and_add_8'

### ISSUE THREAD

**Issue by bdrung** [pavel-odintsov/fastnetmon#703]
fastnetmon fails to build on the Debian architectures mips, mipsel, m68k, powerpc, sh4:
```
/usr/bin/c++  -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/fastnetmon-1.1.3+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -Wl,-z,relro -Wl,-z,now -rdynamic CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o  -o fastnetmon -lboost_thread -lboost_regex -lboost_program_options -lboost_system -lboost_chrono -lboost_date_time -lboost_atomic -lpthread -lhiredis -lmongoc-1.0 -lbson-1.0 libfast_dpi.a -llog4cpp -lpthread libpatricia.a libfastnetmon_pcap_format.a libipfix_rfc.a libfast_library.a libunified_parser.a libafpacket_plugin.a libsflow_plugin.a libnetflow_plugin.a libpcap_plugin.a libexample_plugin.a libnetmap_plugin.a -lndpi -lboost_thread -lboost_regex -lboost_program_options -lboost_system -lboost_chrono -lboost_date_time -lboost_atomic -lpthread libpatricia.a libfastnetmon_pcap_format.a -ljson-c libunified_parser.a libipfix_rfc.a -lluajit-5.1 -lpcap libfastnetmon_packet_parser.a 
CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o: In function `process_packet(simple_packet&)':
./obj-mipsel-linux-gnu/./src/fastnetmon.cpp:1698: undefined reference to `__sync_fetch_and_add_8'
./obj-mipsel-linux-gnu/./src/fastnetmon.cpp:1788: undefined reference to `__sync_fetch_and_add_8'
./obj-mipsel-linux-gnu/./src/fastnetmon.cpp:1789: undefined reference to `__sync_fetch_and_add_8'
./obj-mipsel-linux-gnu/./src/fastnetmon.cpp:1788: undefined reference to `__sync_fetch_and_add_8'
./obj-mipsel-linux-gnu/./src/fastnetmon.cpp:1789: undefined reference to `__sync_fetch_and_add_8'
CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o:./obj-mipsel-linux-gnu/./src/fastnetmon.cpp:1916: more undefined references to `__sync_fetch_and_add_8' follow
collect2: error: ld returned 1 exit status
CMakeFiles/fastnetmon.dir/build.make:135: recipe for target 'fastnetmon' failed
make[3]: *** [fastnetmon] Error 1
```

The problem is that these architectures do not provide a 64-bit versions of `__sync_fetch_and_add` (i.e. `__sync_fetch_and_add_8`):
```
bdrung@eller:~$ readelf -a /lib/mipsel-linux-gnu/libgcc_s.so.1 | grep __sync_add_and_fetch
     6: 00011060    36 FUNC    GLOBAL DEFAULT   13 __sync_add_and_fetch_4@@GCC_4.4.0
   108: 00010fa0    88 FUNC    GLOBAL DEFAULT   13 __sync_add_and_fetch_1@@GCC_4.4.0
   696: 00011000    88 FUNC    GLOBAL DEFAULT   13 __sync_add_and_fetch_2@@GCC_4.4.0
```

The atomic library does not provide `__sync_add_and_fetch`.

Debian-Bug: https://bugs.debian.org/869805

**Comment by bdrung** [comment]
Aaron M. Ucko wrote in the Debian bug:
> Oh, sorry, somebody will also need to port the code from the legacy
> __sync_* API to the current __atomic_* API from
> https://gcc.gnu.org/onlinedocs/gcc-7.3.0/gcc/_005f_005fatomic-Builtins.html#g_t_005f_005fatomic-Builtins
> (which is all that libatomic covers).
>

**Comment by pavel-odintsov** [comment]
Oh, it's interesting. I saw lib atomics already. It's worth to port FNM to new cross-platform approach.

**Comment by pavel-odintsov** [comment]
Hello!

I implemented it in https://github.com/pavel-odintsov/fastnetmon/commit/d5711bb3da43bff3f90a33c5d5ab9b5a262660c5 and https://github.com/pavel-odintsov/fastnetmon/commit/b6e6843d2e21bea1a2ca69643622cc4eb42d4d06

It wasn't tested very well because I do not have mips/powerpc/m68/sh4 machines yet.

Could you enable this option only for architectures where we have compilation issues?

Thank you!

**Comment by bdrung** [comment]
Looking at your commit d5711bb3da43bff3f90a33c5d5ab9b5a262660c5, I am a little bit confused. You replace `__sync_fetch_and_add` by `__atomic_add_fetch` which does the inverse according to the documentation. `__sync_fetch_and_add` returns the value of the variable *before* the addition, `__atomic_add_fetch` returns it *after* the addition. Isn't `__atomic_fetch_add` the direct replacement or am I missing something here?

Anyway, I tested your two commits in addition to my commit to enable linking to the atomic library on a Debian mipsel porter box and it compiled successfully.

**Comment by pavel-odintsov** [comment]
@bdrung thanks for proofreading my code! :) You're right! But I think we could keep it as because we ignore the return value and just need atomic increment. 

Great news about fixed builds!

**Comment by bdrung** [comment]
Right. :) So I will do an upload with that patch set now.

**Comment by bdrung** [comment]
So the number of patches in the Debian package rises to 22 patches now. :D
