### ISSUE TITLE
Segregate netflow sources

### ISSUE THREAD

**Issue by chasgames** [pavel-odintsov/fastnetmon#704]
Hello

We have multiple netflow sources sending data to fastnetmon, and in grafana we want to segregate the sources in the graphs. Is this possible? I can only find total statistics like fastnetmon.incoming.mbps, etc..

Thanks!

**Comment by pavel-odintsov** [comment]
Hello!

Could you explain what do you want in details, please? FastNetMon merges all sources together and exports only per IP and per subnet traffic information to Graphite/InfluxDB.

You could run one instance of FNM if you need options to export data about different data sources to different dashboards.

Also, FastNetMon Advanced provides traffic persistency backend and could export any kind of reports created from your traffic: https://fastnetmon.com/fastnetmon-advanced-traffic-persistency/

**Comment by chasgames** [comment]
Hi Pavel !

I want to differentiate the netflow traffic based on the origin of the netflow sender.

Currently all our netflow sources are merged together like you mentioned, we see there is value in keeping them separate for graph analysis (such as in NFsen).

Is this possible in current FNM?

Many Thanks

**Comment by pavel-odintsov** [comment]
Hello!

I do not think so. But you could deploy different FNM instances for each device.

**Comment by chasgames** [comment]
Ok Thanks we may try that
