### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [pavel-odintsov/fastnetmon#717]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your application as my Open Source Contribution?

Thanks before.

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for suggestion! I appreciate it! :) But we already have it (you can check our site, fastnetmon.com). I added it here also: https://github.com/pavel-odintsov/fastnetmon

**Comment by anharismail** [comment]
Okay, no problem Sir.
