### ISSUE TITLE
Help to install ExaBGP

### ISSUE THREAD

**Issue by prtomasi** [pavel-odintsov/fastnetmon#719]
Hello,

Installation on Ubuntu 16.04 gave me errors.
I've followed the instructions from https://fastnetmon.com/docs/exabgp_integration/
In the last step it showed me these errors:

root@fastnetmon:/etc# env exabgp.daemon.user=root exabgp.daemon.daemonize=true exabgp.daemon.pid=/var/run/exabgp.pid exabgp.log.destination=/var/log/exabgp.log exabgp /etc/exabgp_blackhole.conf
**exabgp: 20045 configuration environment file missing
exabgp: 20045 configuration generate it using "exabgp --fi > /usr/local/etc/exabgp/exabgp.env"**
root@fastnetmon:/etc#

root@fastnetmon:/etc# uname -a
Linux fastnetmon 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@fastnetmon:/etc# exabgp --version
ExaBGP : 3.4.20
Python : 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
Uname : #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017

Environment
the command showed an empty result:

root@fastnetmon:/etc# exabgp --di
root@fastnetmon:/etc#

Program output
no configuration file provided

The configuration file is located at /etc/exabgp_blackhole.conf
What did I miss?

**Comment by pavel-odintsov** [comment]
Hello!

ExaBGP's error reporting is very misleading :)

You can ignore this:
```
/log/exabgp.log exabgp /etc/exabgp_blackhole.conf
exabgp: 1363   configuration environment file missing
``

When you call following command:
```
env exabgp.daemon.user=root exabgp.daemon.daemonize=true exabgp.daemon.pid=/var/run/exabgp.pid exabgp.log.destination=/var/log/exabgp.log exabgp /etc/exabgp_blackhole.conf
```

ExaBGP will start in daemon mode in background:
```
ps aux|grep exabgp
root      1367  0.5  1.2  50272 12324 ?        S    21:56   0:00 /usr/bin/python /usr/local/bin/exabgp /etc/exabgp_blackhole.conf
root      1368  0.0  0.1  24364  1756 ?        S    21:56   0:00 /usr/bin/socat stdout pipe:/var/run/exabgp.cmd
root      1370  0.0  0.1  12948  1028 pts/0    S+   21:56   0:00 grep --color=auto exabgp
```

I just reproduced it with Ubuntu 16.04.

Also, you can check log file about any actions from ExaBGP:
```
cat /var/log/exabgp.log 
```

**Comment by prtomasi** [comment]
Great, my BGP peer is up now!

The hint you gave helped me to find the problem:

> cat /var/log/exabgp.log

Thanks Pavel :D 
(what a shame, it was my firewall on Mikrotik blocking the Linux IP)
