### ISSUE TITLE
Traffic scrubing

### ISSUE THREAD

**Issue by behzad-kh** [pavel-odintsov/fastnetmon#728]
Dear Pavel,
First off I woul like to thank you for creating such an amazing program.

Speaking of DDoS attack, does FNM support traffic scrubing? In other words does it show the source IP address of the attack which is mostly forged especially if FNM is receiving its traffic from port mirroring?

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for feedback!

Unfortunately, FastNetMon does not execute any traffic filtering. It works as sensor only. 

But you can use any BGP Flow Spec / RFC 5575 capable router as filter. FastNetMon can inject filtering rules to any router with such capability and filter our malicious traffic this way.

**Comment by behzad-kh** [comment]
Thanks for your quick response.

Is FNM capable of pushing source IP address through BGP Flow Spec?

**Comment by pavel-odintsov** [comment]
Hello!

It can do it but only in case when attack comes from single IP. According to our experience, it happens very very very rare. Almost all recent attacks have distributed character and attacks comes from thousands of unique IP address (often spoofed).
