### ISSUE TITLE
How to contribute to documentation?

### ISSUE THREAD

**Issue by Fohdeesha** [pavel-odintsov/fastnetmon#729]
Hi, I would like to contribute to the documentation of fastnetmon like I do for several other projects. For example: many typo and grammar fixes, add a guide on brocade sflow configuration, etc.

However I see you have moved all the documentation from the github repo to static content on your website, so I can no longer simply create a pull request. How do you suggest I contribute?

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for help! I do no think that we can delegate document editing permission in our CMS :( 

But think you can make patches from web site pages. Just download html page as is into GitHub report, edit it and share with us repo :)

We will integrate these changes.
