### ISSUE TITLE
Opnsense 18.7 adding support

### ISSUE THREAD

**Issue by CheckB** [pavel-odintsov/fastnetmon#730]
Hello friends!
Unfortunately I'm not a programmer, but this product is very interesting, it is especially interesting as a plugin for Opnsense.
In opnsense there is also a suricata (IDS). It would be very nice not only to see Fastnetmon in opnsense.

I found a brief information on the development of plugins for Opnsense https://docs.opnsense.org/development/examples/helloworld.html

And also opnsense has a very good community, which will gladly accept any changes, especially such a popular product

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for sharing your ideas!

As I understand, Opnsense uses FreeBSD and can use packages from it without any issues. And we already offer complete support for FreeBSD: https://www.freshports.org/net-mgmt/fastnetmon/ 

Unfortunately, we do not have any ways to contact with Opnsense team. But you can raise ticket to Opnsense guys to add it in default installation. 

We can offer all required help for better integration!

Thank you!

**Comment by CheckB** [comment]
> Unfortunately, we do not have any ways to contact with Opnsense team. But you can raise ticket to Opnsense guys to add it in default installation.

https://forum.opnsense.org
https://forum.opnsense.org/index.php?action=profile;u=10 If to him to write personally, he will answer. Always responds

https://github.com/opnsense

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for details! I will keep this issue open to collect more feedback. If receive enough interest, we will allocate time to work on this integration. 

Meanwhile, you can try installing FastNetMon manually on Opnsense and share your success story with Opnsense. That's best way to keep people's attention.

**Comment by CheckB** [comment]
@pavel-odintsov 
https://forum.opnsense.org/index.php?topic=9645.msg44656#msg44656

Look at the last post, please

**Comment by pavel-odintsov** [comment]
Hello!

I do not think that we have this information somewhere. You can setup lab and test it. From developer perspective I do not see any issues.

**Comment by pavel-odintsov** [comment]
This feature request is more about external product. Typically, we do not implement integrations with third party products because we have no such skills for their platform. We will be happy to help if someone from OPSense decides to allocate time and finish such migration. We have solid support with VyOS and you can try it instead as reference.
