### ISSUE TITLE
Feature Request: configuration file / directory for groups and host groups 

### ISSUE THREAD

**Issue by itayrozenberg** [pavel-odintsov/fastnetmon#732]
please add a feature to configure the network list, groups, hostgroups on a file external from the main configuration,

**Comment by pavel-odintsov** [comment]
Hello!

We have PR about it: https://github.com/pavel-odintsov/fastnetmon/pull/576 but it need more work. Feel free to pick it up and improve.

**Comment by pavel-odintsov** [comment]
This PR was abandoned due to author's decision to stop working on it. This logic feels complicated and we do not want to make community edition that complicated. Single file can be easily regenerated from configuration management software.
