### ISSUE TITLE
Grafana feature request

### ISSUE THREAD

**Issue by tolyod** [pavel-odintsov/fastnetmon#738]
we would like to have in Grafana the ability to view traffic over ip/network / asn in configuration with ClickHouse DB. 
Is that possible? 
what is necessary for this ?

**Comment by pavel-odintsov** [comment]
Hello!

We track this FR in ZenDesk and few days ago we asked for details. Can you check your email, please?

**Comment by pavel-odintsov** [comment]
Was implemented https://grafana.com/dashboards/8238 and https://grafana.com/dashboards/8241
