### ISSUE TITLE
astnetmon proccess is Crashing on "Segmentation fault"

### ISSUE THREAD

**Issue by itayrozenberg** [pavel-odintsov/fastnetmon#743]
hi Pavel

i'm using the Git Version of fastnetmon

when i try to enable Netflow_hooks.lua the fastnetmon proccess is Crashing on "Segmentation fault"
i ran it with gdb and i get this traceback:

#0  0x00007ffff66e1450 in ?? () from /usr/local/lib/libluajit-5.1.so.2
#1  0x00007ffff66e2d53 in lua_getfield () from /usr/local/lib/libluajit-5.1.so.2
#2  0x000000000046e0d1 in call_lua_function(std::string, lua_State*, std::string, void*) ()
#3  0x000000000048cf24 in process_netflow_packet_v5(unsigned char*, unsigned int, std::string) ()
#4  0x000000000048ed2d in process_netflow_packet(unsigned char*, unsigned int, std::string) ()
#5  0x000000000048f105 in start_netflow_collector(std::string, unsigned int) ()
#6  0x00000000004907cd in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(std::string, unsigned int), boost::_bi::list2<boost::_bi::value<std::string>, boost::_bi::value<int> > > >::run() ()
#7  0x00007ffff7bd127a in thread_proxy () from /lib64/libboost_thread-mt.so.1.53.0
#8  0x00007ffff6946e25 in start_thread () from /lib64/libpthread.so.0
#9  0x00007ffff50ddbad in clone () from /lib64/libc.so.6

can you help ?
thank you

**Comment by pavel-odintsov** [comment]
Hello!

Can you show your lua code? Does it work fine with standard lua function from FastNetMon's install? Can you show /etc/fastnetmon.conf?

Thank you!

**Comment by pavel-odintsov** [comment]
I'm closing this ticket because we cannot debug LUA related issues without LUA code used for it.
