### ISSUE TITLE
rfe: http_proxy

### ISSUE THREAD

**Issue by jnorell** [pavel-odintsov/fastnetmon#748]
The installer (fastnemton_install.pl) cannot be used without direct internet access; with very minor changes it can support an http proxy by setting environment variables (http_proxy and https_proxy, and possibly the uppercase variants as well, depending on the system).

On debian 9 I added 2 lines to the top of the installer:

$ENV{'http_proxy'}="http://xx.xx.xx.xx:3128/";
$ENV{'https_proxy'}="http://xx.xx.xx.xx:3128/";

(I also had to install the ca-certificates package, as a possible dependency.)  It's easy enough to add that commented out, and maybe that would be sufficient, but it seems if http_proxy and/or https_proxy env variables are already set (and mine are), they should be used.

**Comment by pavel-odintsov** [comment]
Hello!

Really good idea! Thank you for reporting it! I switched ticket to "enhancement".

**Comment by pavel-odintsov** [comment]
Hello!

We've reworked install logic completely and we use binary packages for installing FastNetMon and we download them using wget / curl who can respect proxy EVN options.
