### ISSUE TITLE
Кошмар перфекциониста

### ISSUE THREAD

**Issue by alexanderfefelov** [pavel-odintsov/fastnetmon#761]
На [GitHub-странице проекта](https://github.com/pavel-odintsov/fastnetmon) есть такая схема

![1](https://user-images.githubusercontent.com/5790321/56181135-e4750f00-6014-11e9-8d42-50b48d180f67.png)

Зелёным прямоугольником я отметил проблему. Прошу, умоляю, исправьте её, пожалуйста!

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for report! Done: https://github.com/pavel-odintsov/fastnetmon/commit/61ed75331db1ca94e87ec143000c2c88e2fb8421
