### ISSUE TITLE
Устарела версия Netmap API

### ISSUE THREAD

**Issue by Anito23** [pavel-odintsov/fastnetmon#764]
Привет!!!

Скрипт использует старую версию Netmap API, а точнее 11. Текущая версию 14. 

Если не сложно, замени, пожалуйста, файлы в https://github.com/pavel-odintsov/fastnetmon/tree/master/src/netmap_plugin/netmap_includes/net на более свежие с https://github.com/luigirizzo/netmap/tree/master/sys/net.

После замены, все собирается и работает корректно - проверено на Debian 8 x64. 

Спасибо.

**Comment by pavel-odintsov** [comment]
Thank you for feedback! Really good idea! Done!

**Comment by Anito23** [comment]
Еще необходимо добавить файл https://github.com/luigirizzo/netmap/blob/master/sys/net/netmap_legacy.h в директорию https://github.com/pavel-odintsov/fastnetmon/tree/master/src/netmap_plugin/netmap_includes/net

Иначе при сборке можно отхватить ошибку:
```
In file included from /usr/src/fastnetmon/src/netmap_plugin/netmap_includes/net/netmap_user.h:104:0,
                 from /usr/src/fastnetmon/src/netmap_plugin/netmap_collector.cpp:30:
/usr/src/fastnetmon/src/netmap_plugin/netmap_includes/net/netmap.h:393:27: fatal error: netmap_legacy.h: No such file or directory
 #include "netmap_legacy.h"
                           ^
compilation terminated.
CMakeFiles/netmap_plugin.dir/build.make:54: recipe for target 'CMakeFiles/netmap_plugin.dir/netmap_plugin/netmap_collector.cpp.o' failed
make[2]: *** [CMakeFiles/netmap_plugin.dir/netmap_plugin/netmap_collector.cpp.o] Error 1
CMakeFiles/Makefile2:426: recipe for target 'CMakeFiles/netmap_plugin.dir/all' failed
make[1]: *** [CMakeFiles/netmap_plugin.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```
Спасибо.

**Comment by pavel-odintsov** [comment]
Done: https://github.com/pavel-odintsov/fastnetmon/commit/8b5be4990ab334e09d15d62e77dc695a45cc8ea6
