### ISSUE TITLE
pf ring update

### ISSUE THREAD

**Issue by gthgame** [pavel-odintsov/fastnetmon#767]
i'm using latest kernel in debian 9 and i can't compile pf ring even with use_modern_pf_ring it's result in an error : error: implicit declaration of function ‘ACCESS_ONCE’

This is fied in latest PF_RING 7.4.0 . 

so i compiled and loaded pf_ring 7.4.0 and when i start fastnetmon it's resulting error : 

[PF_RING] Wrong RING version: kernel is 17, libpfring was compiled with 16

Can you fix this ? 

Cordialy,

**Comment by pavel-odintsov** [comment]
Hello!

Is it critical to use PF_RING for you? 

FastNetMon will be included into Debian 10 by default: https://packages.debian.org/buster/fastnetmon 

But due to licensing issues we do not support PF_RING in this case.

**Comment by pavel-odintsov** [comment]
We deprecated PF_RING for new distros in latest version: https://github.com/pavel-odintsov/fastnetmon/commit/2c87e24d930048c60604d31368b8ca55cbace5dc 

We recommend using AF_PACKET instead. For old distros we will support PF_RING.
