### ISSUE TITLE
Некорректное отображение версии

### ISSUE THREAD

**Issue by yerktoyn** [pavel-odintsov/fastnetmon#771]
Долго не мог понять почему собирается версия 1.1.3. После некоторых углублений обнаружил в исходниках 1.1.4: 

`set(FASTNETMON_APPLICATION_VERSION "1.1.3 master git-${GIT_LAST_COMMIT_HASH}")`

Мелочь, но ввела в ступор :)

**Comment by pavel-odintsov** [comment]
Thank you for reporting it! We will check it.

**Comment by pavel-odintsov** [comment]
We did this fix some time ago https://github.com/pavel-odintsov/fastnetmon/commit/df85edc2ddc53f60f17ef76e632bea3bd9f8ac11 but I think we forgot about it during release. I'll check it for next release to bump it correctly.
