### ISSUE TITLE
Allow comments in network_list and network_whitelist

### ISSUE THREAD

**Issue by detzen** [pavel-odintsov/fastnetmon#773]
For documentation purposes, it would be great to allow comments in network_list and network_whitelist.

When i comment out the whole line, it currently works, but throws an error in the logfile:
`2019-09-13 09:54:22,272 [ERROR] Can't parse line from subnet list: '# testcomment'`
I think a WARNING would be more accurate in this case.

Unfortunately, inline-comments doesn't work at all, because the whole line is ignored.
`2019-09-13 10:01:03,982 [ERROR] Can't parse line from whitelist: 1.2.3.0/27    # testcomment`

I think the function load_our_networks_list() in fastnetmon.cpp has to be rewritten respectively the parsing logic has to be expanded in this case.

Regards,
Alex

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for idea! You may try raising PR to implement it, it should not be complicated and I'll help with review. 

As alternative option you can use makefile or script to generate networks list from another format like JSON or YAML.

**Comment by romanstech** [comment]
Very good and healthy idea.

**Comment by pavel-odintsov** [comment]
Done: https://github.com/pavel-odintsov/fastnetmon/commit/f01b3175cc3c1132464142407a48c5a6b59c0ad9 https://github.com/pavel-odintsov/fastnetmon/commit/235cbc29dbbe0d025a7ba0b9417141028dc9d2cc

You can add comments using following syntax:
```
# It's DMZ zone
1.2.3.0/24
# Most important host ever
8.9.1.1/32
```

We added support for both networks list and networks whitelist.
