### ISSUE TITLE
Ban action failure

### ISSUE THREAD

**Issue by ed29** [pavel-odintsov/fastnetmon#791]
operating system name and version: centos 7 cloud
fastnetmon version: 1.1.3
issue:i use ab tool to test a web page,the fastnetmon_client shows *banned*,but actually there is not ban action takes,ab test can still goes on.

[fastnetmon.conf.txt](https://github.com/pavel-odintsov/fastnetmon/files/4142592/fastnetmon.conf.txt)
[fastnetmon.log](https://github.com/pavel-odintsov/fastnetmon/files/4142584/fastnetmon.log)

**Comment by pavel-odintsov** [comment]
Hello!

Let me explain. FastNetMon does not ban and does not block any host. It just calls script or created BGP announce. If you need ban actions then you need to change notify_about_attack.sh accordingly.

**Comment by ed29** [comment]
@pavel-odintsov 
Ok,i get it now.

Thank you!
