### ISSUE TITLE
Option to hide template flowset_id info log message

### ISSUE THREAD

**Issue by cuddylier** [pavel-odintsov/fastnetmon#792]
* What capture engine are you using: netflow, sflow, miror?
IPFIX on a Juniper MX240

In normal operation when using a MX240 with ipfix and fastnetmon community 1.1.4, the following message is printed in the /var/log/fastnetmon.log every 4 - 6 seconds, 4 times:

`[INFO] We don't have a template for flowset_id: 512 but it's not an error if this message disappears in 5-10 seconds. We need some time to learn it!`

Pavel mentioned to me in Slack that this is shown as the MX router doesn't send all the templates to fastnetmon but this is meaningless in the community edition as it doesn't support options therefore I suggest that a configuration option is added to hide this info message to avoid spamming the logs unnecessarily.

**Comment by pavel-odintsov** [comment]
You may disable such "options" templates from router's side actually. We're working on some plans to improve Netflow support in future.
