### ISSUE TITLE
Junos 20 - IPFIX data not being collected, client shows 0 pps

### ISSUE THREAD

**Issue by dark1587** [pavel-odintsov/fastnetmon#798]
# If you want to solve your issue please read following information below

First of all, please check following steps:
* Do you have latest FastNetMon version? Yes
* Do we have similar tickets already? I found some old tickets #653 and #553, but nothing related to my issue with Junos 20

If it does not help, please fill information below:
* Your operating system name and version? CentOS 7.1
* Please attach your /etc/fastnetmon.conf configuration file: [fastnetmon.conf.txt](https://github.com/pavel-odintsov/fastnetmon/files/4467457/fastnetmon.conf.txt)
* What capture engine are you using: netflow, sflow, miror? netflow; IPFIX specifically
* If you are using netflow or sflow, please specify version, vendor name, model name and firmware of agent device.

- Juniper SRX300
- Junos 20.1r1
- IPFIX Template

* Please attach /var/log/fastnetmon.log: 
[fastnetmon.log](https://github.com/pavel-odintsov/fastnetmon/files/4467461/fastnetmon.log)

Then please describe your issue as detailed as possible! Thanks you :)

So I am trying to get IPFIX working for DDoS detection from my Juniper SRX300. I can see traffic coming into my CentOS 7 host running FastNetMon, but when I run the CLI tool I see nothing in the output:

<img width="955" alt="Screen Shot 2020-04-13 at 1 34 27 AM" src="https://user-images.githubusercontent.com/6076098/79083576-fe7c2700-7d26-11ea-9f22-4d5fcaf73528.png">

The log is filling up wit the following messages:

    2020-04-12 22:38:15,654 [INFO] We don't have a template for flowset_id: 264 but it's not an error if this message disap
pears in 5-10 seconds. We need some time to learn it!
    2020-04-12 22:38:41,704 [INFO] We don't have a template for flowset_id: 265 but it's not an error if this message disap
pears in 5-10 seconds. We need some time to learn it!
    2020-04-12 22:38:53,733 [INFO] We don't have a template for flowset_id: 264 but it's not an error if this message disap
pears in 5-10 seconds. We need some time to learn it!

I do see fastnetmon is listening on port 2055:

    [root@fastnetmon ~]# netstat -an | grep 2055
    udp        0      0 0.0.0.0:2055            0.0.0.0:*                          

I've made sure rp_filter is disabled as well:

    [root@fastnetmon ~]# sysctl -a | grep \\.rp_filter
    net.ipv4.conf.all.rp_filter = 0
    net.ipv4.conf.default.rp_filter = 0
    net.ipv4.conf.eth0.rp_filter = 0
    net.ipv4.conf.eth1.rp_filter = 0
    net.ipv4.conf.lo.rp_filter = 0
    net.ipv4.conf.sit0.rp_filter = 0
    net.ipv4.conf.tunl0.rp_filter = 0

And my Junos config:

    show conf chaynes@gatekeeper> show configuration forwarding-options 
    sampling {
        input {
            rate 100;
            run-length 0;
        }
        instance {
            s1 {
                input {
                    rate 100;
                    run-length 0;
                }
                family inet {
                    output {
                        flow-server 10.200.15.6 {
                            port 2055;
                            version-ipfix {
                                template {
                                    ipv4-test;
                                }
                            }
                        }
                        flow-server 10.200.15.7 {
                            port 2055;
                            version-ipfix {
                                template {
                                    ipv4-test;
                                }
                            }
                        }
                        inline-jflow {
                            source-address 10.200.15.1;
                        }
                    }
                }
                family inet6 {
                    output {
                        flow-server 10.200.15.6 {
                            port 2055;
                            version-ipfix {
                                template {
                                    ipv6-test;
                                }
                            }
                        }
                        flow-server 10.200.15.7 {
                            port 2055;
                            version-ipfix {
                                template {
                                    ipv6-test;
                                }
                            }
                        }
                        inline-jflow {
                            source-address 10.200.15.1;
                        }
                    }
                }
            }
        }
    }

I've also attached a PCAP with shows the traffic coming into the server:

    [root@fastnetmon ~]# tcpdump -i eth1 -w ipfix.pcap -c 10 "port 2055"
    tcpdump: listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
    10 packets captured
    10 packets received by filter
    0 packets dropped by kernel

[ipfix.pcap.zip](https://github.com/pavel-odintsov/fastnetmon/files/4467499/ipfix.pcap.zip)

Please let me know if you need anything else!

**Comment by pavel-odintsov** [comment]
Hello!

I can suggest configuring IPFIX export according to our own guides. There are many mandatory options on JunOS side: https://fastnetmon.com/docs/junos_integration/

**Comment by pavel-odintsov** [comment]
You've shared pcap file with very small number of packets. I suppose your router did not send template packets to FastNetMon and it will not able to decode them.
