### ISSUE TITLE
can not install fastnetmon on CentOS 7

### ISSUE THREAD

**Issue by vhostvn** [pavel-odintsov/fastnetmon#799]
Hi,

I follow this guide: https://fastnetmon.com/install/ and unable to install fastnetmon on CentOS 7

our OS version: CentOS Linux release 7.7.1908 (Core)

Log error:

`[ 73%] Building CXX object CMakeFiles/ipfix_rfc.dir/ipfix_rfc.cpp.o
Linking CXX static library libipfix_rfc.a
[ 73%] Built target ipfix_rfc
Scanning dependencies of target netflow_plugin
[ 80%] Building CXX object CMakeFiles/netflow_plugin.dir/netflow_plugin/netflow_collector.cpp.o
Linking CXX static library libnetflow_plugin.a
[ 80%] Built target netflow_plugin
Scanning dependencies of target netmap_plugin
[ 86%] Building CXX object CMakeFiles/netmap_plugin.dir/netmap_plugin/netmap_collector.cpp.o
Linking CXX static library libnetmap_plugin.a
[ 86%] Built target netmap_plugin
Scanning dependencies of target fastnetmon
[ 93%] Building CXX object CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o] Error 4
make[1]: *** [CMakeFiles/fastnetmon.dir/all] Error 2
make: *** [all] Error 2
[root@fastnetmon ~]#`

How to fix this issue?

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for query!

It looks like memory related error. Do you have any errors about OOM in dmesg? Can you extend memory size?

**Comment by vhostvn** [comment]
Thanks for your fast reply.

It seems memory is not enough to compile software. I have extended memory from 512MB to 2GB.

I'm installing now, i will revert back if this fix the case.

**Comment by vhostvn** [comment]
Completed:

> [100%] Built target fastnetmon_client
> Install fastnetmon to dir /opt/fastnetmon
> Create stub configuration file
> If you have any issues, please check /var/log/fastnetmon.log file contents
> Please add your subnets in /etc/networks_list in CIDR format one subnet per line
> We found systemd enabled distro and created service: fastnetmon.service
> You could run it with command: systemctl start fastnetmon.service
> We have built project in 4.72 minutes
