### ISSUE TITLE
Kind of attack community edition support?

### ISSUE THREAD

**Issue by operations999** [pavel-odintsov/fastnetmon#819]
Hello,
On official site I believe commercial product support all these kind of attacks?

    syn_flood: TCP packets with enabled SYN flag
    udp_flood: flood with UDP packets (so recently in result of amplification)
    icmp flood: flood with ICMP packets
    ip_fragmentation_flood: IP packets with MF flag set or with non zero fragment offset
    DNS amplification
    NTP amplification
    SSDP amplification
    SNMP amplification

Does community edition support all these attacks and is there CLI ?
fastnetmon_client show limited flow data.
Thanks

**Comment by pavel-odintsov** [comment]
Hello!

These attacks can be mitigated by Advanced edition in Flow Spec mode: https://fastnetmon.com/fastnetmon-flow-spec-mitigation-mode-algorithm-details/ But attack type detection in Advanced edition is same.
