### ISSUE TITLE
fastnetmon

### ISSUE THREAD

**Issue by whitedays2007** [pavel-odintsov/fastnetmon#826]
# If you want to solve your issue please read following information below

First of all, please check following steps:
* Do you have latest FastNetMon version? If not, please upgrade to 1.1.3 version.
* Do we have similar tickets already? Please check [bug tracker](https://github.com/pavel-odintsov/fastnetmon/issues) and [Mailing list](https://groups.google.com/forum/#!forum/fastnetmon) about similar issues.

If it does not help, please fill information below:
* Your operating system name and version?
* Please attach your /etc/fastnetmon.conf configuration file
* What capture engine are you using: netflow, sflow, miror?
* If you are using netflow or sflow, please specify version, vendor name, model name and firmware of agent device.  
* Please attach /var/log/fastnetmon.log

Then please describe your issue as detailed as possible! Thanks you :)

**Comment by pavel-odintsov** [comment]
No details provided, closing.
