### ISSUE TITLE
Feature request: IPv6 per network counters export to influxDB

### ISSUE THREAD

**Issue by dmayan-ss** [pavel-odintsov/fastnetmon#827]
As the title says, please implement per IPv6 network counters export to influxDB, as is already implemented in IPv4

Thanks

**Comment by dmayan-ss** [comment]
Anyone? Pavel?

**Comment by pavel-odintsov** [comment]
We've added it recently: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/metrics/influxdb.cpp#L341
