### ISSUE TITLE
Feature Request: Hostgroup ban time

### ISSUE THREAD

**Issue by shyrwall** [pavel-odintsov/fastnetmon#846]
If possible please add ban_time per host group :)

**Comment by pavel-odintsov** [comment]
Thank you for feedback! I've added FR tag for this ticket.

**Comment by pavel-odintsov** [comment]
I believe it will make things more complicated and we're doing hard job by keeping them simple. We have no plans about extending hostgroup capabilities over per hostgroup thresholds but it may be done in future.
