### ISSUE TITLE
Install Script works in interactive mode

### ISSUE THREAD

**Issue by interpoint-tech** [pavel-odintsov/fastnetmon#854]
I had an issue while upgrading from 1.1.3 to 1.1.7 using the script
sudo perl fastnetmon_install.pl --install-ci-packages

The problem is that the install script is operating silently

This means I was not aware it was asking for input to confirm action relating to the overwriting of fastnetmon.conf with the maintainers version.

I managed to get over the situation by inputting Y at the right time - I had to guess this was the required input as it was upgrading silently.

I hope this makes sense, as it may cause others to have the same problem during upgrade.

**Comment by interpoint-tech** [comment]
I had an issue while upgrading from 1.1.3 to 1.1.7 using the script 
sudo perl fastnetmon_install.pl --install-ci-packages


This is the install log..

root@fastnetmon ~# cat /tmp/fastnetmon_install_20756.log
Install startedWe are calling command: LANG=C apt-get update

Hit http://security.debian.org jessie/updates InRelease
Hit https://repos.influxdata.com jessie InRelease
Ign http://ppa.launchpad.net jessie InRelease
Ign http://archive.turnkeylinux.org jessie-security InRelease
Get:1 http://packages.netxms.org jessie InRelease [3584 B]
Hit https://packages.grafana.com stable InRelease
Hit https://packages.grafana.com stable InRelease
Ign http://archive.turnkeylinux.org jessie InRelease
Ign http://ppa.launchpad.net jessie Release.gpg
Ign http://ppa.launchpad.net jessie Release
Ign http://http.debian.net jessie InRelease
Hit http://archive.turnkeylinux.org jessie-security Release.gpg
Hit http://http.debian.net jessie Release.gpg
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [781 kB]
Hit http://archive.turnkeylinux.org jessie Release.gpg
Hit http://http.debian.net jessie Release
Get:3 https://repos.influxdata.com jessie/stable amd64 Packages [923 B]
Err http://packages.netxms.org jessie InRelease

Hit http://archive.turnkeylinux.org jessie-security Release
Get:4 http://security.debian.org jessie/updates/main Translation-en [401 kB]
Get:5 https://packagecloud.io wheezy InRelease [35 B]
Hit http://security.debian.org jessie/updates/contrib amd64 Packages
Get:6 https://repos.influxdata.com jessie/stable Translation-en [151 B]
Hit http://archive.turnkeylinux.org jessie Release
Hit http://security.debian.org jessie/updates/contrib Translation-en
Ign https://packagecloud.io wheezy InRelease
Err http://ppa.launchpad.net jessie/main amd64 Packages
  404  Not Found [IP: 91.189.95.83 80]
Get:7 https://repos.influxdata.com jessie/stable Translation-en [151 B]
Ign http://ppa.launchpad.net jessie/main Translation-en
Get:8 https://packagecloud.io wheezy Release.gpg [35 B]
Get:9 https://packages.grafana.com stable/main Translation-en [231 B]
Ign https://packagecloud.io wheezy Release.gpg
Get:10 https://repos.influxdata.com jessie/stable Translation-en [151 B]
Hit http://http.debian.net jessie/main amd64 Packages
Hit http://http.debian.net jessie/contrib amd64 Packages
Hit http://http.debian.net jessie/contrib Translation-en
Hit http://http.debian.net jessie/main Translation-en
Get:11 https://packagecloud.io wheezy Release [35 B]
Ign https://packagecloud.io wheezy Release
Get:12 https://repos.influxdata.com jessie/stable Translation-en [151 B]
Get:13 https://repos.influxdata.com jessie/stable Translation-en [151 B]
Ign https://repos.influxdata.com jessie/stable Translation-en
Get:14 https://packages.grafana.com stable/main Translation-en [224 B]
Get:15 https://packagecloud.io wheezy/main amd64 Packages/DiffIndex [146 B]
Ign https://packagecloud.io wheezy/main amd64 Packages/DiffIndex
Hit http://archive.turnkeylinux.org jessie-security/main amd64 Packages
Get:16 https://packagecloud.io wheezy/main Translation-en [146 B]
Get:17 https://packages.grafana.com stable/main Translation-en [231 B]
Hit http://archive.turnkeylinux.org jessie/main amd64 Packages
Get:18 https://packagecloud.io wheezy/main amd64 Packages [35 B]
Get:19 https://packages.grafana.com stable/main Translation-en [224 B]
Get:20 https://packagecloud.io wheezy/main Translation-en [146 B]
Get:21 https://packagecloud.io wheezy/main amd64 Packages [35 B]
Get:22 https://packages.grafana.com stable/main Translation-en [231 B]
Get:23 https://packagecloud.io wheezy/main Translation-en [146 B]
Get:24 https://packages.grafana.com stable/main Translation-en [224 B]
Ign http://archive.turnkeylinux.org jessie-security/main Translation-en
Get:25 https://packagecloud.io wheezy/main amd64 Packages [35 B]
Ign http://archive.turnkeylinux.org jessie/main Translation-en
Get:26 https://packagecloud.io wheezy/main Translation-en [146 B]
Get:27 https://packages.grafana.com stable/main Translation-en [231 B]
Get:28 https://packagecloud.io wheezy/main amd64 Packages [35 B]
Get:29 https://packages.grafana.com stable/main Translation-en [224 B]
Get:30 https://packagecloud.io wheezy/main Translation-en [146 B]
Ign https://packagecloud.io wheezy/main Translation-en
Get:31 https://packages.grafana.com stable/main Translation-en [231 B]
Get:32 https://packagecloud.io wheezy/main amd64 Packages [35 B]
Ign https://packages.grafana.com stable/main Translation-en
Err https://packagecloud.io wheezy/main amd64 Packages
  HttpError429
Get:33 https://packages.grafana.com stable/main Translation-en [224 B]
Ign https://packages.grafana.com stable/main Translation-en
Fetched 33.1 kB in 3s (8942 B/s)
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.netxms.org jessie InRelease: The following signatures were invalid: KEYEXPIRED 1585054160 KEYEXPIRED 1585054160 KEYEXPIRED 1585054160 KEYEXPIRED 1585054160 KEYEXPIRED 1585054160

W: Failed to fetch http://packages.netxms.org/debian/dists/jessie/InRelease

W: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]

W: Failed to fetch https://packagecloud.io/grafana/stable/debian/dists/wheezy/main/binary-amd64/Packages  HttpError429

W: Some index files failed to download. They have been ignored, or old ones used instead.
Command finished with code 0

We are calling command: LANG=C DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold" libpcap0.8 libatomic1

Reading package lists...
Building dependency tree...
Reading state information...
libatomic1 is already the newest version.
libpcap0.8 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Command finished with code 0

(Reading database ... 110433 files and directories currently installed.)
Preparing to unpack fastnetmon_1.1.7_amd64.deb ...
Unpacking fastnetmon (1.1.7) over (1.1.6) ...
Setting up fastnetmon (1.1.7) ...

Configuration file '/etc/fastnetmon.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** fastnetmon.conf (Y/I/N/O/D/Z) [default=N] ? 

The problem is that the install script is operating silently

This means I was not aware it was asking for input to confirm action relating to the overwriting of fastnetmon.conf with the maintainers version. 

I managed to get over the situation by inputting Y at the right time - I had to guess this was the required input as it was upgrading silently.

I hope this makes sense, as it may cause others to have the same problem during upgrade.

**Comment by pavel-odintsov** [comment]
Thank you so much for reporting it! We will change logic to suppress requests about configuration upgrade.

**Comment by pavel-odintsov** [comment]
It's actually weird:
```LANG=C DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confold"```

These options must prevent it from working this way.

**Comment by pavel-odintsov** [comment]
Let's wait for reproduce, we cannot replicate it.
