### ISSUE TITLE
gobgp community support

### ISSUE THREAD

**Issue by csszep** [pavel-odintsov/fastnetmon#855]
Hi!

I testing Fastnetmon 1.1.7 (community)  with gobgp integration.
In fastnetmon.conf there is no "gobgp_community=" variable similar to "exabgp_community = 65001:666"
It is possible to set the community in the injected routes from Fastnetmon? 

thx
csszep

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for idea! You may implement workaround using GoBGP Policies for now. 

I've converted this issue into feature request.

**Comment by pavel-odintsov** [comment]
Try this: 
```gobgp_community_host = 65001:666
gobgp_community_subnet = 65001:777```
