### ISSUE TITLE
Grafana Graphs

### ISSUE THREAD

**Issue by herzadigital** [pavel-odintsov/fastnetmon#886]
This is related to Issue # 864 (https://github.com/pavel-odintsov/fastnetmon/issues/864)

OK, it seems the graph from https://grafana.com/grafana/dashboards/1605 is no longer functioning for the current FNM version. Thats why it doesnt show any reading in the graph. 

I try to download modified JSON of Total Transit Traffic graph from https://forum.mikrotik.com/viewtopic.php?t=124958 and now it shows graph properly.

But I really want to use the FastNetMon Advanced Total traffic, do you have the updated JSON file for this?

**Comment by pavel-odintsov** [comment]
Hello!

I'm sorry but graphs for Advanced version are not compatible with graphs for Community version.
