### ISSUE TITLE
Mikrotik plugin

### ISSUE THREAD

**Issue by hexicans** [pavel-odintsov/fastnetmon#891]
Hi,

I write here because I use mikrotik_plugin to blackhole IPs automatically. Ban works, but unban is not work : 

` Use of undefined constant ip_mikrotik - assumed 'ip_mikrotik' (this will throw an Error in a future version of PHP)`

Do you have an idea ? The connection to mikrotik is done but can't remove route.

Thanks !
Axel

**Comment by hexicans** [comment]
Seem not the route cause.

I'have re-run again and i'have noted the process don't terminated : 

PHP Warning:  Use of undefined constant ip_mikrotik - assumed 'ip_mikrotik' (this will throw an Error in a future version of PHP) in /root/mikrotik_plugin/fastnetmon_mikrotik.php on line 31
PHP Warning:  Use of undefined constant api_user - assumed 'api_user' (this will throw an Error in a future version of PHP) in /root/mikrotik_plugin/fastnetmon_mikrotik.php on line 32
PHP Warning:  Use of undefined constant api_pass - assumed 'api_pass' (this will throw an Error in a future version of PHP) in /root/mikrotik_plugin/fastnetmon_mikrotik.php on line 33
PHP Warning:  Use of undefined constant ip_mikrotik - assumed 'ip_mikrotik' (this will throw an Error in a future version of PHP) in /root/mikrotik_plugin/fastnetmon_mikrotik.php on line 65
PHP Warning:  Use of undefined constant api_user - assumed 'api_user' (this will throw an Error in a future version of PHP) in /root/mikrotik_plugin/fastnetmon_mikrotik.php on line 65
PHP Warning:  Use of undefined constant api_pass - assumed 'api_pass' (this will throw an Error in a future version of PHP) in /root/mikrotik_plugin/fastnetmon_mikrotik.php on line 65
(not back to "root@fastnetmon:~# ")

**Comment by pavel-odintsov** [comment]
@elmaxid can you look on it, please?

**Comment by hexicans** [comment]
Temporary, I have recoded the unban process, I do a connection to router, using php ssh. It is not secure but it's work.

**Comment by pavel-odintsov** [comment]
Can you try updating to latest stable RouterOS version and trying it again? @elmaxid have tried replicating issue in test lab without success.

**Comment by hexicans** [comment]
Pavel,
I can't test now because the router is the core router of our network.
I close the issue and I will reopen it when update is done.
