### ISSUE TITLE
Email problem

### ISSUE THREAD

**Issue by scaetano84** [pavel-odintsov/fastnetmon#892]
Hello. How can I disable an email that receives notifications? I have not found it anywhere.

Thank you!

**Comment by pavel-odintsov** [comment]
Hello!

email address is specified in notify script which can be fond here: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/notify_about_attack.sh#L14 in configuration it specified this way https://github.com/pavel-odintsov/fastnetmon/blob/master/src/fastnetmon.conf#L169
