### ISSUE TITLE
with ipv6 enabled Subnet load: stops counting after 4 min

### ISSUE THREAD

**Issue by deivisonmarteleto** [pavel-odintsov/fastnetmon#901]
# If you want to solve your issue please read following information below

First of all, please check following steps:
* Do you have latest FastNetMon version? If not, please upgrade to 1.1.3 version.
* Do we have similar tickets already? Please check [bug tracker](https://github.com/pavel-odintsov/fastnetmon/issues) and [Mailing list](https://groups.google.com/forum/#!forum/fastnetmon) about similar issues.

If it does not help, please fill information below:
* Your operating system name and version?
* Please attach your /etc/fastnetmon.conf configuration file
* What capture engine are you using: netflow, sflow, miror?
* If you are using netflow or sflow, please specify version, vendor name, model name and firmware of agent device.  
* Please attach /var/log/fastnetmon.log

Then please describe your issue as detailed as possible! Thanks you :)

**Comment by deivisonmarteleto** [comment]
with ipv6 enabled Subnet load: stops counting after 4 min:

In version 1.1.9, when enabling BAN ipv6 support, we notice in the command "/ opt / fastnetmon / fastnetmon_client" and by Grafana (influxdb) that Subnet Load crashes. But "IPs ordered by: packets" continues to count.

**Comment by pavel-odintsov** [comment]
What IPv6 per host traffic in same time? Does it work fine?

**Comment by deivisonmarteleto** [comment]
Only IPv4 is crashing. IPv6 continues to count.

**Comment by deivisonmarteleto** [comment]
Olá!
I conducted an investigation and realized that:

IPv4 subnet accounting freezes, when an IPv6 attack (BAN) is identified IPv4 subnet accounting freezes.

But IPv6 subnet accounting continues to work.

**Comment by pavel-odintsov** [comment]
Hello!

Thank you for update!

Can you check your fatnetmon.log for following error messages "find traffic counters for subnet".  If you can confirm some of them then we have idea about fix. 

Thank you!

**Comment by deivisonmarteleto** [comment]
Hello guys,

I've been testing version 1.2.2, I noticed something strange.

when I put an ip in "ban" manual (using API), the subnet traffic count for... This local using command "fastnetmon-community/app/bin/fastnetmon_client "

and in influx I see that tb stops counting...

have you caught this?

it only goes back to normal when I restart fastnetmon

I didn't find anything abnormal in the log

**Comment by pavel-odintsov** [comment]
At Telegram chat we've confirmed that it's not a crash:

![image](https://user-images.githubusercontent.com/2744166/181792410-5514a644-ad54-4e17-b2a8-ee28c7252f9f.png)

![image](https://user-images.githubusercontent.com/2744166/181792430-38c571c2-298b-451f-b576-08899c161448.png)

**Comment by pavel-odintsov** [comment]
I think it's good time for complete per subnet counters rewrite and I did it: https://github.com/pavel-odintsov/fastnetmon/commit/4a7ee74718106c597c370bd1cce62b0a4aa64f79

**Comment by pavel-odintsov** [comment]
Please wait for CI to build new developer packages and install it that way:
```
wget https://install.fastnetmon.com/installer -Oinstaller
sudo chmod +x installer
sudo ./installer -install_community_edition -developer_version
```

**Comment by deivisonmarteleto** [comment]
Success!! problem solved.

**Comment by pavel-odintsov** [comment]
![image](https://user-images.githubusercontent.com/2744166/181818295-24364a26-c2d6-4de7-9816-22388fb2df9e.png)

Next stable release 1.2.3 will include fix for this bug.
