### ISSUE TITLE
No Flows Mikrotik @ v9

### ISSUE THREAD

**Issue by expohl** [pavel-odintsov/fastnetmon#906]
Using virtual ova appliance with Mikrotik 6.47.8  w/ netflow v9, connection tracking is enabled but flows aren't propagating, hoping someone will know what to do?

root@fcli> show host_counters bytes incoming
xx.xx.30.254     122322 pps 1269 mbps 0 flows/s
xx.xx.31.112     45121 pps 468 mbps 0 flows/s
xx.xx.31.102     42521 pps 446 mbps 0 flows/s
xx.xx.232.4      44054 pps 443 mbps 0 flows/s
xx.xx.232.2      44126 pps 434 mbps 0 flows/s
xx.xx.232.1      40801 pps 411 mbps 0 flows/s
xx.xx.232.3      40709 pps 409 mbps 0 flows/s
xx.xx.232.5      37183 pps 377 mbps 0 flows/s
xx.xx.31.247     32419 pps 344 mbps 0 flows/s
xx.xx.31.230     29720 pps 305 mbps 0 flows/s

* Please attach your /etc/fastnetmon.conf configuration file
**cat: /etc/fastnetmon.conf: No such file or directory
root@fastnetmon:/home/fastnetmon#
**

* What capture engine are you using: Netflow, sFlow, miror?
**Netflow v9**
* If you are using Netflow or sFlow, please specify version, vendor name, model name and firmware of agent device.  
**Mikrotik 6.47.8 netflow v9**

* Please attach /var/log/fastnetmon.log
** cat /var/log/fastnetmon.log
cat: /var/log/fastnetmon.log: No such file or directory**

Then please describe your issue as detailed as possible! Thanks you :)

****

**Comment by pavel-odintsov** [comment]
Hello!

This one for Advanced version, in this case you need to contact with support team, it's independent product from community edition.

You can enable flow tracking this way:
```
sudo fcli set main enable_connection_tracking enable
sudo fcli commit
```
