### ISSUE TITLE
Feature request: create additional thresholds, actions for well-known amplification attacks.

### ISSUE THREAD

**Issue by l1ght13aby** [pavel-odintsov/fastnetmon#911]
It would be great to have additional thresholds and maybe separate actions for well known vulnarable applications like DNS, NTP and etc.
We can match such applications by a pattern port + protocol (always UDP AFAIK).
List to start: https://us-cert.cisa.gov/ncas/alerts/TA14-017A

**Comment by pavel-odintsov** [comment]
Hello!

Thank you so much for an idea! We will consider it as an option for future development.

**Comment by pavel-odintsov** [comment]
Do you have any insights about efficiency of such approach?

**Comment by l1ght13aby** [comment]
Hello Pavel,

Using fastnetmon in ISP environment makes it more complicated to make accurate thresholds for subnets used for NAT (NAT boxes have different load) and endusers (also very big difference). And we should have huge thresholds to avoid unwanted blackholing.
Our fellow ISP uses custom solution for DDoS attack detection which works like way I described in first message and their practice proved us it's efficiency.
Due to big variety of our customers traffic we really can't have enough flexibility looking at all flows.
We have tested our partner's solution (passing our traffic through their ASN) and it works well for us. 
Having less thresholds gives us opportunity to better detect attacks targeted to subnet or even many subnets.

**Comment by elmaxid** [comment]
Very interesting the way to detect DDoS. 
Do you know the name of the DDoS solutions which use this algorithms?

Br 

M.

**Comment by pavel-odintsov** [comment]
It can be done using state of the art flexible thresholds in Advanced edition: https://fastnetmon.com/docs-fnm-advanced/flexible-thresholds/

**Comment by pavel-odintsov** [comment]
Advanced version has logic to cover this case: https://fastnetmon.com/docs-fnm-advanced/escalation-script-for-fastnetmon-advanced/
