### ISSUE TITLE
Need Notify Code that Connected External smtp server

### ISSUE THREAD

**Issue by raminmalekghasemi** [pavel-odintsov/fastnetmon#912]
# If you want to solve your issue please read following information below

First of all, please check following steps:
* Do you have latest FastNetMon version? If not, please upgrade to latest [stable version](https://github.com/pavel-odintsov/fastnetmon/releases)
* Do we have similar tickets already? Please check [bug tracker](https://github.com/pavel-odintsov/fastnetmon/issues) and [Mailing list](https://groups.google.com/forum/#!forum/fastnetmon) about similar issues.

If it does not help, please fill information below:
* Your operating system name and version?
* Please attach your /etc/fastnetmon.conf configuration file
* What capture engine are you using: Netflow, sFlow, miror?
* If you are using Netflow or sFlow, please specify version, vendor name, model name and firmware of agent device.  
* Please attach /var/log/fastnetmon.log

Then please describe your issue as detailed as possible! Thanks you :)
Hi Dear Friends I need .sh fiel for email alert notification that used external mail server and Can edit usernam ( source mail address ) and password ( Password OF mail address) 
if you have please Share with me ???

**Comment by pavel-odintsov** [comment]
Hello!

I'm sorry but it's not directly related with project itself, please ask community for such questions.
