### ISSUE TITLE
New version 1.2.0 does not download gobgp packages 

### ISSUE THREAD

**Issue by deivisonmarteleto** [pavel-odintsov/fastnetmon#914]
I performed the standard procedure for installing version 1.2.0 and realized that the gobgp package was not downloaded. 

wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
sudo perl fastnetmon_install.pl 

OS: CENTOS7

**Comment by pavel-odintsov** [comment]
Thank you!

Fixed in https://github.com/pavel-odintsov/fastnetmon/commit/b65742b13c7f69eca7b11b75757c4c9595b566b5 

Please wait for CI (~1h+) and then install version from CI:
```
wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl 
sudo perl fastnetmon_install.pl --install-ci-packages
``
