### ISSUE TITLE
no data or traffic

### ISSUE THREAD

**Issue by mokakuw** [pavel-odintsov/fastnetmon#926]
# If you want to solve your issue please read following information below

First of all, please check following steps:
* Do you have latest FastNetMon version? If not, please upgrade to 1.1.3 version. yes
* Do we have similar tickets already? Please check [bug tracker](https://github.com/pavel-odintsov/fastnetmon/issues) and [Mailing list](https://groups.google.com/forum/#!forum/fastnetmon) about similar issues. no

If it does not help, please fill information below:
* Your operating system name and version? ubuntu 20:04 LTS
* Please attach your /etc/fastnetmon.conf configuration file
[fastnetmon.conf.txt](https://github.com/pavel-odintsov/fastnetmon/files/8323766/fastnetmon.conf.txt)

* What capture engine are you using: netflow, sflow, miror? idont know iam new to linux
* If you are using netflow or sflow, please specify version, vendor name, model name and firmware of agent device.  
* Please attach /var/log/fastnetmon.log

Then please describe your issue as detailed as possible! Thanks you :)

hi i have problem there is no data from netmon
![image](https://user-images.githubusercontent.com/71259297/159471763-c627ebe7-8cea-494a-9466-87b0b0499b2b.png)
and 
![image](https://user-images.githubusercontent.com/71259297/159471834-3eb2057e-3bb0-48db-97ad-23b5d5b96c9e.png)

rp filter is off iam using and virtual machine from amazon please help me iam new at linux i followed this toutorial https://fastnetmon.com/docs-fnm-advanced/advanced-visual-traffic/

**Comment by mokakuw** [comment]
iam hositng vpn on the vps with pritunl

**Comment by mokakuw** [comment]
![image](https://user-images.githubusercontent.com/71259297/159474547-937edc92-9e69-45ba-b51c-4e267fef69cc.png)

**Comment by pavel-odintsov** [comment]
Hello!

These graphs https://fastnetmon.com/docs-fnm-advanced/advanced-visual-traffic/ are only for commercial edition, they do not work for community edition. For community edition you need to manually configure everything.

To capture traffic you need to do basic configuration and at least enable mirror mode:
```
mirror_afpacket = on
interfaces = ethXXX
```

**Comment by mokakuw** [comment]
can you please tell me how do i do that my linux exprience are little bit bad

**Comment by mokakuw** [comment]
![image](https://user-images.githubusercontent.com/71259297/159480954-3c87fbf8-e183-40ac-86e3-c86969e8ef49.png)

i installedit from https://fastnetmon.com/docs-fnm-advanced/advanced-visual-traffic/  and still same issue

**Comment by mokakuw** [comment]
what should i do to enable mirror mode and interfaces

**Comment by pavel-odintsov** [comment]
I can recommend watching this video https://www.youtube.com/watch?v=cTzt54suq4Y It provides detailed overview of all things.

**Comment by mokakuw** [comment]
ok thank you i will watch it it tell u if my issue solved

**Comment by mokakuw** [comment]
but bro this is 2 hour long there is any shorter video ?

**Comment by pavel-odintsov** [comment]
This video is the most complete about configuration. For now you just need to open /etc/fastnetmon.conf and set options I've shared above.

**Comment by mokakuw** [comment]
ok bro i will set the options and let you know

**Comment by mokakuw** [comment]
okay its working 
![image](https://user-images.githubusercontent.com/71259297/159487937-0a644268-b00a-48ae-8b92-e6e9bf294401.png)


but grafana not working 
![image](https://user-images.githubusercontent.com/71259297/159487983-5b3e5aa8-3697-4804-89e0-70b2c5c3da0c.png)

**Comment by mokakuw** [comment]
how can i do that

**Comment by mokakuw** [comment]
iam so so sorry bro iam new at linux

**Comment by pavel-odintsov** [comment]
Just open /etc/fastnetmon.conf and check section about influxdb

**Comment by mokakuw** [comment]
let me retsart grafana and check

**Comment by mokakuw** [comment]
no nothing

**Comment by mokakuw** [comment]
my bad just rebooted my vps and its working 
![image](https://user-images.githubusercontent.com/71259297/159508194-600ef6a9-0678-491f-80fb-e5e613b36397.png)

**Comment by mokakuw** [comment]
how can i do a alert

**Comment by pavel-odintsov** [comment]
This dashboard is not compatible with latest community version. 

I can see that original problem is solved. If you have more questions I can recommend reaching community channels.

**Comment by mokakuw** [comment]
ok bro 
thank you so much :3
