### ISSUE TITLE
fastnetmon 1.2.3 build issue on macOS

### ISSUE THREAD

**Issue by chenrui333** [pavel-odintsov/fastnetmon#949]
Trying to build against the release 1.2.3, but ran into the following build failure

```
/opt/homebrew/include/boost/stacktrace/detail/collect_unwind.ipp:33:2: error: "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if _Unwind_Backtrace is available without `_GNU_SOURCE`."
#error "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if _Unwind_Backtrace is available without `_GNU_SOURCE`."
 ^
1 error generated.
```

relates to https://github.com/Homebrew/homebrew-core/pull/113728

---

Package and Environment Details (include every applicable attribute)
- Package Name/Version: boost/1.80.0
- Operating System+version: macOS
- Compiler+version:  Clang: 14.0.0 build 1400

**Comment by pavel-odintsov** [comment]
Hello!

Thank you so much for working on Formula upgrade.

Yep, I think I know root cause of it. We've added stack trace logging via Boost and I think MacOS wants some special flags for it.

I'll check it and update you after.

**Comment by chenrui333** [comment]
Thanks!

**Comment by pavel-odintsov** [comment]
I just fixed our CI for MacOS https://github.com/pavel-odintsov/fastnetmon/commit/fb06b56120555bc746e010f30a04505fc0e8fdd5 and replicated this error: https://app.circleci.com/pipelines/github/pavel-odintsov/fastnetmon/854/workflows/cdac09ce-8cd3-4ad5-95e2-b0b98d4aeeb4/jobs/12660

**Comment by pavel-odintsov** [comment]
```in file included from /usr/local/include/boost/stacktrace/safe_dump_to.hpp:217:
/usr/local/include/boost/stacktrace/detail/collect_unwind.ipp:33:2: error: "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if _Unwind_Backtrace is available without `_GNU_SOURCE`."
#error "Boost.Stacktrace requires `_Unwind_Backtrace` function. Define `_GNU_SOURCE` macro or `BOOST_STACKTRACE_GNU_SOURCE_NOT_REQUIRED` if _Unwind_Backtrace is available without `_GNU_SOURCE`."
 ^
1 error generated.
make[2]: *** [CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o] Error 1
make[1]: *** [CMakeFiles/fastnetmon.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by chenrui333** [comment]
I find a build patch working in my local, just file a PR for it. :)

**Comment by pavel-odintsov** [comment]
Thank you so much for preparing it, I just merged PR, waiting for CI to finish.

**Comment by pavel-odintsov** [comment]
It worked fine, thank you: https://app.circleci.com/pipelines/github/pavel-odintsov/fastnetmon/855/workflows/8156fc64-e2fd-43e8-89c5-321011cd8fdf/jobs/12680
