### ISSUE TITLE
Speed calculation malfunctions when system time is changed

### ISSUE THREAD

**Issue by salfers** [pavel-odintsov/fastnetmon#954]
A few months ago we had an issue where Fastnetmon would regularly report extremely high speeds that were impossible in our network (e.g. 120000 Mbit) and ban lots of IPs that were not under attack.
Short log excerpt:
<pre>
2022-09-05 11:53:15,676 [ERROR] Negative delay for traffic calculation -7199 Skipped iteration
2022-09-05 11:53:16,676 [ERROR] Negative delay for traffic calculation -7198 Skipped iteration
2022-09-05 11:53:17,677 [ERROR] Negative delay for traffic calculation -7197 Skipped iteration
</pre>

We figured out this issue together with your support (we are a Fastnetmon Advanced customer) and they recommend us to disable NTP time sync.

I looked through the code and found the origin of the message. I think the situation could easily be improved:
https://github.com/pavel-odintsov/fastnetmon/blob/529375f8815f654aeeffe59ba6795bfc95ca3608/src/fastnetmon_logic.cpp#L2155-L2184

If you used a monotonic clock instead of wall-time then the timestamp would never jump forwards or backwards and the calculations would be protected from this bug. C++ provides a monotonic clock with [`std::chrono::steady_clock`](https://en.cppreference.com/w/cpp/chrono/steady_clock).

Looking forward to your reply.

**Comment by pavel-odintsov** [comment]
Hello!

Thank you so much for your detailed feedback. 

We have separate issue to track this behaviour: https://features.fastnetmon.com/feature-requests/p/handle-case-when-time-moves-backward-gracefully

Thank you for your proposal, we will test it carefully and try to apply in future releases.

**Comment by pavel-odintsov** [comment]
We've setup lab to replicate this issue on Ubuntu 22.04. So we did following preparations.

In default Ubuntu installation NTP is enabled: 
```
timedatectl
               Local time: Mon 2023-01-16 16:37:33 GMT
           Universal time: Mon 2023-01-16 16:37:33 UTC
                 RTC time: Mon 2023-01-16 16:37:34
                Time zone: Europe/London (GMT, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

To manually adjust time for our tests we need to disable NTP:
```
timedatectl set-ntp off
```

Then we can setup time manually:
```
timedatectl set-time 16:36:47
```

To isolate behaviour as in FastNetMon we've prepared app:
```
#include <iostream>
#include <unistd.h>
#include <sys/time.h>

int main() {
    while (true) {
        sleep(1);

        struct timeval current_time;
        gettimeofday(&current_time, NULL);
        
        std::cout << "sec: " << current_time.tv_sec << " usec: " << current_time.tv_usec << std::endl; 
    }
}
```

Then we run it and moved time back for 2 minutes with set-time:
```
sec: 1673887485 usec: 609435
sec: 1673887486 usec: 609555
sec: 1673887487 usec: 609887
sec: 1673887488 usec: 610230
sec: 1673887489 usec: 610505
sec: 1673887490 usec: 610599
sec: 1673887491 usec: 610691
sec: 1673887492 usec: 611023
sec: 1673887493 usec: 611262
sec: 1673887494 usec: 611706
sec: 1673887495 usec: 611806
sec: 1673887427 usec: 333649 <---- time moved backwards 
sec: 1673887428 usec: 333728
sec: 1673887429 usec: 333801
sec: 1673887430 usec: 333885
sec: 1673887431 usec: 333973
sec: 1673887432 usec: 334068
```

So it's very clear that this issue is root cause for sure.

**Comment by pavel-odintsov** [comment]
Another time source we use it time() function.

Let's replicate issue for it too:
```
#include <iostream>
#include <unistd.h>
#include <sys/time.h>

int main() {
    while (true) {
        sleep(1);

        time_t current_time;

        time(&current_time);

        std::cout << "sec: " << current_time << std::endl; 
    }
}
```

Then I moved time for ~6 minutes back:
```
sec: 1673889678
sec: 1673889679
sec: 1673889680
sec: 1673889681
sec: 1673889682
sec: 1673889683
sec: 1673889684
sec: 1673889685
sec: 1673889686
<--- time moves backwards here
sec: 1673889287
sec: 1673889288
```

**Comment by pavel-odintsov** [comment]
Let's try native option as @salfers recommended using native C++ version.

Example app:

```
#include <iostream>
#include <chrono>
#include <unistd.h>

int main() {
    while (true) {
        auto start = std::chrono::steady_clock::now();
        sleep(1);
        auto end = std::chrono::steady_clock::now();       

        std::chrono::duration<double> diff = end - start;

        std::cout << "sec: " << diff.count() << std::endl; 
    }
}
```

Then I run it and tried moving time back and forward for few minutes:
```
sec: 1.00008
sec: 1.00008
sec: 1.00006
sec: 1.00006
sec: 1.00006
sec: 1.00007
sec: 1.00007
sec: 1.00007
sec: 1.00006
sec: 1.00005
sec: 1.00006
sec: 1.00007
sec: 1.00007
sec: 1.00007
sec: 1.00007
sec: 1.00007
sec: 1.00007
sec: 1.00007
sec: 1.00006
sec: 1.00006
sec: 1.00006
```

Neat and very stable!

**Comment by pavel-odintsov** [comment]
@salfers may I kindly ask you for testing this new logic?

You can install it on test VM using this approach:
```
wget https://install.fastnetmon.com/installer -Oinstaller
sudo chmod +x installer
sudo ./installer -install_community_edition  -developer_version
```

After confirming that it's fine with community and finishing internal QA phase we will port it to Advanced.

**Comment by pavel-odintsov** [comment]
We've included this fix into stable release of Advanced edition: https://github.com/FastNetMon/fastnetmon-advanced-releases/releases/tag/v2.0.333

Packages for all available platforms will be built in next hours.

**Comment by salfers** [comment]
Great news, thank you! We will upgrade our internal systems immediately and report back in case there are an issues.
