### ISSUE TITLE
fastnetmon_api_client unban / get_banlist: after unban IP is never -permanently- removed from the banlist

### ISSUE THREAD

**Issue by tyler0891** [pavel-odintsov/fastnetmon#958]
OS: Debian 11.1
Capture engine:  AF_PACKET
Version: 1.2.4 master git-d32dc372591d795ede7e6c42045cda62d96b95af

Problem:
To troubleshoot BGP blackhole functionality after an update, I typically try to manually ban / unban an IP.  With the version tested, when a -manually- banned client is unbanned (using fastnetmon_api_client) it is never -permanently- removed from the banlist, but is removed from GoBGP advertisements.

To duplicate:
fastnetmon_api_client ban {IP}
fastnetmon_api_client unban {IP}
fastnetmon_api_client get_banlist {IP}

Output in fastnetmon.log
[fastnetmon.log](https://github.com/pavel-odintsov/fastnetmon/files/10346840/fastnetmon.log)

**Comment by pavel-odintsov** [comment]
Was it only for IPv4 or IPv6 too?

**Comment by pavel-odintsov** [comment]
We've reworked this logic completely https://github.com/pavel-odintsov/fastnetmon/commit/4a052e9a8c349219250611aaea00d2b5c6969795 and it should not happen again.
