### ISSUE TITLE
Install fails with webserver error 405

### ISSUE THREAD

**Issue by PtDragon** [pavel-odintsov/fastnetmon#981]
13:27:00 Starting installation of FastNetMon Community 1.2.4
13:27:00 Apply sysctl configuration changes
13:27:00 Disable rp_filter for all interfaces
13:27:00 Installing on Debian 11.6 platform
13:27:00 Update package manager cache
13:27:08 Installing libncurses dependency package
13:27:08 Download binary package
13:27:09 Cannot download file for Debian 11.6 with error: Non successful response code: 405

**Comment by pavel-odintsov** [comment]
Hello!

This error code means that query was blocked for compliance / sanctions reasons by one of our vendors.
