### ISSUE TITLE
Database suggestion for Fastnetmon

### ISSUE THREAD

**Issue by paulocoghi** [pavel-odintsov/fastnetmon#992]
After reading the blog post "FastNetMon in search of perfect database for configuration and state storage", I would like to suggest ustore, from ukv project, available at [github.com/unum-cloud/ustore](https://github.com/unum-cloud/ustore).

The numbers presented on the official documentation are interesting: https://unum-cloud.github.io/ustore/

**Comment by pavel-odintsov** [comment]
Hello!

Thank you very much for your proposal. We will review capabilities of this database.
